#!/bin/bash

PROG="/opt/miq/bin/miqhost"
PROGNAME=`basename $PROG`

isrunning() {
	pidof -o %PPID $PROG 2>&1 > /dev/null
	return $?
}

killit() {
	for SIG in "INT" "KILL"
	do
		kill -s $SIG $1 >/dev/null 2>&1
		for count in 1 2 3 4 5
		do
			sleep 5
			isrunning
			if [ $? -ne 0 ]
			then
				break
			fi
		done
		isrunning
		if [ $? -ne 0 ]
		then
			break
		fi
	done
}

start() {
	echo -n $"Starting $PROG: "
	if isrunning $PROG
	then
		echo $"cannot start $PROG: $PROG is already running."
		return 1
	fi
	
	nohup $PROG 2>&1 > /dev/null &
	RV=$?
	
	if [ $RV -eq 0 ]
	then
		echo $"succeeded."
		touch /var/lock/subsys/miqhostd
	else
		echo $"failed."
	fi
	return $?
}

stop() {
	echo -n $"Stopping $PROG: "
	DPID=`pidof -o %PPID $PROGNAME`
	if [ $? -ne 0 ]
	then
		echo "cannot stop $PROG: $PROG is not running"
		return 1
	fi
	
	set $DPID
	
	if [ $# -eq 2 ]
	then
		if [ "$1" -gt "$2" ]
		then
			DPID="$1"
		else
			DPID="$2"
		fi
	else
		DPID="$1"
	fi
	
	killit $DPID
	RV=$?
	
	if [ $RV -eq 0 ]
	then
		echo $"succeeded."
	else
		echo $"failed."
	fi
	return $?
}

restart() {
	stop
	start
}

status() {
	DPID=`pidof -o %PPID $PROGNAME`
	
	if [ $? -eq 0 ]
	then
		echo $"$PROGNAME (pids: $DPID) is running."
		exit 0
	else
		echo $"$PROGNAME is stopped."
		exit 3
	fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  status) 
        status
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

echo $"Done"
