module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_Azure_CloudManager_Provision < MiqAeServiceManageIQ_Providers_CloudManager_Provision
    expose_eligible_resources :resource_groups
  end
end
