---
exclude_paths:
- ".git/"
- "**.yml"
- "**.svg"
- "app/assets/javascripts/dhtmlx*/"
- "config/dictionary_strings.rb"
- "config/model_attributes.rb"
- "config/yaml_strings.rb"
- "db/schema.rb"
- "db/schema.yml"
- "db/fixtures/**/*.yml"
- "db/migrate/20130923182042_collapsed_initial_migration.rb"
- "gems/pending/spec/"
- "gems/pending/test/"
- "gems/pending/*/test/"
- "gems/pending/metadata/linux/test/Packages"
- "gems/pending/metadata/linux/test/tc_LinuxUtils.rb"
- "gems/pending/VcoWebService/vmwo.wsdl"
- "gems/pending/VMwareWebService/wsdl41/"
- "locale/"
- "public/javascripts/timeline/"
- "spec/"
- "test/"
- "tmp/"
- "vendor/assets/"
engines:
  brakeman:
    # very slow :sad_panda:
    enabled: false
  bundler-audit:
    # requires Gemfile.lock
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    # Still failing :sad_panda:
    enabled: false
    channel: "eslint-2"
  fixme:
    # let's enable later
    enabled: false
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
    config: '.rubocop_cc.yml'
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rake"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
