---
exclude_paths:
- ".git/"
- "**.gif"
- "**.html"
- "**.json"
- "**.png"
- "**.svg"
- "**.xml"
- "**.yaml"
- "**.yml"
- "config/dictionary_strings.rb"
- "config/model_attributes.rb"
- "config/yaml_strings.rb"
- "db/schema.rb"
- "db/schema.yml"
- "db/fixtures/**/*.yml"
- "db/migrate/20130923182042_collapsed_initial_migration.rb"
- "locale/"
- "spec/"
- "test/"
- "tmp/"
- "vendor/assets/"
engines:
  brakeman:
    # very slow :sad_panda:
    enabled: false
  bundler-audit:
    # requires Gemfile.lock
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      concurrency: 1
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    # let's enable later
    enabled: false
  markdownlint:
    # let's enable later
    enabled: false
  rubocop:
    enabled: true
    config: '.rubocop_cc.yml'
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_base.yml"
    path: ".rubocop_base.yml"
  - url: "https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_cc_base.yml"
    path: ".rubocop_cc_base.yml"
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rake"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
