---
version: '2'
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 11
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
plugins:
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: 'rubocop-0-69'
exclude_patterns:
- config/dictionary_strings.rb
- config/model_attributes.rb
- config/yaml_strings.rb
- db/schema.rb
- lib/generators/**/templates/
- node_modules/
- spec/
- test/
- tmp/
- vendor/
