languages:
  Ruby: true
  JavaScript: true
exclude_paths:
- "app/assets/javascripts/dhtmlx*/*"
- "app/assets/javascripts/dynatree*/*"
- "app/assets/javascripts/SlickGrid*/*"
- "gems/pending/spec/*"
- "gems/pending/test/*"
- "gems/pending/*/test/*"
- "public/javascripts/timeline/*"
- "spec/*"
- "test/*"
- "spa_ui/self_service/client/**/*.spec.js"
- "spa_ui/self_service/client/test-helpers/*"
- "spa_ui/self_service/gulp/*"
- "spa_ui/self_service/gulpfile.js"
- "spa_ui/self_service/karma.conf.js"
- "spa_ui/self_service/bower_components/*"
- "spa_ui/self_service/node_modules/*"
- "spa_ui/self_service/.tmp/*"
