version: '2'
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/base.yml
    path: styles/base.yml
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/cc_base.yml
    path: styles/cc_base.yml
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 11
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
plugins:
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: rubocop-0-82
exclude_patterns:
- node_modules/
- spec/
- test/
- tmp/
- vendor/
