inherit_from:
- https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop.yml
#
# Overrides
#
GlobalVars:
  AllowedVariables:
  # Loggers
  - $audit_log
  - $api_log
  - $aws_log
  - $fog_log
  - $log
  - $miq_ae_logger
  - $policy_log
  - $rails_log
  - $rhevm_log
  - $kube_log
  - $scvmm_log
  - $vim_log
  # In Automate methods
  - $evm
#
# Special Exclusions
#
AllCops:
  Exclude:
    - config/toolbar_strings.rb
    - gems/pending/VMwareWebService/wsdl41/vimws25MappingRegistry.rb
ClassAndModuleCamelCase:
  Exclude:
    - lib/miq_automation_engine/service_models/*.rb
FileName:
  Exclude:
    - lib/miq_automation_engine/service_models/*.rb
    - config/toolbar_strings.rb
