# VmOrTemplate Daily performance chart layouts
--- 
- :title: CPU (Mhz)
  :type: Line
  :columns:
  - cpu_usagemhz_rate_average
  - min_cpu_usagemhz_rate_average
  - max_cpu_usagemhz_rate_average
  - trend_max_cpu_usagemhz_rate_average
  - resource.cpu_usagemhz_rate_average_high_over_time_period
  - resource.cpu_usagemhz_rate_average_low_over_time_period
  :menu: 
  - Chart-Current-Hourly:Hourly for this day
  - Timeline-Current-Daily:Daily events on this VM
  - Timeline-Current-Hourly:Hourly events on this VM
  :applies_to_method: cpu_mhz_available?

- :title: CPU (%)
  :type: Line
  :columns:
  - cpu_usage_rate_average
  - min_cpu_usage_rate_average
  - max_cpu_usage_rate_average
  - trend_max_cpu_usage_rate_average
  - resource.cpu_usage_rate_average_high_over_time_period
  - resource.cpu_usage_rate_average_low_over_time_period
  :menu:
  - Chart-Current-Hourly:Hourly for this day
  - Timeline-Current-Daily:Daily events on this VM
  - Timeline-Current-Hourly:Hourly events on this VM
  :max_value: 100.4
  :decimals: 1
  :applies_to_method: cpu_percent_available?

- :title: Virtual Machine CPU States
  :type: StackedArea
  :columns:
  - v_pct_cpu_ready_delta_summation
  - v_pct_cpu_used_delta_summation
#  - v_pct_cpu_wait_delta_summation
  :menu:
  - Chart-Current-Hourly:Hourly for this day
  - Timeline-Current-Daily:Daily events on this VM
  - Timeline-Current-Hourly:Hourly events on this VM
  :max_value: 100.4
  :decimals: 1
  :applies_to_method: cpu_ready_available?

- :title: Memory (MB)
  :type: Line
  :columns:
  - derived_memory_used
  - min_derived_memory_used
  - max_derived_memory_used
  - trend_max_derived_memory_used
  - resource.derived_memory_used_high_over_time_period
  - resource.derived_memory_used_low_over_time_period
  :menu: 
  - Chart-Current-Hourly:Hourly for this day
  - Timeline-Current-Daily:Daily events on this VM
  - Timeline-Current-Hourly:Hourly events on this VM
  :applies_to_method: memory_mb_available?

- :title: Disk I/O (KBps)
  :type: Line
  :columns:
  - disk_usage_rate_average
  - min_disk_usage_rate_average
  - max_disk_usage_rate_average
  - trend_max_disk_usage_rate_average
  :menu: 
  - Chart-Current-Hourly:Hourly for this day
  - Timeline-Current-Daily:Daily events on this VM
  - Timeline-Current-Hourly:Hourly events on this VM

- :title: Network I/O (KBps)
  :type: Line
  :columns:
  - net_usage_rate_average
  - min_net_usage_rate_average
  - max_net_usage_rate_average
  - trend_max_net_usage_rate_average
  :menu: 
  - Chart-Current-Hourly:Hourly for this day
  - Timeline-Current-Daily:Daily events on this VM
  - Timeline-Current-Hourly:Hourly events on this VM
