require "spec_helper"

describe EmsRefresh::Refreshers::OpenstackRefresher do
  before(:each) do
    _guid, _server, zone = EvmSpecHelper.create_guid_miq_server_zone
    @ems = FactoryGirl.create(
      :ems_openstack,
      :zone      => zone,
      :hostname  => "1.2.3.4",
      :ipaddress => "1.2.3.4",
      :port      => 5000)
    @ems.update_authentication(:default => {:userid => "admin", :password => "password"})
  end

  it "will record an error when trying to perform a full refresh against RHOS Havana" do
    # NOTE: Do not delete this cassette.  It was hand edited and will not be
    # regenerated by VCR
    refresh_ems_with_cassette(@ems, "#{described_class.name.underscore}_rhos_havana_with_error")

    assert_failed_refresh
  end

  def assert_failed_refresh
    @ems.last_refresh_status.should == "error"
  end

  def refresh_ems_with_cassette(ems, cassette_name)
    @ems.reload

    # Caching OpenStack info between runs causes the tests to fail with:
    #   VCR::Errors::UnusedHTTPInteractionError
    # Reset the cache so HTTP interactions are the same between runs.
    @ems.reset_openstack_handle

    # We need VCR to match requests differently here because fog adds a dynamic
    #   query param to avoid HTTP caching - ignore_awful_caching##########
    #   https://github.com/fog/fog/blob/master/lib/fog/openstack/compute.rb#L308
    VCR.use_cassette(cassette_name, :match_requests_on => [:method, :host, :path]) do
      EmsRefresh.refresh(ems)
    end

    @ems.reload
  end
end
