# Middleware Server real time performance chart layouts
---
- :title: JVM Heap Usage (Bytes)
  :type: Line
  :columns:
  - mw_heap_used
  - mw_heap_committed
  - mw_heap_max

- :title: JVM Non Heap Usage (Bytes)
  :type: Line
  :columns:
  - mw_non_heap_used
  - mw_non_heap_committed

- :title: GC Duration (ms)
  :type: Line
  :columns:
  - mw_accumulated_gc_duration

- :title: Web Sessions
  :type: Line
  :columns:
  - mw_aggregated_active_web_sessions
  - mw_aggregated_expired_web_sessions
  - mw_aggregated_rejected_web_sessions
