source 'https://rubygems.org'
if RUBY_PLATFORM =~ /mingw/
  gem "win32-process", "=0.5.1"
  gem "win32-service"
end

# TODO: Fix AWS tests now that our api specs and the soap4r 1.6.0 specs pass on 1.8.7/1.9.3
gem "actionwebservice", "=3.1.0", :git => "git://github.com/ManageIQ/actionwebservice.git", :tag => "v3.1.0-1"

# Locally modified and required
gem "activesupport", "=3.2.17", :git => "git://github.com/ManageIQ/rails.git", :tag => "vendored-3.2.17-7"

# Not locally modified and not required
gem "binary_struct",        "~>1.0.1", :require => false
gem "ezcrypto",             "=0.7",    :require => false
gem "facade",               "~>1.0.5", :require => false  # Used by util/pathname2.rb
gem "httpclient",           "~>2.2.4", :require => false
gem "log4r",                "=1.1.8",  :require => false
gem "more_core_extensions", "~>1.1.0", :require => false
gem "nokogiri",             "~>1.5.0", :require => false
gem "Platform",             "=0.4.0",  :require => false
gem "rubyzip",              "=0.9.5",  :require => false  # TODO: Review 0.9.7 breaking log collection in FB14646
gem "rufus-lru",            "~>1.0.5", :require => false
gem "rufus-scheduler",      "=2.0.19", :require => false
gem "soap4r",               "=1.6.0",  :require => false, :git => "git://github.com/ManageIQ/soap4r.git", :tag => "v1.6.0-2"
gem "uuidtools",            "~>2.1.3", :require => false

# Locally modified but not required
gem "handsoap",    "~>0.2.5",   :require => false, :git => "git://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-2"

# There were some gems from the old 1.8.6 environment that have not been brought
# over for SmartProxy on Windows.  We may need them later as we test other Smart
# Proxy Features, see: https://github.com/ManageIQ/cfme_build/issues/7
