class FixMissingIndexes < ActiveRecord::Migration
  include MigrationHelper

  disable_ddl_transaction!

  INDEXES = [
    [:cloud_networks, [:ems_id, :cloud_tenant_id, :orchestration_stack_id]],
    [:cloud_object_store_containers, [:ems_id, :cloud_tenant_id]],
    [:cloud_object_store_objects, [:ems_id, :cloud_tenant_id, :cloud_object_store_container_id]],
    [:cloud_resource_quotas, [:ems_id, :cloud_tenant_id]],
    [:cloud_subnets, [:ems_id, :availability_zone_id, :cloud_network_id]],
    [:cloud_tenants, [:ems_id]],
    [:cloud_tenants_vms, [:cloud_tenant_id, :vm_id]],
    [:cloud_volume_snapshots, [:ems_id, :cloud_volume_id, :cloud_tenant_id]],
    [:cloud_volumes, [:ems_id, :availability_zone_id, :cloud_volume_snapshot_id, :cloud_tenant_id]],
    [:conditions_miq_policies, [:miq_policy_id, :condition_id]],
    [:custom_buttons, [:applies_to_id]],
    [:customization_templates, [:pxe_image_type_id]],
    [:dialog_fields, [:dialog_group_id]],
    [:dialog_groups, [:dialog_tab_id]],
    [:dialog_tabs, [:dialog_id]],
    [:disks, [:backing_id]],
    [:ems_events, [:dest_ems_cluster_id, :availability_zone_id]],
    [:ext_management_systems, [:zone_id]],
    [:firewall_rules, [:source_security_group_id]],
    [:floating_ips, [:ems_id, :vm_id, :cloud_tenant_id]],
    [:hosts, [:ems_cluster_id]],
    [:iso_datastores, [:ems_id]],
    [:iso_images, [:iso_datastore_id, :pxe_image_type_id]],
    [:key_pairs_vms, [:authentication_id, :vm_id]],
    [:ldap_domains, [:ldap_domain_id]],
    [:ldap_managements, [:manager_id, :ldap_user_id]],
    [:log_files, [:file_depot_id]],
    [:metric_rollups_01, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_02, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_03, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_04, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_05, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_06, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_07, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_08, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_09, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_10, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_11, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metric_rollups_12, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_00, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_01, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_02, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_03, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_04, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_05, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_06, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_07, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_08, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_09, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_10, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_11, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_12, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_13, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_14, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_15, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_16, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_17, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_18, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_19, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_20, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_21, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_22, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:metrics_23, [:parent_host_id, :parent_ems_cluster_id, :parent_storage_id, :parent_ems_id, :time_profile_id]],
    [:miq_cim_associations, [:zone_id]],
    [:miq_cim_instances, [:vmdb_obj_id, :zone_id]],
    [:miq_databases, [:last_replication_id]],
    [:miq_proxies_product_updates, [:product_update_id, :miq_proxy_id]],
    [:miq_queue, [:target_id, :instance_id, :handler_id, :for_user_id]],
    [:miq_reports, [:user_id]],
    [:miq_request_tasks, [:miq_request_task_id]],
    [:miq_roles_features, [:miq_user_role_id, :miq_product_feature_id]],
    [:miq_servers, [:log_file_depot_id]],
    [:miq_servers_product_updates, [:product_update_id, :miq_server_id]],
    [:miq_widget_contents, [:miq_group_id]],
    [:miq_widget_shortcuts, [:miq_shortcut_id, :miq_widget_id]],
    [:orchestration_stacks, [:ems_id]],
    [:pictures, [:resource_id]],
    [:pxe_images, [:pxe_menu_id, :pxe_image_type_id]],
    [:pxe_menus, [:pxe_server_id]],
    [:resource_actions, [:dialog_id, :resource_id]],
    [:security_groups, [:ems_id, :cloud_network_id, :cloud_tenant_id, :orchestration_stack_id]],
    [:security_groups_vms, [:security_group_id, :vm_id]],
    [:service_resources, [:service_template_id, :resource_id, :service_id, :source_id]],
    [:service_templates, [:service_template_id, :evm_owner_id, :miq_group_id, :service_template_catalog_id]],
    [:services, [:service_template_id, :evm_owner_id, :miq_group_id, :service_id]],
    [:vmdb_database_metrics, [:vmdb_database_id]],
    [:vmdb_indexes, [:vmdb_table_id]],
    [:vmdb_tables, [:vmdb_database_id, :parent_id]],
    [:vms, [:ems_cluster_id, :cloud_network_id, :cloud_subnet_id, :cloud_tenant_id, :orchestration_stack_id]],
    [:windows_images, [:pxe_server_id, :pxe_image_type_id]],
    [:zones, [:log_file_depot_id]],
  ]

  def up
    INDEXES.each do |args|
      add_index(*args)
    end
  end

  def down
    INDEXES.each do |args|
      drop_index(*args)
    end
  end
end
