#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: "VIM Performance Daily"

# Menu name
name: "VIM Performance Daily"

rpt_type: middleware

# Main DB table report is based on
db: LiveMetric

# Columns to fetch from the main table
cols:
- timestamp
- mw_heap_used
- mw_heap_committed
- mw_heap_max
- mw_non_heap_used
- mw_non_heap_committed
- mw_accumulated_gc_duration
- mw_aggregated_active_web_sessions
- mw_aggregated_expired_web_sessions
- mw_aggregated_rejected_web_sessions
- mw_tx_committed
- mw_tx_timeout
- mw_tx_heuristics
- mw_tx_application_rollbacks
- mw_tx_aborted
- mw_tx_resource_rollbacks

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order:
- timestamp
- mw_heap_used
- mw_heap_committed
- mw_heap_max
- mw_non_heap_used
- mw_non_heap_committed
- mw_accumulated_gc_duration
- mw_aggregated_active_web_sessions
- mw_aggregated_expired_web_sessions
- mw_aggregated_rejected_web_sessions
- mw_tx_committed
- mw_tx_timeout
- mw_tx_heuristics
- mw_tx_application_rollbacks
- mw_tx_aborted
- mw_tx_resource_rollbacks

# Column titles, in order
headers:
- Date/Time
- Used
- Committed
- Maximum
- Used
- Committed
- Duration
- Active
- Expired
- Rejected
- Committed
- Timed-out
- Heuristic
- Application Failure
- Aborted
- Resource Failure

# Condition expression for search filtering
conditions: 

# Order string for the SQL query
order: ascending

# Columns to sort the report on, in order
sortby: timestamp

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph: 
  :type: Line
  :columns:
    - mw_heap_used
    - mw_heap_committed
    - mw_heap_max
    - mw_non_heap_used
    - mw_non_heap_committed
    - mw_accumulated_gc_duration
    - mw_aggregated_active_web_sessions
    - mw_aggregated_expired_web_sessions
    - mw_aggregated_rejected_web_sessions
    - mw_tx_committed
    - mw_tx_timeout
    - mw_tx_heuristics
    - mw_tx_application_rollbacks
    - mw_tx_aborted
    - mw_tx_resource_rollbacks

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims: 

template_type: report
