#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: "VIM Performance Hourly"

# Menu name
name: "VIM Performance Hourly"

rpt_type: middleware

# Main DB table report is based on
db: LiveMetric

# Columns to fetch from the main table
cols:
- timestamp
- mw_ds_available_count
- mw_ds_in_use_count
- mw_ds_timed_out
- mw_ds_average_get_time
- mw_ds_average_creation_time
- mw_ds_max_wait_time

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order:
- timestamp
- mw_ds_available_count
- mw_ds_in_use_count
- mw_ds_timed_out
- mw_ds_average_get_time
- mw_ds_average_creation_time
- mw_ds_max_wait_time

# Column titles, in order
headers:
- Date/Time
- Available
- In Use
- Time-out
- Get Time (avg)
- Creation Time (avg)
- Wait Time (max)

# Condition expression for search filtering
conditions: 

# Order string for the SQL query
order: ascending

# Columns to sort the report on, in order
sortby: timestamp

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph: 
  :type: Line
  :columns:
    - mw_ds_available_count
    - mw_ds_in_use_count
    - mw_ds_timed_out
    - mw_ds_average_get_time
    - mw_ds_average_creation_time
    - mw_ds_max_wait_time

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims: 

template_type: report
