#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: "VMDB Database Metrics"

# Menu name
name: "VMDB Database Metrics"

# Main DB table report is based on
db: VmdbDatabaseMetric

# Columns to fetch from the main table
cols:
- timestamp
- disk_total_bytes
- disk_free_bytes
- disk_used_bytes
- disk_total_inodes
- disk_free_inodes
- disk_used_inodes

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order: 
- timestamp
- disk_total_bytes
- disk_free_bytes
- disk_used_bytes
- disk_total_inodes
- disk_free_inodes
- disk_used_inodes

# Column titles, in order
headers:
- Date/Time
- Total
- Free
- Used
- Total
- Free
- Used

# Condition expression for search filtering
conditions: 

# Order string for the SQL query
order: ascending

# Columns to sort the report on, in order
sortby: timestamp

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph: 
  :type: Line
  :columns:
    - disk_total_bytes

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims: 

template_type: report
