#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: "VMDB Table Metrics"

# Menu name
name: "VMDB Table Metrics"

# Main DB table report is based on
db: VmdbMetric

# Columns to fetch from the main table
cols:
- timestamp
- size
- rows
- pages
- percent_bloat
- wasted_bytes
- rows_inserted
- rows_updated
- rows_deleted

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order: 
- timestamp
- size
- rows
- pages
- percent_bloat
- wasted_bytes
- rows_inserted
- rows_updated
- rows_deleted

# Column titles, in order
headers:
- Date/Time
- Size
- Rows
- Pages
- Percent Bloat
- Wasted
- Inserted
- Updated
- Deleted

# Condition expression for search filtering
conditions: 

# Order string for the SQL query
order: ascending

# Columns to sort the report on, in order
sortby: timestamp

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph: 
  :type: Line
  :columns:
    - size

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims: 

template_type: report
