#
# Toolbar config file
#
---
:model: ManageIQ::Providers::AnsibleTower::ConfigurationManager::ConfiguredSystem
:button_groups:
- :name: provider_foreman_policy
  :items:
  - :buttonSelect: provider_foreman_policy_choice
    :icon: fa fa-shield fa-lg
    :title: Policy
    :text: Policy
    :items:
    - :button: configured_system_tag
      :icon: pficon pficon-edit fa-lg
      :text: "Edit Tags"
      :title: "Edit Tags for this Configured System"
      :url: tagging
      :url_parms: 'main_div'
      :enabled: 'false'
      :onwhen: '1+'

