---
:name: miq_provision_configured_system_foreman_dialogs
:description: Sample Configuration Management Provisioning Dialog
:dialog_type: MiqProvisionConfiguredSystemWorkflow
:content:
  :buttons:
  - :submit
  - :cancel
  :dialogs:
    :requester:
      :description: Request
      :fields:
        :owner_phone:
          :description: Phone
          :required: false
          :display: :hide
          :data_type: :string
        :owner_country:
          :description: Country/Region
          :required: false
          :display: :hide
          :data_type: :string
        :owner_phone_mobile:
          :description: Mobile
          :required: false
          :display: :hide
          :data_type: :string
        :owner_title:
          :description: Title
          :required: false
          :display: :hide
          :data_type: :string
        :owner_first_name:
          :description: First Name
          :required: true
          :display: :edit
          :data_type: :string
        :owner_manager:
          :description: Name
          :required: false
          :display: :edit
          :data_type: :string
        :owner_address:
          :description: Address
          :required: false
          :display: :hide
          :data_type: :string
        :owner_company:
          :description: Company
          :required: false
          :display: :hide
          :data_type: :string
        :owner_last_name:
          :description: Last Name
          :required: true
          :display: :edit
          :data_type: :string
        :owner_manager_mail:
          :description: E-Mail
          :required: false
          :display: :hide
          :data_type: :string
        :owner_city:
          :description: City
          :required: false
          :display: :hide
          :data_type: :string
        :owner_department:
          :description: Department
          :required: false
          :display: :hide
          :data_type: :string
        :owner_load_ldap:
          :pressed:
            :method: :retrieve_ldap
          :description: Look Up LDAP Email
          :required: false
          :display: :show
          :data_type: :button
        :owner_manager_phone:
          :description: Phone
          :required: false
          :display: :hide
          :data_type: :string
        :owner_state:
          :description: State
          :required: false
          :display: :hide
          :data_type: :string
        :owner_office:
          :description: Office
          :required: false
          :display: :hide
          :data_type: :string
        :owner_zip:
          :description: Zip code
          :required: false
          :display: :hide
          :data_type: :string
        :owner_email:
          :description: E-Mail
          :required_method: :validate_regex
          :required_regex: !ruby/regexp /\A[\w!#$\%&'*+\/=?`\{|\}~^-]+(?:\.[\w!#$\%&'*+\/=?`\{|\}~^-]+)*@(?:[A-Z0-9-]+\.)+[A-Z]{2,6}\Z/i 
          :required: true
          :display: :edit
          :data_type: :string
        :request_notes:
          :description: Notes
          :required: false
          :display: :edit
          :data_type: :string
      :display: :show
      :field_order:
    :purpose:
      :description: Purpose
      :fields:
        :tag_ids:
          :required_method: :validate_tags
          :description: Tags
          :required: false
          :options:
            :include: []
            :order: []
            :single_select: []
            :exclude: []
          :display: :edit
          :required_tags: []
          :data_type: :integer
      :display: :show
      :field_order:
    :customize:
      :description: Customize
      :fields:
        :root_password:
          :description: Root Password
          :required: false
          :display: :edit
          :data_type: :string
          :notes: Minimum 8 characters or blank
        :hostname:
          :description: Host Name
          :required: false
          :display: :edit
          :data_type: :string
        :ip_addr:
          :description: IP Address
          :required: false
          :notes: (Enter starting IP address)
          :display: :edit
          :data_type: :string
          :notes_display: :hide
      :display: :show
    :service:
      :description: Catalog
      :fields:
        :src_configured_system_ids:
          :values_from:
            :method: :allowed_configured_systems
          :description: Configured Systems
          :required: true
          :notes:
          :display: :show
          :data_type: :integer
          :notes_display: :show
        :src_configuration_profile_id:
          :values_from:
            :method: :allowed_configuration_profiles
          :description: Configuration Profile
          :required: true
          :notes:
          :display: :edit
          :data_type: :integer
          :notes_display: :show
      :display: :show
    :schedule:
      :description: Schedule
      :fields:
        :schedule_type:
          :values:
            schedule: Schedule
            immediately: Immediately on Approval
          :description: When to Provision
          :required: false
          :display: :edit
          :default: immediately
          :data_type: :string
        :schedule_time:
          :values_from:
            :options:
              :offset: 1.day
            :method: :default_schedule_time
          :description: Provision on
          :required: false
          :display: :edit
          :data_type: :time
      :display: :show
  :dialog_order:
  - :requester
  - :purpose
  - :service
  - :customize
  - :schedule
