raise "Ruby versions less than 2.2.2 are unsupported!" if RUBY_VERSION < "2.2.2"

source 'https://rubygems.org'

# Unmodified gems
gem "actionpack",              "~> 5.0.0"
gem "activerecord",            "~> 5.0.0" # used by appliance_console
gem "activesupport",           "~> 5.0.0"
gem "addressable",             "~> 2.4",            :require => false
gem "awesome_spawn",           "~> 1.4",            :require => false
gem "azure-armrest",           "=0.5.2",            :require => false
gem "bcrypt",                  "~> 3.1.10",         :require => false
gem "binary_struct",           "~> 2.1",            :require => false
gem "bundler",                 ">= 1.8.4" # rails-assets requires bundler >= 1.8.4, see: https://rails-assets.org/
gem "bunny",                   "~>2.1.0",           :require => false
gem "excon",                   "~>0.40",            :require => false
gem "ezcrypto",                "=0.7",              :require => false
gem "ffi",                     "~>1.9.3",           :require => false
gem "ffi-vix_disk_lib",        "~>1.0.2",           :require => false  # used by lib/VixDiskLib
gem "fog-openstack",           "=0.1.19",           :require => false
gem "hawkular-client",         "=2.7.0",            :require => false
gem "httpclient",              "~>2.7.1",           :require => false
gem "image-inspector-client",  "~>1.0.3",           :require => false
gem "iniparse",                                     :require => false
gem "kubeclient",              "=2.3.0",            :require => false
gem "linux_admin",             "~>0.19.0",          :require => false
gem "log4r",                   "=1.1.8",            :require => false
gem "memoist",                 "~>0.14.0",          :require => false
gem "memory_buffer",           ">=0.1.0",           :require => false
gem "more_core_extensions",    "~>3.2",             :require => false
gem "net-scp",                 "~>1.2.1",           :require => false
gem "net-sftp",                "~>2.1.2",           :require => false
gem "nokogiri",                "~>1.6.8",           :require => false
gem "openscap",                "~>0.4.3",           :require => false
gem "ovirt",                   "~>0.14.0",          :require => false
gem "parallel",                "~>1.9",             :require => false # For OvirtInventory
gem "pg",                      "~>0.18.2",          :require => false
gem "pg-dsn_parser",           "~>0.1.0",           :require => false
gem "psych",                   "~>2.0.12"
gem "rake",                    "~>10.1"
gem "rbvmomi",                 "~>1.8.0",           :require => false
gem "rest-client",             "~>2.0.0",           :require => false
gem "rubyzip",                 "~>1.2.0",           :require => false
gem "rufus-lru",               "~>1.0.3",           :require => false
gem "sys-proctable",           "~>1.1.3",           :require => false
gem "sys-uname",               "~>1.0.1",           :require => false
gem "trollop",                 "~>2.0",             :require => false
gem "uuidtools",               "~>2.1.3",           :require => false
gem "winrm",                   "~>1.7.2",           :require => false
gem "winrm-elevated",          "~>0.4.0",           :require => false
gem "zip-zip",                 "~>0.3.0",           :require => false

# Modified gems (forked on github)
gem "handsoap", "~>0.2.5", :require => false, :git => "https://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-5"
gem "rubywbem",            :require => false, :git => "https://github.com/ManageIQ/rubywbem.git", :branch => "rubywbem_0_1_0"

group :appliance do
  gem "highline", "~> 1.6.21", :require => false  # Needed for the appliance_console
end

# Linux-only section
if RbConfig::CONFIG["host_os"].include?("linux")
  gem "linux_block_device", ">=0.1.0", :require => false

  if RbConfig::CONFIG["host_cpu"] == "x86"  # 32 bit Linux.
    gem "large_file_linux", "~>0.1.0", :require => false
  end
end

# Windows only. Do not put in Gemfile.lock on other platforms.
if Gem.win_platform?
  gem "win32-process", "~>0.8.0", :require => false, :platforms => [:mswin, :mingw]
end

### Start of gems excluded from the appliances.
# The gems listed below do not need to be packaged until we find it necessary or useful.
# Only add gems here that we do not need on an appliance.
#
unless ENV['APPLIANCE']
  group :test do
    gem "camcorder",                    :require => false
    gem "coveralls",                    :require => false
    gem "rspec",         "~>3.5.0",     :require => false
    gem "test-unit",                    :require => false
    gem "timecop",       "~>0.7.3",     :require => false
    gem "vcr",           "~>3.0.0",     :require => false
    gem "webmock",       "~>1.12",      :require => false
    gem "xml-simple",    "~>1.1.0",     :require => false  # Used by test/xml/tc_xmlhash_methods.rb
  end
end
