raise "Ruby versions less than 2.0 are unsupported!" if RUBY_VERSION < "2.0.0"

source 'https://rubygems.org'

# rails-assets requires bundler >= 1.8.4, see: https://rails-assets.org/
gem "bundler",       ">= 1.8.4"
gem "rake",          "~>10.1"
gem "iniparse"

gem "activesupport",           "~>4.2.3"

# ActiveRecord is used by appliance_console
gem "activerecord",            "~>4.2.3"

# Not locally modified and not required
gem "awesome_spawn",           "~> 1.3",            :require => false
gem "binary_struct",           "~> 2.0",            :require => false
gem "excon",                   "~>0.40",            :require => false
gem "ezcrypto",                "=0.7",              :require => false
gem "facade",                  "~>1.0.5",           :require => false  # Used by util/pathname2.rb
gem "ffi",                     "~>1.9.3",           :require => false
gem "ffi-vix_disk_lib",        "~>1.0.1",           :require => false  # used by lib/VixDiskLib
gem "fog",                     "~>1.33.0",          :require => false
gem "fog-core",                "!=1.31.1",          :require => false
gem "httpclient",              "~>2.5.3",           :require => false
gem "kubeclient",              "=0.1.17",           :require => false
gem "linux_admin",             "~>0.11.0",          :require => false
gem "log4r",                   "=1.1.8",            :require => false
gem "memoist",                 "~>0.11.0",          :require => false
gem "memory_buffer",           ">=0.1.0",           :require => false
gem "more_core_extensions",    "~>1.2.0",           :require => false
gem "net-sftp",                "~>2.1.2",           :require => false
gem "nokogiri",                "~>1.6.0",           :require => false
gem "openshift_client",        "=0.0.8",            :require => false
gem "ovirt",                   "~>0.6.0",           :require => false
gem "parallel",                "~>0.5.21",          :require => false
gem "psych",                   "~>2.0.12"
gem "rest-client",                                  :require => false, :git => "git://github.com/rest-client/rest-client.git", :ref => "08480eb86aef1e"
gem "rubyzip",                 "=0.9.5",            :require => false  # TODO: Review 0.9.7 breaking log collection in FB14646
gem "rufus-lru",               "~>1.0.3",           :require => false
gem "sys-uname",               "~>1.0.1",           :require => false
gem "trollop",                 "~>2.0",             :require => false
gem "uuidtools",               "~>2.1.3",           :require => false

if RbConfig::CONFIG["host_os"].include?("darwin") # This is only used on Mac
  gem 'sys-proctable',  "~> 0.9",      :require => false
end

# Linux-only section
if RbConfig::CONFIG["host_os"].include?("linux")
  gem "linux_block_device", ">=0.1.0", :require => false

  if RbConfig::CONFIG["host_cpu"] == "x86"  # 32 bit Linux.
    gem "large_file_linux", "~>0.1.0", :require => false
  end
end

# qpid group is needed to gate the inclusion of qpid_messaging gem on platforms
# where the qpid-cpp-client-devel package is not available.  This includes
# OSX, Windows, and CruiseControl machines.
group :qpid do
  gem "qpid_messaging", "~>0.20.0", :require => false
end

# Grouping this mainly to stay consistent with qpid--the other amqp library.  In
# a production build, the qpid and rabbit groups should be included
group :rabbit do
  gem "bunny", "~>1.0.4", :require => false
end

group :appliance do
  gem "highline", "~> 1.6.21", :require => false  # Needed for the appliance_console
  #gem "minitest", "<  5",      :require => false  # HACK to run test suite on SCL ruby
  gem "rdoc",                  :require => false  # HACK to run test suite on SCL ruby
end

# Locally modified but not required
gem "handsoap", "~>0.2.5", :require => false, :git => "git://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-2"
gem "rubywbem",            :require => false, :git => "git://github.com/ManageIQ/rubywbem.git", :branch => "rubywbem_0_1_0"

# Windows only. Do not put in Gemfile.lock on other platforms.
if Gem.win_platform?
  gem "win32-process", "~>0.8.0", :require => false, :platforms => [:mswin, :mingw]
end

### Start of gems excluded from the appliances.
# The gems listed below do not need to be packaged until we find it necessary or useful.
# Only add gems here that we do not need on an appliance.
#
unless ENV['APPLIANCE']
  group :test do
    gem "test-unit",                    :require => false
    gem "camcorder",                    :require => false
    gem "jasmine",                      :require => false, :git => "git://github.com/jasmine/jasmine-gem.git", :ref => "c726fe1"
    gem "rspec",         "~>2.14.0",    :require => false
    gem "rspec-fire",    "~>1.3.0",     :require => false
    gem "timecop",       "~>0.7.3",     :require => false
    gem "xml-simple",    "=1.0.12",     :require => false  # Used by test/xml/tc_xmlhash_methods.rb
  end
end
