raise "Ruby versions less than 2.2.2 are unsupported!" if RUBY_VERSION < "2.2.2"

source 'https://rubygems.org'

# rails-assets requires bundler >= 1.8.4, see: https://rails-assets.org/
gem "bundler",       ">= 1.8.4"
gem "rake",          "~>10.1"
gem "iniparse"

gem "activesupport",           "~> 5.0.0"
gem "actionpack",              "~> 5.0.0"

# ActiveRecord is used by appliance_console
gem "activerecord",            "~> 5.0.0"

# Not locally modified and not required
gem "addressable",             "~> 2.4",            :require => false
gem "awesome_spawn",           "~> 1.3",            :require => false
gem "azure-armrest",           "=0.2.10",           :require => false
gem "bcrypt",                  "~> 3.1.10",         :require => false
gem "binary_struct",           "~> 2.1",            :require => false
gem "excon",                   "~>0.40",            :require => false
gem "ezcrypto",                "=0.7",              :require => false
gem "ffi",                     "~>1.9.3",           :require => false
gem "ffi-vix_disk_lib",        "~>1.0.2",           :require => false  # used by lib/VixDiskLib
gem "fog-openstack",           "=0.1.11",           :require => false
gem "httpclient",              "~>2.7.1",           :require => false
gem "image-inspector-client",  "~>1.0.3",           :require => false
gem "kubeclient",              "=1.2.0",            :require => false
gem "hawkular-client",         "=0.2.2",            :require => false
gem "linux_admin",             "~>0.19.0",          :require => false
gem "log4r",                   "=1.1.8",            :require => false
gem "memoist",                 "~>0.14.0",          :require => false
gem "memory_buffer",           ">=0.1.0",           :require => false
gem "more_core_extensions",    "~>3.0.0",           :require => false
gem "net-sftp",                "~>2.1.2",           :require => false
gem "net-scp",                 "~>1.2.1",           :require => false
gem "nokogiri",                "~>1.6.0",           :require => false
gem "openshift_client",        "=1.2.0",            :require => false
gem "openscap",                "~>0.4.3",           :require => false
gem "ovirt",                   "~>0.12.1",          :require => false
gem "pg",                      "~>0.18.2",          :require => false
gem "psych",                   "~>2.0.12"
gem "rest-client",             "~>2.0.0",           :require => false
gem "rubyzip",                 "~>1.2.0",           :require => false
gem "zip-zip",                 "~>0.3.0",           :require => false
gem "rufus-lru",               "~>1.0.3",           :require => false
gem "sys-uname",               "~>1.0.1",           :require => false
gem "trollop",                 "~>2.0",             :require => false
gem "uuidtools",               "~>2.1.3",           :require => false
gem "winrm",                   "~>1.7.2",           :require => false
gem "winrm-elevated",          "~>0.3.0",           :require => false
gem 'sys-proctable',           "~> 1.0",            :require => false

# Linux-only section
if RbConfig::CONFIG["host_os"].include?("linux")
  gem "linux_block_device", ">=0.1.0", :require => false

  if RbConfig::CONFIG["host_cpu"] == "x86"  # 32 bit Linux.
    gem "large_file_linux", "~>0.1.0", :require => false
  end
end

gem "bunny", "~>2.1.0", :require => false

group :appliance do
  gem "highline", "~> 1.6.21", :require => false  # Needed for the appliance_console
  #gem "minitest", "<  5",      :require => false  # HACK to run test suite on SCL ruby
  gem "rdoc",                  :require => false  # HACK to run test suite on SCL ruby
end

# Locally modified but not required
gem "handsoap", "~>0.2.5", :require => false, :git => "git://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-3"
gem "rubywbem",            :require => false, :git => "git://github.com/ManageIQ/rubywbem.git", :branch => "rubywbem_0_1_0"

# Windows only. Do not put in Gemfile.lock on other platforms.
if Gem.win_platform?
  gem "win32-process", "~>0.8.0", :require => false, :platforms => [:mswin, :mingw]
end

### Start of gems excluded from the appliances.
# The gems listed below do not need to be packaged until we find it necessary or useful.
# Only add gems here that we do not need on an appliance.
#
unless ENV['APPLIANCE']
  group :test do
    gem "coveralls",                    :require => false
    gem "test-unit",                    :require => false
    gem "camcorder",                    :require => false
    gem "jasmine",       "~>2.4.0",     :require => false
    gem "phantomjs",     "=1.9.8.0",    :require => false
    gem "rspec",         "~>3.5.0",     :require => false
    gem "timecop",       "~>0.7.3",     :require => false
    gem "vcr",           "~>2.6",       :require => false
    gem "webmock",       "~>1.12",      :require => false
    gem "xml-simple",    "~>1.1.0",     :require => false  # Used by test/xml/tc_xmlhash_methods.rb
  end
end
