require_relative './bundler_setup'

Dir[File.join(GEMS_PENDING_ROOT, "lib/tasks/**/*.rake")].sort.each { |ext| load ext }

task :default do
  Rake::Task["spec"].invoke
  Rake::Task["test"].invoke
  if ENV["TRAVIS"]
    require 'coveralls/rake/task'
    Coveralls::RakeTask.new
    Rake::Task["coveralls:push"].invoke
  end
end
