require_relative './bundler_setup'

begin
  require 'coveralls/rake/task'
rescue LoadError
else
  Coveralls::RakeTask.new
end

Dir[File.join(GEMS_PENDING_ROOT, "lib/tasks/**/*.rake")].sort.each { |ext| load ext }

task :default => [:spec, :test, 'coveralls:push']
