#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: Applications

# Menu name
name: Applications

# Main DB table report is based on
db: GuestApplication

# Columns to fetch from the main table
cols:
- name
- vendor
- version
- release
- description
- package_name
- product_icon
- transform
- language
- typename
- product_key
- path
- arch

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order: 
- name
- vendor
- version
- release
- description
- package_name
- product_key
- path
- arch

# Column titles, in order
headers:
- Name
- Vendor
- Version
- Release
- Description
- Package Name
- Product Key
- Path
- Architecture

# Condition(s) string for the SQL query
conditions: 

# Order string for the SQL query
order: Ascending

# Columns to sort the report on, in order
sortby:
- name

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph: 

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims: 
