#
# This is an MIQ Report configuration file
#   Single value parameters are specified as:
#     single_value_parm: value
#   Multiple value parameters are specified as:
#     multi_value_parm:
#       - value 1
#       - value 2
#

# Report title
title: Ansible Tower Job Templates

# Menu name
name: Job Templates

# Main DB table report is based on
db: ManageIQ::Providers::AnsibleTower::ConfigurationManager::ConfigurationScript

# Columns to fetch from the main table
cols:
- name
- type
- description
- created_at
- updated_at

# Included tables (joined, has_one, has_many) and columns
include:

# Order of columns (from all tables)
col_order:
- name
- type
- description
- created_at
- updated_at

# Column titles, in order
headers:
- Nname
- Type
- Description
- Created On
- Updated On


col_formats:
-
- :model_name
-
-

# Condition(s) string for the SQL query
conditions:

# Order string for the SQL query
order: Ascending

# Columns to sort the report on, in order
sortby:
- hostname

# Group rows (y=yes,n=no,c=count)
group: n

# Graph type
#   Bar
#   Column
#   ColumnThreed
#   ParallelThreedColumn
#   Pie
#   PieThreed
#   StackedBar
#   StackedColumn
#   StackedThreedColumn

graph:

# Dimensions of graph (1 or 2)
#   Note: specifying 2 for a single dimension graph may not return expected results
dims:
