source 'https://rubygems.org'

gem "rack"
gem "faraday"
gem "faraday_middleware"
gem "trollop"
gem "activesupport"
gem "more_core_extensions"

group :test do
  gem "rspec",      "~>2.12.0", :require => false
end
