class ApplicationHelper::Toolbar::VmCloudsCenter < ApplicationHelper::Toolbar::Basic
  button_group('instance_vmdb', [
    {
      :buttonSelect => "instance_vmdb_choice",
      :icon         => "fa fa-cog fa-lg",
      :title        => N_("Configuration"),
      :text         => N_("Configuration"),
      :enabled      => "false",
      :onwhen       => "1+",
      :items => [
        {
          :button       => "instance_refresh",
          :icon         => "fa fa-refresh fa-lg",
          :text         => N_("Refresh Relationships and Power States"),
          :title        => N_("Refresh relationships and power states for all items related to the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Refresh relationships and power states for all items related to the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_scan",
          :icon         => "fa fa-search fa-lg",
          :text         => N_("Perform SmartState Analysis"),
          :title        => N_("Perform SmartState Analysis on the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Perform SmartState Analysis on the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_compare",
          :icon         => "product product-compare fa-lg",
          :text         => N_("Compare Selected items"),
          :title        => N_("Select two or more items to compare"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "2+",
        },
        {
          :separator    => nil,
        },
        {
          :button       => "instance_edit",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Edit Selected item"),
          :title        => N_("Select a single item to edit"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1",
        },
        {
          :button       => "instance_ownership",
          :icon         => "pficon pficon-user fa-lg",
          :text         => N_("Set Ownership"),
          :title        => N_("Set Ownership for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_delete",
          :icon         => "pficon pficon-delete fa-lg",
          :text         => N_("Remove selected items from the VMDB"),
          :title        => N_("Remove selected items from the VMDB"),
          :url_parms    => "main_div",
          :confirm      => N_("Warning: The selected items and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :separator    => nil,
        },
      ]
    },
  ])
  button_group('instance_policy', [
    {
      :buttonSelect => "instance_policy_choice",
      :icon         => "fa fa-shield fa-lg",
      :title        => N_("Policy"),
      :text         => N_("Policy"),
      :enabled      => "false",
      :onwhen       => "1+",
      :items => [
        {
          :button       => "instance_protect",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Manage Policies"),
          :title        => N_("Manage Policies for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_policy_sim",
          :icon         => "fa fa-play-circle-o fa-lg",
          :text         => N_("Policy Simulation"),
          :title        => N_("View Policy Simulation for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_tag",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Edit Tags"),
          :title        => N_("Edit tags for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_check_compliance",
          :icon         => "fa fa-search fa-lg",
          :text         => N_("Check Compliance of Last Known Configuration"),
          :title        => N_("Check Compliance of the last known configuration for the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Initiate Check Compliance of the last known configuration for the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
  button_group('instance_lifecycle', [
    {
      :buttonSelect => "instance_lifecycle_choice",
      :icon         => "fa fa-recycle fa-lg",
      :title        => N_("Lifecycle"),
      :text         => N_("Lifecycle"),
      :items => [
        {
          :button       => "instance_miq_request_new",
          :icon         => "pficon pficon-add-circle-o fa-lg",
          :url_parms    => "main_div",
          :text         => N_("Provision Instances"),
          :title        => N_("Request to Provision Instances"),
        },
        {
          :button       => "instance_retire",
          :icon         => "fa fa-clock-o fa-lg",
          :text         => N_("Set Retirement Dates"),
          :title        => N_("Set Retirement Dates for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_retire_now",
          :icon         => "fa fa-clock-o fa-lg",
          :text         => N_("Retire selected items"),
          :title        => N_("Retire the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Retire the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
  button_group('instance_operations', [
    {
      :buttonSelect => "instance_power_choice",
      :icon         => "fa fa-power-off fa-lg",
      :title        => N_("Power Operations"),
      :text         => N_("Power"),
      :enabled      => "false",
      :onwhen       => "1+",
      :items => [
        {
          :button       => "instance_stop",
          :image        => "guest_shutdown",
          :text         => N_("Stop"),
          :title        => N_("Stop the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Stop the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_start",
          :image        => "power_on",
          :text         => N_("Start"),
          :title        => N_("Start the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Start the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_pause",
          :image        => "power_pause",
          :text         => N_("Pause"),
          :title        => N_("Pause the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Pause the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_suspend",
          :image        => "suspend",
          :text         => N_("Suspend"),
          :title        => N_("Suspend the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Suspend the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_shelve",
          :image        => "power_shelve",
          :text         => N_("Shelve"),
          :title        => N_("Shelve the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Shelve the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_shelve_offload",
          :image        => "power_shelve_offload",
          :text         => N_("Shelve Offload"),
          :title        => N_("Shelve Offload the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Shelve Offload the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_resume",
          :image        => "power_resume",
          :text         => N_("Resume"),
          :title        => N_("Resume the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Resume the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :separator    => nil,
        },
        {
          :button       => "instance_guest_restart",
          :image        => "power_reset",
          :text         => N_("Soft Reboot"),
          :title        => N_("Soft Reboot the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Soft Reboot the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_reset",
          :image        => "guest_restart",
          :text         => N_("Hard Reboot"),
          :title        => N_("Hard Reboot the Guest OS on the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Hard Reboot the Guest OS on the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "instance_terminate",
          :image        => "power_off",
          :text         => N_("Terminate"),
          :title        => N_("Terminate the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Terminate the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
end
