class ApplicationHelper::Toolbar::VmInfrasCenter < ApplicationHelper::Toolbar::Basic
  button_group('vm_vmdb', [
    {
      :buttonSelect => "vm_vmdb_choice",
      :icon         => "fa fa-cog fa-lg",
      :title        => N_("Configuration"),
      :text         => N_("Configuration"),
      :enabled      => "false",
      :onwhen       => "1+",
      :items => [
        {
          :button       => "vm_refresh",
          :icon         => "fa fa-refresh fa-lg",
          :text         => N_("Refresh Relationships and Power States"),
          :title        => N_("Refresh relationships and power states for all items related to the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Refresh relationships and power states for all items related to the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_scan",
          :icon         => "fa fa-search fa-lg",
          :text         => N_("Perform SmartState Analysis"),
          :title        => N_("Perform SmartState Analysis on the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Perform SmartState Analysis on the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_collect_running_processes",
          :icon         => "fa fa-eyedropper fa-lg",
          :text         => N_("Extract Running Processes"),
          :title        => N_("Extract Running Processes for the selected items"),
          :confirm      => N_("Extract Running Processes for the selected items?"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_compare",
          :icon         => "product product-compare fa-lg",
          :text         => N_("Compare Selected items"),
          :title        => N_("Select two or more items to compare"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "2+",
        },
        {
          :separator    => nil,
        },
        {
          :button       => "vm_edit",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Edit Selected item"),
          :title        => N_("Select a single item to edit"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1",
        },
        {
          :button       => "vm_ownership",
          :icon         => "pficon pficon-user fa-lg",
          :text         => N_("Set Ownership"),
          :title        => N_("Set Ownership for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_delete",
          :icon         => "pficon pficon-delete fa-lg",
          :text         => N_("Remove selected items from the VMDB"),
          :title        => N_("Remove selected items from the VMDB"),
          :url_parms    => "main_div",
          :confirm      => N_("Warning: The selected items and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :separator    => nil,
        },
        {
          :button       => "vm_right_size",
          :icon         => "product product-custom-6 fa-lg",
          :text         => N_("Right-Size Recommendations"),
          :title        => N_("CPU/Memory Recommendations of selected item"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1",
        },
        {
          :button       => "vm_reconfigure",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Reconfigure Selected items"),
          :title        => N_("Reconfigure the Memory/CPUs of selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
  button_group('vm_policy', [
    {
      :buttonSelect => "vm_policy_choice",
      :icon         => "fa fa-shield fa-lg",
      :title        => N_("Policy"),
      :text         => N_("Policy"),
      :enabled      => "false",
      :onwhen       => "1+",
      :items => [
        {
          :button       => "vm_protect",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Manage Policies"),
          :title        => N_("Manage Policies for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_policy_sim",
          :icon         => "fa fa-play-circle-o fa-lg",
          :text         => N_("Policy Simulation"),
          :title        => N_("View Policy Simulation for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_tag",
          :icon         => "pficon pficon-edit fa-lg",
          :text         => N_("Edit Tags"),
          :title        => N_("Edit tags for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_check_compliance",
          :icon         => "fa fa-search fa-lg",
          :text         => N_("Check Compliance of Last Known Configuration"),
          :title        => N_("Check Compliance of the last known configuration for the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Initiate Check Compliance of the last known configuration for the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
  button_group('vm_lifecycle', [
    {
      :buttonSelect => "vm_lifecycle_choice",
      :icon         => "fa fa-recycle fa-lg",
      :title        => N_("Lifecycle"),
      :text         => N_("Lifecycle"),
      :items => [
        {
          :button       => "vm_miq_request_new",
          :icon         => "pficon pficon-add-circle-o fa-lg",
          :url_parms    => "main_div",
          :text         => N_("Provision VMs"),
          :title        => N_("Request to Provision VMs"),
        },
        {
          :button       => "vm_clone",
          :icon         => "product product-clone fa-lg",
          :text         => N_("Clone selected item"),
          :title        => N_("Clone this item"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1",
        },
        {
          :button       => "vm_publish",
          :icon         => "pficon pficon-export",
          :text         => N_("Publish selected VM to a Template"),
          :title        => N_("Publish selected VM to a Template"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1",
        },
        {
          :button       => "vm_migrate",
          :icon         => "product product-migrate fa-lg",
          :text         => N_("Migrate selected items"),
          :title        => N_("Migrate selected items to another Host/Datastore"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_retire",
          :icon         => "fa fa-clock-o fa-lg",
          :text         => N_("Set Retirement Dates"),
          :title        => N_("Set Retirement Dates for the selected items"),
          :url_parms    => "main_div",
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_retire_now",
          :icon         => "fa fa-clock-o fa-lg",
          :text         => N_("Retire selected items"),
          :title        => N_("Retire the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Retire the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
  button_group('vm_operations', [
    {
      :buttonSelect => "vm_power_choice",
      :icon         => "fa fa-power-off fa-lg",
      :title        => N_("Power Operations"),
      :text         => N_("Power"),
      :enabled      => "false",
      :onwhen       => "1+",
      :items => [
        {
          :button       => "vm_guest_shutdown",
          :image        => "guest_shutdown",
          :text         => N_("Shutdown Guest"),
          :title        => N_("Shutdown the Guest OS on the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Shutdown the Guest OS on the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_guest_restart",
          :image        => "guest_restart",
          :text         => N_("Restart Guest"),
          :title        => N_("Restart the Guest OS on the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Restart the Guest OS on the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :separator    => nil,
        },
        {
          :button       => "vm_start",
          :image        => "power_on",
          :text         => N_("Power On"),
          :title        => N_("Power On the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Power On the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_stop",
          :image        => "power_off",
          :text         => N_("Power Off"),
          :title        => N_("Power Off the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Power Off the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_suspend",
          :image        => "power_suspend",
          :text         => N_("Suspend"),
          :title        => N_("Suspend the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Suspend the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
        {
          :button       => "vm_reset",
          :image        => "power_reset",
          :text         => N_("Reset"),
          :title        => N_("Reset the selected items"),
          :url_parms    => "main_div",
          :confirm      => N_("Reset the selected items?"),
          :enabled      => "false",
          :onwhen       => "1+",
        },
      ]
    },
  ])
end
