require 'active_metrics/connection_adapters/elasticsearch_adapter'
require 'active_metrics/connection_adapters/hawkular_metrics_adapter'
require 'active_metrics/connection_adapters/influxdb_adapter'
require 'active_metrics/base'
