source 'https://rubygems.org'

gem "bundler", "~>1.3"
gem "rake",    "~>10.1"

# NOTE: Must use fully qualified paths here so that when vmdb/Gemfile pulls in
#       this file, the directories resolve correctly.

# Locally modified and required
gem "activesupport", "=3.2.17", :git => "git://github.com/ManageIQ/rails.git", :tag => "vendored-3.2.17-7"

# ActiveRecord is used by appliance_console
gem "activerecord",  "=3.2.17", :git => "git://github.com/ManageIQ/rails.git", :tag => "vendored-3.2.17-7"

# Not locally modified and not required
gem "awesome_spawn",        "~> 1.2",    :require => false
gem "binary_struct",        "~> 2.0",    :require => false
gem "excon",                "~>0.31.0",  :require => false
gem "ezcrypto",             "=0.7",      :require => false
gem "facade",               "~>1.0.5",   :require => false  # Used by util/pathname2.rb
gem "ffi",                  "~>1.9.3",   :require => false
gem "fog",                  "~>1.19.0",  :require => false, :git => "git://github.com/ManageIQ/fog.git", :tag => "v1.19.0-1"
gem "httpclient",           "~>2.2.4",   :require => false
gem "io-extra",             "=1.2.6",    :require => false
gem "linux_admin",          "~>0.9",     :require => false
gem "log4r",                "=1.1.8",    :require => false
gem "more_core_extensions", "~>1.2.0",   :require => false
gem "nokogiri",             "~>1.5.0",   :require => false
gem "parallel",             "~>0.5.21",  :require => false
gem "Platform",             "=0.4.0",    :require => false
gem "rubyzip",              "=0.9.5",    :require => false  # TODO: Review 0.9.7 breaking log collection in FB14646
gem "rufus-lru",            "~>1.0.3",   :require => false
gem "uuidtools",            "~>2.1.3",   :require => false
gem "sass",                 "3.1.20",    :require => false
gem "trollop",              "~>1.16.2",  :require => false

# qpid group is needed to gate the inclusion of qpid_messaging gem on platforms
# where the qpid-cpp-client-devel package is not available.  This includes
# OSX, Windows, and CruiseControl machines.
group :qpid do
  gem "qpid_messaging", "~>0.20.0",    :require => false
end

# Grouping this mainly to stay consistent with qpid--the other amqp library.  In
# a production build, the qpid and rabbit groups should be included
group :rabbit do
  gem "bunny",          "~>1.0.4",    :require => false
end

group :appliance do
  gem "highline", "~> 1.6.21", :require => false  # Needed for the appliance_console
  gem "minitest", "<  5",      :require => false  # HACK to run test suite on SCL ruby
  gem "rdoc",                  :require => false  # HACK to run test suite on SCL ruby
end

# Locally modified but not required
gem "handsoap",    "~>0.2.5",   :require => false, :git => "git://github.com/ManageIQ/handsoap.git", :tag => "v0.2.5-2"
gem "rest-client", "~>1.6.7",   :require => false, :git => "git://github.com/ManageIQ/rest-client.git", :tag => "v1.6.7-5"
gem "rubywbem",    "=0.1.0",    :require => false, :git => "git://github.com/ManageIQ/rubywbem.git", :tag => "v0.1.0-2"

### Start of gems excluded from the appliances.
# The gems listed below do not need to be packaged until we find it necessary or useful.
# Only add gems here that we do not need on an appliance.
#
unless ENV['APPLIANCE']
  group :test do
    gem "camcorder",              :require => false
    gem "rspec",      "~>2.14.0", :require => false
    gem "rspec-fire", "~>1.3.0",  :require => false
    gem "timecop",    "~>0.5.3",  :require => false
    gem "xml-simple", "=1.0.12",  :require => false  # Used by test/xml/tc_xmlhash_methods.rb
  end
end
