# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative './bundler_setup'

require 'rake'
require 'rake/testtask'
require 'rdoc/task'

LIB_ROOT = File.expand_path(File.dirname(__FILE__))
Dir["#{LIB_ROOT}/lib/tasks/**/*.rake"].sort.each { |ext| load ext }

task :default => [:test]