# Feed metadata
roles: "cfme_administrators"
feed_title: "SmartProxy Changes - Settings"
feed_description: "Hosts with recent SmartProxy settings changes"
feed_link: "/alert/rss?feed=smartproxy_settings_changes"

# Item metadata
item_title: "#{rec.name}, hostname: #{rec.hostname}, running #{rec.vmm_vendor} VMM"
item_description: "(#{rec.created_on}) #{rec.message}, User: #{rec.userid}, Status: #{rec.status}"
item_link: "/host/show/#{rec.target_id}"
item_class: Host

# Search criteria
#   search_method: find, nil or a custom method name
#   Custom method is called the following way:
#     <item_class>.method(<search_method>).<name>, <options>)
#   A nil value or a value of "find" use the default class find method
search_method: rss_settings_changes
limit_to_time: 
limit_to_count: 
orderby: "created_on DESC"

# tags_include: any or all
tag_ns: "/managed/lifecycles"
tags_include: 
tags: SmartProxy
    
