---
http_interactions:
- request:
    method: get
    uri: https://yzamir-centos7-1.example.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0.rc1 (linux-gnu x86_64) ruby/2.2.5p319
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer TheToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '136'
      Date:
      - Mon, 11 Jul 2016 11:29:38 GMT
      Set-Cookie:
      - OPENSHIFT_REENCRYPT_openshift-infra_hawkular-metrics_SERVERID=6d1f3acb19e25d1ab5f5b24a75c0fa5d;
        path=/; HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.17.0-SNAPSHOT","Built-From-Git-SHA1":"56ede2a1bf69da749b4e7092b4b8ed7a399e8f2f"}'
    http_version:
  recorded_at: Mon, 11 Jul 2016 11:29:38 GMT
recorded_with: VCR 2.9.3
