# agent: Runtime settings for remote agent (MIQHost)
# policy: Policy rules for hosts and virtual machines
#
---
host:
  autoscan: false
  inherit_mgt_tags: false
  scan_frequency: 0
policy:
  autoscan: false
  autosmart: true
  inherit_mgt_tags: true
  start_smart_service: true
  start_smart_vm: true
