# Strings extracted from toolbar yamls for gettext to find
_("Add Host Analysis Profile")
_("Add Project to this Tenant")
_("Add VM Analysis Profile")
_("Add a New #{@sb[:folder].upcase == "VM" ? "VM" : ui_lookup(:model=>@sb[:folder])} Condition")
_("Add a New #{ui_lookup(:model=>@sb[:folder])} Alert Profile")
_("Add a New #{ui_lookup(:model=>@sb[:nodeid])} #{@sb[:mode].capitalize} Policy")
_("Add a New #{ui_lookup(:table=>"container")}")
_("Add a New #{ui_lookup(:table=>"container_group")}")
_("Add a New #{ui_lookup(:table=>"container_image_registry")}")
_("Add a New #{ui_lookup(:table=>"container_node")}")
_("Add a New #{ui_lookup(:table=>"container_project")}")
_("Add a New #{ui_lookup(:table=>"container_replicator")}")
_("Add a New #{ui_lookup(:table=>"container_service")}")
_("Add a New #{ui_lookup(:table=>"ems_cloud")}")
_("Add a New #{ui_lookup(:table=>"ems_container")}")
_("Add a New #{ui_lookup(:table=>"ems_infra")}")
_("Add a New Alert")
_("Add a New Catalog Bundle")
_("Add a New Catalog Item")
_("Add a New Catalog")
_("Add a New Class")
_("Add a New Customization Template")
_("Add a New Domain")
_("Add a New ISO Datastore")
_("Add a New Instance")
_("Add a New Method")
_("Add a New Namespace")
_("Add a New PXE Server")
_("Add a New Policy Profile")
_("Add a New Storage Manager")
_("Add a New item")
_("Add a new Action")
_("Add a new Box to this Tab")
_("Add a new Button Group")
_("Add a new Button")
_("Add a new Chargeback Rate")
_("Add a new Dashboard")
_("Add a new Dialog")
_("Add a new Element to this Box")
_("Add a new Group")
_("Add a new Host Analysis Profile")
_("Add a new LDAP Domain")
_("Add a new LDAP Region")
_("Add a new Provider")
_("Add a new Report")
_("Add a new Repository")
_("Add a new Role")
_("Add a new Schedule")
_("Add a new System Image Type")
_("Add a new Tab to this Dialog")
_("Add a new Time Profile")
_("Add a new User")
_("Add a new VM Analysis Profile")
_("Add a new Widget")
_("Add a new Zone")
_("Add child Tenant to this Tenant")
_("Add")
_("All attributes")
_("Analyze then Check Compliance for the selected items")
_("Analyze then Check Compliance for the selected items?")
_("Analyze then Check Compliance for this item")
_("Analyze then Check Compliance for this item?")
_("Analyze then Check Compliance")
_("Approve this Request")
_("Are you sure you want initiate content generation for this Widget now?")
_("Are you sure you want to copy this Alert?")
_("Are you sure you want to create Policy [#{truncate("Copy of #{@policy.description}", :length => 255, :omission => "")}] from this Policy?")
_("Are you sure you want to delete this #{ui_lookup(:model=>@condition.towhat)} Condition?")
_("Are you sure you want to delete this #{ui_lookup(:model=>@policy.towhat)} Policy?")
_("Are you sure you want to delete this Action?")
_("Are you sure you want to delete this Alert Profile?")
_("Are you sure you want to delete this Alert?")
_("Are you sure you want to delete this Group?")
_("Are you sure you want to delete this LDAP Domain?")
_("Are you sure you want to delete this LDAP Region?")
_("Are you sure you want to delete this Request?")
_("Are you sure you want to delete this Role?")
_("Are you sure you want to delete this User?")
_("Are you sure you want to delete this Zone?")
_("Are you sure you want to delete this item and all of it's children?")
_("Are you sure you want to remove selected Items?")
_("Are you sure you want to remove the selected Domains?")
_("Are you sure you want to remove the selected Instances?")
_("Are you sure you want to remove the selected Methods?")
_("Are you sure you want to remove the selected Namespaces?")
_("Are you sure you want to remove this Class?")
_("Are you sure you want to remove this Condition from Policy [#{@condition_policy.description}]?")
_("Are you sure you want to remove this Domain?")
_("Are you sure you want to remove this Instance?")
_("Are you sure you want to remove this Method?")
_("Are you sure you want to remove this Namespace?")
_("Are you sure you want to remove this Policy Profile?")
_("Attributes with different values")
_("Attributes with same values")
_("CPU/Memory Recommendations of selected item")
_("CPU/Memory Recommendations of this Image")
_("CPU/Memory Recommendations of this VM")
_("Cancel Changes")
_("Cancel Job")
_("Cancel the selected task")
_("Cancel")
_("Check Compliance of Last Known Configuration")
_("Check Compliance of the last known configuration for the selected Templates")
_("Check Compliance of the last known configuration for the selected items")
_("Check Compliance of the last known configuration for this Image")
_("Check Compliance of the last known configuration for this Instance")
_("Check Compliance of the last known configuration for this Template")
_("Check Compliance of the last known configuration for this VM")
_("Check Compliance of the last known configuration for this item")
_("Clone selected Template")
_("Clone selected item")
_("Clone this Template")
_("Clone this VM")
_("Clone this item")
_("Collapse All")
_("Collect Logs")
_("Collect all logs from the selected #{ui_lookup(:table=>"miq_servers")}")
_("Collect all logs from the selected #{ui_lookup(:table=>"zone")}")
_("Collect all logs")
_("Collect current logs")
_("Collect the current logs from the selected #{ui_lookup(:table=>"miq_servers")}")
_("Collect the current logs from the selected #{ui_lookup(:table=>"zone")}")
_("Collect")
_("Compare Selected Templates")
_("Compare Selected items")
_("Compare selected Templates")
_("Compare selected VMs")
_("Compressed View")
_("Configuration")
_("Copy Selected Customization Templates")
_("Copy object details for use in a Button")
_("Copy original Request")
_("Copy selected Classes")
_("Copy selected Instances")
_("Copy selected Methods")
_("Copy selected Orchestration Template")
_("Copy selected Time Profile")
_("Copy the selected Analysis Profiles")
_("Copy the selected Chargeback Rate to a new Chargeback Rate")
_("Copy the selected Dialog to a new Dialog")
_("Copy the selected Role to a new Role")
_("Copy the selected User to a new User")
_("Copy this #{ui_lookup(:model=>@policy.towhat)} Policy")
_("Copy this Alert")
_("Copy this Chargeback Rate")
_("Copy this Class")
_("Copy this Condition to a new Condition assigned to Policy [#{@condition_policy.description}]")
_("Copy this Condition to a new Condition")
_("Copy this Customization Template")
_("Copy this Dialog")
_("Copy this Instance")
_("Copy this Method")
_("Copy this Orchestration Template")
_("Copy this Policy to new Policy [#{truncate("Copy of #{@policy.description}", :length => 255, :omission => "")}]")
_("Copy this Report")
_("Copy this Role to a new Role")
_("Copy this User to a new User")
_("Copy this Widget")
_("Copy this selected Analysis Profile")
_("Copy")
_("Create Datastore")
_("Create Logical Disk")
_("Create Service Dialog from Orchestration Template")
_("Create a Datastore based on this #{ui_lookup(:model=>"OntapFileShare").split(" - ").last}")
_("Create a Logical Disk (NetApp Flexible Volume) on this #{ui_lookup(:model=>"OntapStorageSystem").split(" - ").last}")
_("Create a new Condition assigned to this Policy")
_("Create a new snapshot for this Template")
_("Create a new snapshot for this VM")
_("Create new Orchestration Template")
_("Delete All Existing Snapshots")
_("Delete All")
_("Delete Older")
_("Delete Selected Snapshot")
_("Delete Server #{@record.name} [#{@record.id}]")
_("Delete Snapshots")
_("Delete Tasks")
_("Delete all finished tasks")
_("Delete all of this Templates existing snapshots?")
_("Delete all of this VMs existing snapshots?")
_("Delete all selected Groups?")
_("Delete all selected LDAP Regions?")
_("Delete all selected Roles?")
_("Delete all selected Users?")
_("Delete all selected items and all of their children?")
_("Delete selected #{@sb[:txt]}")
_("Delete selected Groups")
_("Delete selected LDAP Regions")
_("Delete selected Roles")
_("Delete selected Saved Reports")
_("Delete selected Time Profiles")
_("Delete selected Users")
_("Delete selected items")
_("Delete selected tasks from the VMDB")
_("Delete tasks older than the selected task")
_("Delete the selected Analysis Profiles from the VMDB")
_("Delete the selected Roles from the VMDB")
_("Delete the selected Schedules from the VMDB")
_("Delete this #{ui_lookup(:model=>@condition.towhat)} Condition")
_("Delete this #{ui_lookup(:model=>@policy.towhat)} Policy")
_("Delete this Action")
_("Delete this Alert Profile")
_("Delete this Alert")
_("Delete this Analysis Profile from the VMDB")
_("Delete this Dashboard from the Database")
_("Delete this Group")
_("Delete this LDAP Domain")
_("Delete this LDAP Region")
_("Delete this Report from the Database")
_("Delete this Request")
_("Delete this Role")
_("Delete this Saved Report from the Database")
_("Delete this Schedule from the Database")
_("Delete this Schedule from the VMDB")
_("Delete this User")
_("Delete this Widget from the Database")
_("Delete this Zone")
_("Delete this item")
_("Delete")
_("Demote Server #{@record.miq_server.name} [#{@record.miq_server.id}] to secondary for the #{@record.server_role.description} Role")
_("Demote Server")
_("Deny this Request")
_("Details Mode")
_("Disable the selected Schedules")
_("Discard this new #{@sb[:node_typ].titleize}")
_("Discover #{ui_lookup(:tables=>"ems_clouds")}")
_("Discover #{ui_lookup(:tables=>"ems_infras")}")
_("Discover items")
_("Do you want to delete Server #{@record.name} [#{@record.id}]?")
_("Do you want to demote this Server to secondary?  This will leave no primary Server for this Role.")
_("Do you want to promote this Server to primary?  This will replace any existing primary Server for this Role.")
_("Download as CSV")
_("Download as PDF")
_("Download as Text")
_("Download comparison report in CSV format")
_("Download comparison report in PDF format")
_("Download comparison report in text format")
_("Download summary in PDF format")
_("Download the Entire #{@msg_title} Log File")
_("Download the Entire #{@sb[:rails_log]} Log File")
_("Download the Entire Audit Log File")
_("Download the Entire EVM Log File")
_("Download these items in CSV format")
_("Download these items in PDF format")
_("Download these items in text format")
_("Download this Timeline data in CSV format")
_("Download this Timeline data in PDF format")
_("Download this Timeline data in text format")
_("Download this report in CSV format")
_("Download this report in PDF format")
_("Download this report in text format")
_("Download")
_("Edit '#{session[:customer_name]}' Tags for the selected Groups")
_("Edit '#{session[:customer_name]}' Tags for the selected Tenant")
_("Edit '#{session[:customer_name]}' Tags for the selected Users")
_("Edit '#{session[:customer_name]}' Tags for this Group")
_("Edit '#{session[:customer_name]}' Tags for this Tenant")
_("Edit '#{session[:customer_name]}' Tags for this User")
_("Edit Actions for this Policy Event")
_("Edit Basic Info, Scope, and Notes")
_("Edit Management Engine Relationship")
_("Edit Priority Order  of Domains")
_("Edit Priority Order of Domains")
_("Edit Selected #{ui_lookup(:table=>"container")}")
_("Edit Selected #{ui_lookup(:table=>"container_group")}")
_("Edit Selected #{ui_lookup(:table=>"container_image_registry")}")
_("Edit Selected #{ui_lookup(:table=>"container_node")}")
_("Edit Selected #{ui_lookup(:table=>"container_project")}")
_("Edit Selected #{ui_lookup(:table=>"container_replicator")}")
_("Edit Selected #{ui_lookup(:table=>"container_service")}")
_("Edit Selected #{ui_lookup(:table=>"ems_cloud")}")
_("Edit Selected #{ui_lookup(:table=>"ems_container")}")
_("Edit Selected #{ui_lookup(:table=>"ems_infra")}")
_("Edit Selected Customization Templates")
_("Edit Selected Domains")
_("Edit Selected Instance")
_("Edit Selected Item")
_("Edit Selected Method")
_("Edit Selected Namespace")
_("Edit Selected PXE Servers")
_("Edit Selected Service")
_("Edit Selected Storage Manager")
_("Edit Selected Template")
_("Edit Selected item")
_("Edit Selected items")
_("Edit Sequence of Dashboards")
_("Edit Sequence of User Groups for LDAP Look Up")
_("Edit Tags for the selected #{ui_lookup(:tables=>"ems_clouds")}")
_("Edit Tags for the selected #{ui_lookup(:tables=>"ems_infras")}")
_("Edit Tags for the selected #{ui_lookup(:tables=>"orchestration_stack")}")
_("Edit Tags for the selected #{ui_lookup(:tables=>"storages")}")
_("Edit Tags for the selected Availability Zones")
_("Edit Tags for the selected Flavors")
_("Edit Tags for the selected Repositories")
_("Edit Tags for the selected Resource Pools")
_("Edit Tags for the selected Security Groups")
_("Edit Tags for the selected items")
_("Edit Tags for this #{ui_lookup(:model=>"OntapFileShare").split(" - ").last}")
_("Edit Tags for this #{ui_lookup(:model=>"OntapStorageSystem").split(" - ").last}")
_("Edit Tags for this #{ui_lookup(:table=>"container")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_group")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_groups")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_image")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_image_registries")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_image_registry")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_images")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_node")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_nodes")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_project")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_projects")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_replicator")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_replicators")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_route")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_routes")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_service")}")
_("Edit Tags for this #{ui_lookup(:table=>"container_services")}")
_("Edit Tags for this #{ui_lookup(:table=>"ems_cloud")}")
_("Edit Tags for this #{ui_lookup(:table=>"ems_container")}")
_("Edit Tags for this #{ui_lookup(:table=>"ems_infra")}")
_("Edit Tags for this #{ui_lookup(:table=>"storages")}")
_("Edit Tags for this #{ui_lookup(:tables=>"orchestration_stack")}")
_("Edit Tags for this Availability Zone")
_("Edit Tags for this Catalog Item")
_("Edit Tags for this Configured System")
_("Edit Tags for this Flavor")
_("Edit Tags for this Image")
_("Edit Tags for this Instance")
_("Edit Tags for this Logical Disk")
_("Edit Tags for this Orchestration Template")
_("Edit Tags for this Repository")
_("Edit Tags for this Resource Pool")
_("Edit Tags for this Security Group")
_("Edit Tags for this Service")
_("Edit Tags for this Template")
_("Edit Tags for this VM")
_("Edit Tags for this Volume")
_("Edit Tags for this item")
_("Edit Tags")
_("Edit assignments for this Alert Profile")
_("Edit selected Orchestration Template")
_("Edit selected Schema")
_("Edit selected Time Profile")
_("Edit sequence of Class Schema")
_("Edit sequence")
_("Edit tags for the selected File Shares")
_("Edit tags for the selected Items")
_("Edit tags for the selected Logical Disks")
_("Edit tags for the selected Systems")
_("Edit tags for the selected Templates")
_("Edit tags for the selected Volumes")
_("Edit tags for the selected items")
_("Edit tags for this Cloud Tenant")
_("Edit the Log Depot settings for the selected #{ui_lookup(:table=>"miq_servers")}")
_("Edit the Log Depot settings for the selected #{ui_lookup(:table=>"zone")}")
_("Edit the Selected Repository")
_("Edit the original Request")
_("Edit the selected Analysis Profiles")
_("Edit the selected Chargeback Rate")
_("Edit the selected Dialog")
_("Edit the selected Group")
_("Edit the selected LDAP Region")
_("Edit the selected Role")
_("Edit the selected Schedule")
_("Edit the selected System Image Type")
_("Edit the selected User")
_("Edit the selected item")
_("Edit this #{ui_lookup(:table=>"container")}")
_("Edit this #{ui_lookup(:table=>"container_group")}")
_("Edit this #{ui_lookup(:table=>"container_image_registry")}")
_("Edit this #{ui_lookup(:table=>"container_node")}")
_("Edit this #{ui_lookup(:table=>"container_project")}")
_("Edit this #{ui_lookup(:table=>"container_replicator")}")
_("Edit this #{ui_lookup(:table=>"container_route")}")
_("Edit this #{ui_lookup(:table=>"container_service")}")
_("Edit this #{ui_lookup(:table=>"ems_cloud")}")
_("Edit this #{ui_lookup(:table=>"ems_container")}")
_("Edit this #{ui_lookup(:table=>"ems_infra")}")
_("Edit this Action")
_("Edit this Alert Profile")
_("Edit this Alert")
_("Edit this Analysis Profile")
_("Edit this Button Group")
_("Edit this Button")
_("Edit this Chargeback Rate")
_("Edit this Class")
_("Edit this Condition")
_("Edit this Customization Template")
_("Edit this Dashboard")
_("Edit this Dialog")
_("Edit this Domain")
_("Edit this Group")
_("Edit this ISO Image")
_("Edit this Image")
_("Edit this Instance")
_("Edit this Item")
_("Edit this LDAP Domain")
_("Edit this LDAP Region")
_("Edit this Method")
_("Edit this Namespace")
_("Edit this Orchestration Template")
_("Edit this PXE Image")
_("Edit this PXE Server")
_("Edit this Policy Profile")
_("Edit this Policy's Condition assignments")
_("Edit this Policy's Event assignments")
_("Edit this Provider")
_("Edit this Report")
_("Edit this Repository")
_("Edit this Role")
_("Edit this Schedule")
_("Edit this Service")
_("Edit this Storage Manager")
_("Edit this System Image Type")
_("Edit this Template")
_("Edit this User")
_("Edit this VM")
_("Edit this Widget")
_("Edit this Windows Image")
_("Edit this Zone")
_("Edit this item")
_("Edit")
_("Enable the selected Schedules")
_("Enter Maintenance Mode")
_("Enter Standby Mode")
_("Exists Mode")
_("Exit Maintenance Mode")
_("Expand All")
_("Expanded View")
_("Extract Running Processes for the selected items")
_("Extract Running Processes for the selected items?")
_("Extract Running Processes for this VM")
_("Extract Running Processes for this VM?")
_("Extract Running Processes")
_("Generate Widget content now")
_("Go to this item")
_("Graph View")
_("Grid View")
_("Hard Reboot the Guest OS on this Instance")
_("Hard Reboot the Guest OS on this Instance?")
_("Hard Reboot")
_("History")
_("Hybrid View")
_("Initiate Check Compliance of the last known configuration for the selected Templates?")
_("Initiate Check Compliance of the last known configuration for the selected items?")
_("Initiate Check Compliance of the last known configuration for this Image?")
_("Initiate Check Compliance of the last known configuration for this Instance?")
_("Initiate Check Compliance of the last known configuration for this Template?")
_("Initiate Check Compliance of the last known configuration for this VM?")
_("Initiate Check Compliance of the last known configuration for this item?")
_("Initiate refresh of recent C&U data")
_("Initiate refresh of recent C&U data?")
_("Instance Power Functions")
_("Lifecycle")
_("List View")
_("Lock this Domain")
_("Manage Policies for the selected #{ui_lookup(:tables=>"ems_clouds")}")
_("Manage Policies for the selected #{ui_lookup(:tables=>"ems_infras")}")
_("Manage Policies for the selected Repositories")
_("Manage Policies for the selected Resource Pools")
_("Manage Policies for the selected Templates")
_("Manage Policies for the selected items")
_("Manage Policies for this #{ui_lookup(:table=>"ems_cloud")}")
_("Manage Policies for this #{ui_lookup(:table=>"ems_infra")}")
_("Manage Policies for this Image")
_("Manage Policies for this Instance")
_("Manage Policies for this Repository")
_("Manage Policies for this Resource Pool")
_("Manage Policies for this Template")
_("Manage Policies for this VM")
_("Manage Policies for this item")
_("Manage Policies")
_("Manage Quotas for the Selected Item")
_("Manage Quotas")
_("Migrate selected items to another Host/Datastore")
_("Migrate selected items")
_("Migrate this VM to another Host/Datastore")
_("Migrate this VM")
_("Monitoring")
_("Open a web-based VMRC console for this VM")
_("Open a web-based VMRC console for this VM.  This requires that VMRC is pre-configured to work in your browser.")
_("Open a web-based VNC or SPICE console for this VM")
_("Open a web-based console for this VM")
_("Opening a VM web-based VMRC console requires that VMRC is pre-configured to work in your browser.  Are you sure?")
_("Opening a VM web-based console can take a while and requires that the VMware MKS plugin version configured for Management Engine already be installed and working.  Are you sure?")
_("Opening a web-based VM VNC or SPICE console requires that the Provider is pre-configured to allow VNC connections.  Are you sure?")
_("Pause this Instance")
_("Pause this Instance?")
_("Pause")
_("Perform SmartState Analysis on the selected #{ui_lookup(:tables=>"storages")}")
_("Perform SmartState Analysis on the selected #{ui_lookup(:tables=>"storages")}?")
_("Perform SmartState Analysis on the selected Templates")
_("Perform SmartState Analysis on the selected Templates?")
_("Perform SmartState Analysis on the selected items")
_("Perform SmartState Analysis on the selected items?")
_("Perform SmartState Analysis on this #{ui_lookup(:table=>"storages")}")
_("Perform SmartState Analysis on this #{ui_lookup(:table=>"storages")}?")
_("Perform SmartState Analysis on this Image")
_("Perform SmartState Analysis on this Image?")
_("Perform SmartState Analysis on this Instance")
_("Perform SmartState Analysis on this Instance?")
_("Perform SmartState Analysis on this Template")
_("Perform SmartState Analysis on this Template?")
_("Perform SmartState Analysis on this VM")
_("Perform SmartState Analysis on this VM?")
_("Perform SmartState Analysis on this item")
_("Perform SmartState Analysis on this item?")
_("Perform SmartState Analysis")
_("Policy Simulation")
_("Policy")
_("Power Functions")
_("Power Off the selected items")
_("Power Off the selected items?")
_("Power Off this VM")
_("Power Off this VM?")
_("Power Off this item")
_("Power Off this item?")
_("Power Off")
_("Power On the selected items")
_("Power On the selected items?")
_("Power On this VM")
_("Power On this VM?")
_("Power On this item")
_("Power On this item?")
_("Power On")
_("Power Operations")
_("Power")
_("Promote Server #{@record.miq_server.name} [#{@record.miq_server.id}] to primary for the #{@record.server_role.description} Role")
_("Promote Server")
_("Provision Configured System")
_("Provision Configured Systems")
_("Provision Instances")
_("Provision VMs")
_("Provision items")
_("Provision this item")
_("Provision")
_("Publish selected VM to a Template")
_("Publish this VM to a Template")
_("Put this item into Maintenance Mode")
_("Put this item into Maintenance Mode?")
_("Queue this Report to be generated")
_("Queue up selected Schedules to run now")
_("Queue up this Schedule to run now")
_("Queue")
_("Reconfigure Selected items")
_("Reconfigure the Memory/CPU of this Image")
_("Reconfigure the Memory/CPU of this VM")
_("Reconfigure the Memory/CPUs of selected items")
_("Reconfigure the options of this Service")
_("Reconfigure this Image")
_("Reconfigure this Service")
_("Reconfigure this VM")
_("Refresh Inventory for all Storage CIs known to the selected Storage Managers")
_("Refresh Inventory for all Storage CIs known to the selected Storage Managers?")
_("Refresh Inventory for all Storage CIs known to this Storage Manager")
_("Refresh Inventory for all Storage CIs known to this Storage Manager?")
_("Refresh Inventory")
_("Refresh Relationships and Power States for all items related to the selected Repositories")
_("Refresh Relationships and Power States")
_("Refresh Relationships and Power states")
_("Refresh Relationships for selected ISO Datastores")
_("Refresh Relationships for selected ISO Datastores?")
_("Refresh Relationships for selected PXE Servers")
_("Refresh Relationships for selected PXE Servers?")
_("Refresh Relationships for this ISO Datastore")
_("Refresh Relationships for this ISO Datastore?")
_("Refresh Relationships for this PXE Server")
_("Refresh Relationships for this PXE Server?")
_("Refresh Relationships")
_("Refresh Status for all Storage CIs known to the selected Storage Managers")
_("Refresh Status for all Storage CIs known to the selected Storage Managers?")
_("Refresh Status for all Storage CIs known to this Storage Manager")
_("Refresh Status for all Storage CIs known to this Storage Manager?")
_("Refresh Status")
_("Refresh items and relationships related to this #{ui_lookup(:table=>"ems_container")}")
_("Refresh items and relationships related to this #{ui_lookup(:table=>"ems_container")}?")
_("Refresh items and relationships")
_("Refresh relationships and power states for all items related to the selected #{ui_lookup(:tables=>"ems_clouds")}")
_("Refresh relationships and power states for all items related to the selected #{ui_lookup(:tables=>"ems_clouds")}?")
_("Refresh relationships and power states for all items related to the selected #{ui_lookup(:tables=>"ems_infras")}")
_("Refresh relationships and power states for all items related to the selected #{ui_lookup(:tables=>"ems_infras")}?")
_("Refresh relationships and power states for all items related to the selected Repositories?")
_("Refresh relationships and power states for all items related to the selected Templates")
_("Refresh relationships and power states for all items related to the selected Templates?")
_("Refresh relationships and power states for all items related to the selected items")
_("Refresh relationships and power states for all items related to the selected items?")
_("Refresh relationships and power states for all items related to this #{ui_lookup(:table=>"ems_cloud")}")
_("Refresh relationships and power states for all items related to this #{ui_lookup(:table=>"ems_cloud")}?")
_("Refresh relationships and power states for all items related to this #{ui_lookup(:table=>"ems_infra")}")
_("Refresh relationships and power states for all items related to this #{ui_lookup(:table=>"ems_infra")}?")
_("Refresh relationships and power states for all items related to this Image")
_("Refresh relationships and power states for all items related to this Image?")
_("Refresh relationships and power states for all items related to this Instance")
_("Refresh relationships and power states for all items related to this Instance?")
_("Refresh relationships and power states for all items related to this Repository")
_("Refresh relationships and power states for all items related to this Repository?")
_("Refresh relationships and power states for all items related to this Template")
_("Refresh relationships and power states for all items related to this Template?")
_("Refresh relationships and power states for all items related to this VM")
_("Refresh relationships and power states for all items related to this VM?")
_("Refresh relationships and power states for all items related to this item")
_("Refresh relationships and power states for all items related to this item?")
_("Refresh relationships for all items related to the selected items")
_("Refresh relationships for all items related to the selected items?")
_("Refresh relationships for all items related to this Provider")
_("Refresh relationships for all items related to this Provider?")
_("Reload Current Display")
_("Reload Widgets")
_("Reload current display")
_("Reload current workers display")
_("Reload selected Reports")
_("Reload the #{@msg_title} Log Display")
_("Reload the #{@sb[:rails_log]} Log Display")
_("Reload the Audit Log Display")
_("Reload the EVM Log Display")
_("Reload the charts from the most recent C&U data")
_("Reload the current display")
_("Reload")
_("Remove #{ui_lookup(:tables=>"container_groups")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"container_image_registries")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"container_nodes")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"container_project")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"container_replicators")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"container_services")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"containers")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"ems_clouds")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"ems_containers")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"ems_infras")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"orchestration_stack")} from the VMDB")
_("Remove #{ui_lookup(:tables=>"storages")} from the VMDB")
_("Remove Customization Templates from the VMDB")
_("Remove Domains")
_("Remove ISO Datastores from the VMDB")
_("Remove Instances")
_("Remove Item from the VMDB")
_("Remove Items from the VMDB")
_("Remove Methods")
_("Remove Namespaces")
_("Remove PXE Servers from the VMDB")
_("Remove Repositories from the VMDB")
_("Remove Resource Pools from the VMDB")
_("Remove Selected Repositories from the VMDB")
_("Remove Selected items from the VMDB")
_("Remove Service from the VMDB")
_("Remove Services from the VMDB")
_("Remove Storage Managers from the VMDB")
_("Remove System Image Types from the VMDB")
_("Remove Templates from the VMDB")
_("Remove from the VMDB")
_("Remove items from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"container_groups")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"container_image_registries")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"container_nodes")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"container_projects")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"container_replicators")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"container_services")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"containers")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"ems_clouds")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"ems_containers")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"ems_infras")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"orchestration_stack")} from the VMDB")
_("Remove selected #{ui_lookup(:tables=>"storages")} from the VMDB")
_("Remove selected Chargeback Rates from the VMDB")
_("Remove selected Customization Templates from the VMDB")
_("Remove selected Dialogs from the VMDB")
_("Remove selected Domains")
_("Remove selected ISO Datastores from the VMDB")
_("Remove selected Instances")
_("Remove selected Items from the VMDB")
_("Remove selected Items")
_("Remove selected Methods")
_("Remove selected Namespaces")
_("Remove selected Orchestration Templates")
_("Remove selected Orchestration Templates?")
_("Remove selected PXE Servers from the VMDB")
_("Remove selected Resource Pools from the VMDB")
_("Remove selected Services from the VMDB")
_("Remove selected Storage Managers from the VMDB")
_("Remove selected System Image Types from the VMDB")
_("Remove selected Templates from the VMDB")
_("Remove selected items from the VMDB")
_("Remove this #{ui_lookup(:table=>"container")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_group")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_image_registry")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_node")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_project")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_replicator")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_route")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"container_service")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"ems_cloud")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"ems_container")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"ems_infra")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"orchestration_stack")} from the VMDB")
_("Remove this #{ui_lookup(:table=>"storages")} from the VMDB")
_("Remove this Button Group")
_("Remove this Button")
_("Remove this Chargeback Rate from the VMDB")
_("Remove this Class")
_("Remove this Condition from Policy [#{@condition_policy.description}]")
_("Remove this Customization Template from the VMDB")
_("Remove this Dialog from the VMDB")
_("Remove this Domain")
_("Remove this ISO Datastore from the VMDB")
_("Remove this Image from the VMDB")
_("Remove this Instance from the VMDB")
_("Remove this Instance")
_("Remove this Item from the VMDB")
_("Remove this Method")
_("Remove this Namespace")
_("Remove this Orchestration Template")
_("Remove this Orchestration Template?")
_("Remove this PXE Server from the VMDB")
_("Remove this Policy Profile")
_("Remove this Provider from the VMDB")
_("Remove this Repository from the VMDB")
_("Remove this Resource Pool from the VMDB")
_("Remove this Service from the VMDB")
_("Remove this Storage Manager from the VMDB")
_("Remove this System Image Type from the VMDB")
_("Remove this Template from the VMDB")
_("Remove this VM from the VMDB")
_("Remove this item from the VMDB")
_("Reorder #{x_active_tree == :ab_tree ? "Buttons Groups" : "Buttons and Groups"}")
_("Reorder")
_("Request to Provision Instances")
_("Request to Provision VMs")
_("Request to Provision items")
_("Request to Provision")
_("Reset the selected items")
_("Reset the selected items?")
_("Reset this VM")
_("Reset this VM?")
_("Reset this item")
_("Reset this item?")
_("Reset")
_("Restart Guest")
_("Restart selected worker")
_("Restart server")
_("Restart the Guest OS on the selected items")
_("Restart the Guest OS on the selected items?")
_("Restart the Guest OS on this VM")
_("Restart the Guest OS on this VM?")
_("Restart the selected items")
_("Restart the selected items?")
_("Restart this item")
_("Restart this item?")
_("Restart")
_("Resume this Instance")
_("Resume this Instance?")
_("Resume")
_("Retire selected #{ui_lookup(:tables => "orchestration_stack")}")
_("Retire selected items")
_("Retire the selected #{ui_lookup(:tables => "orchestration_stack")}?")
_("Retire the selected items")
_("Retire the selected items?")
_("Retire this Instance")
_("Retire this Instance?")
_("Retire this Orchestration Stack")
_("Retire this Service")
_("Retire this Service?")
_("Retire this VM")
_("Retire this VM?")
_("Revert to selected snapshot")
_("Right-Size Recommendations")
_("Save Changes")
_("Save")
_("Scale this #{ui_lookup(:table=>"ems_infra")}")
_("Select Classes to copy")
_("Select Instances to copy")
_("Select Methods to copy")
_("Select a single #{ui_lookup(:table=>"container")} to edit")
_("Select a single #{ui_lookup(:table=>"container_group")} to edit")
_("Select a single #{ui_lookup(:table=>"container_image_registry")} to edit")
_("Select a single #{ui_lookup(:table=>"container_node")} to edit")
_("Select a single #{ui_lookup(:table=>"container_project")} to edit")
_("Select a single #{ui_lookup(:table=>"container_replicator")} to edit")
_("Select a single #{ui_lookup(:table=>"container_service")} to edit")
_("Select a single #{ui_lookup(:table=>"ems_cloud")} to edit")
_("Select a single #{ui_lookup(:table=>"ems_container")} to edit")
_("Select a single #{ui_lookup(:table=>"ems_infra")} to edit")
_("Select a single Customization Templates to copy")
_("Select a single Customization Templates to edit")
_("Select a single Domains to edit")
_("Select a single Group to edit")
_("Select a single Instance to edit")
_("Select a single Item to edit")
_("Select a single LDAP Region to edit")
_("Select a single Method to edit")
_("Select a single Namespace to edit")
_("Select a single PXE Servers to edit")
_("Select a single Repository to edit")
_("Select a single Role to copy")
_("Select a single Role to edit")
_("Select a single Storage Manager to edit")
_("Select a single System Image Type to edit")
_("Select a single Template to edit")
_("Select a single Time Profile to copy")
_("Select a single Time Profile to edit")
_("Select a single User to copy")
_("Select a single User to edit")
_("Select a single item to edit")
_("Select a single item to manage quotas")
_("Select a single service to edit")
_("Select a worker to restart")
_("Select one or more Groups to delete")
_("Select one or more LDAP Regions to delete")
_("Select one or more Users to delete")
_("Select one or more items to delete")
_("Select two or more Templates to compare")
_("Select two or more items to compare")
_("Select up to 10 timestamps for Drift Analysis")
_("Set Ownership for the selected Services")
_("Set Ownership for the selected Templates")
_("Set Ownership for the selected items")
_("Set Ownership for this Image")
_("Set Ownership for this Instance")
_("Set Ownership for this Service")
_("Set Ownership for this Template")
_("Set Ownership for this VM")
_("Set Ownership")
_("Set Retirement Date")
_("Set Retirement Dates for the selected #{ui_lookup(:tables=>"orchestration_stack")}")
_("Set Retirement Dates for the selected items")
_("Set Retirement Dates for this Instance")
_("Set Retirement Dates for this Orchestration Stack")
_("Set Retirement Dates for this Service")
_("Set Retirement Dates for this VM")
_("Set Retirement Dates")
_("Shelve Offload this Instance")
_("Shelve Offload this Instance?")
_("Shelve Offload")
_("Shelve this Instance")
_("Shelve this Instance?")
_("Shelve")
_("Show #{@layout == "cim_base_storage_extent" ? @record.evm_display_name : @record.name} Summary")
_("Show Capacity & Utilization data for this #{ui_lookup(:table=>"storages")}")
_("Show Capacity & Utilization data for this Availability Zone")
_("Show Capacity & Utilization data for this Container")
_("Show Capacity & Utilization data for this Group")
_("Show Capacity & Utilization data for this Instance")
_("Show Capacity & Utilization data for this Logical Disk")
_("Show Capacity & Utilization data for this Node")
_("Show Capacity & Utilization data for this Template")
_("Show Capacity & Utilization data for this VM")
_("Show Capacity & Utilization data for this item")
_("Show Timelines for this #{ui_lookup(:table=>"availability_zone")}")
_("Show Timelines for this #{ui_lookup(:table=>"ems_cloud")}")
_("Show Timelines for this #{ui_lookup(:table=>"ems_container")}")
_("Show Timelines for this #{ui_lookup(:table=>"ems_infra")}")
_("Show Timelines for this Container")
_("Show Timelines for this Group")
_("Show Timelines for this Instance")
_("Show Timelines for this Node")
_("Show Timelines for this Project")
_("Show Timelines for this Replicator")
_("Show Timelines for this Template")
_("Show Timelines for this VM")
_("Show Timelines for this item")
_("Show Utilization Statistics for this Logical Disk")
_("Show Utilization for this #{ui_lookup(:model=>"OntapFileShare").split(" - ").last}")
_("Show Utilization for this #{ui_lookup(:model=>"OntapStorageSystem").split(" - ").last}")
_("Show Utilization for this Storage System")
_("Show full screen report")
_("Shutdown Guest")
_("Shutdown the Guest OS on the selected items")
_("Shutdown the Guest OS on the selected items?")
_("Shutdown the Guest OS on this VM")
_("Shutdown the Guest OS on this VM?")
_("Shutdown the selected items to Standby Mode")
_("Shutdown the selected items to Standy Mode?")
_("Shutdown the selected items")
_("Shutdown the selected items?")
_("Shutdown this item to Standby Mode")
_("Shutdown this item to Standby Mode?")
_("Shutdown this item")
_("Shutdown this item?")
_("Shutdown")
_("Simulate using Button details")
_("Simulate")
_("Soft Reboot this Instance")
_("Soft Reboot this Instance?")
_("Soft Reboot")
_("Start Role")
_("Start the #{@record.server_role.description} Role on Server #{@record.miq_server.name} [#{@record.miq_server.id}]")
_("Start the #{@record.server_role.description} Role on Server #{@record.miq_server.name} [#{@record.miq_server.id}]?")
_("Start this Instance")
_("Start this Instance?")
_("Start")
_("Statistics")
_("Stop this Instance")
_("Stop this Instance?")
_("Stop")
_("Suspend Role")
_("Suspend the #{@record.server_role.description} Role on Server #{@record.miq_server.name} [#{@record.miq_server.id}]")
_("Suspend the #{@record.server_role.description} Role on Server #{@record.miq_server.name} [#{@record.miq_server.id}]?")
_("Suspend the selected items")
_("Suspend the selected items?")
_("Suspend this Instance")
_("Suspend this Instance?")
_("Suspend this VM")
_("Suspend this VM?")
_("Suspend")
_("Tabular View")
_("Take this item out of Maintenance Mode")
_("Take this item out of Maintenance Mode?")
_("Terminate the selected items")
_("Terminate the selected items?")
_("Terminate this Instance")
_("Terminate this Instance?")
_("Terminate")
_("The selected Reports will be permanently removed from the database. Are you sure you want to delete this Report?")
_("The selected Saved Reports will be permanently removed from the database. Are you sure you want to delete the selected Saved Reports?")
_("The selected Saved Reports will be permanently removed from the database. Are you sure you want to delete this saved Report?")
_("The selected snapshot will be permanently deleted. Are you sure you want to delete the selected snapshot?")
_("This Template will revert to selected snapshot. Are you sure you want to revert to the selected snapshot?")
_("This VM will revert to selected snapshot. Are you sure you want to revert to the selected snapshot?")
_("This will show the entire report (all rows) in your browser.  Do you want to proceed?")
_("Tile View")
_("Timelines")
_("Unlock this Domain")
_("Utilization")
_("VM Power Functions")
_("View Policy Simulation for the selected Templates")
_("View Policy Simulation for the selected items")
_("View Policy Simulation for this Image")
_("View Policy Simulation for this Instance")
_("View Policy Simulation for this Template")
_("View Policy Simulation for this VM")
_("Warning: Finished tasks will be permanently removed from the database. Are you sure you want to delete all finished tasks?")
_("Warning: Selected node will be restarted, do you want to continue?")
_("Warning: Server will be restarted, do you want to continue?")
_("Warning: Tasks that are older than selected task will be permanently removed from the database. Are you sure you want to delete older tasks?")
_("Warning: The selected #{ui_lookup(:tables=>"container_groups")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"container_groups")}?")
_("Warning: The selected #{ui_lookup(:tables=>"container_image_registries")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"container_image_registries")}?")
_("Warning: The selected #{ui_lookup(:tables=>"container_nodes")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"container_nodes")}?")
_("Warning: The selected #{ui_lookup(:tables=>"container_projects")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"container_projects")}?")
_("Warning: The selected #{ui_lookup(:tables=>"container_replicators")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"container_replicators")}?")
_("Warning: The selected #{ui_lookup(:tables=>"container_services")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"container_services")}?")
_("Warning: The selected #{ui_lookup(:tables=>"containers")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"containers")}?")
_("Warning: The selected #{ui_lookup(:tables=>"ems_clouds")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"ems_clouds")}?")
_("Warning: The selected #{ui_lookup(:tables=>"ems_containers")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"ems_containers")}?")
_("Warning: The selected #{ui_lookup(:tables=>"ems_infras")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"ems_infras")}?")
_("Warning: The selected #{ui_lookup(:tables=>"orchestration_stack")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"orchestration_stack")}?")
_("Warning: The selected #{ui_lookup(:tables=>"storages")} and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected #{ui_lookup(:tables=>"storages")}?")
_("Warning: The selected Analysis Profiles and ALL of their components will be permanently removed from the VMDB.  Are you sure you want to delete the selected Analysis Profiles?")
_("Warning: The selected Button Group will be permanently removed.  Are you sure you want to remove the selected Button Group?")
_("Warning: The selected Chargeback Rate will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Chargeback Rates?")
_("Warning: The selected Customization Templates will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Customization Templates?")
_("Warning: The selected Dialog will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Dialogs?")
_("Warning: The selected ISO Datastores and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected ISO Datastores?")
_("Warning: The selected Items and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Items?")
_("Warning: The selected Items will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Items?")
_("Warning: The selected PXE Servers and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected PXE Servers?")
_("Warning: The selected Provider and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Provider?")
_("Warning: The selected Repositories and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Repositories?")
_("Warning: The selected Resource Pools and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Resource Pools?")
_("Warning: The selected Schedules and ALL of their components will be permanently removed from the VMDB.  Are you sure you want to delete the selected Schedules?")
_("Warning: The selected Services and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Services?")
_("Warning: The selected Storage Managers and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Storage Managers?")
_("Warning: The selected System Image Types will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected System Image Types?")
_("Warning: The selected Templates and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected Templates?")
_("Warning: The selected Time Profiles will be permanently removed from the VMDB. Are you sure you want to delete the selected Time Profiles?")
_("Warning: The selected items and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove the selected items?")
_("Warning: The selected task will be cancelled. Are you sure you want to cancel the task?")
_("Warning: The selected tasks will be permanently removed from the database. Are you sure you want to delete the selected tasks?")
_("Warning: This #{ui_lookup(:table=>"container")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container")}?")
_("Warning: This #{ui_lookup(:table=>"container_group")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_group")}?")
_("Warning: This #{ui_lookup(:table=>"container_image_registry")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_image_registry")}?")
_("Warning: This #{ui_lookup(:table=>"container_node")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_node")}?")
_("Warning: This #{ui_lookup(:table=>"container_project")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_project")}?")
_("Warning: This #{ui_lookup(:table=>"container_replicator")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_replicator")}?")
_("Warning: This #{ui_lookup(:table=>"container_route")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_route")}?")
_("Warning: This #{ui_lookup(:table=>"container_service")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"container_service")}?")
_("Warning: This #{ui_lookup(:table=>"ems_cloud")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"ems_cloud")}?")
_("Warning: This #{ui_lookup(:table=>"ems_container")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"ems_container")}?")
_("Warning: This #{ui_lookup(:table=>"ems_infra")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"ems_infra")}?")
_("Warning: This #{ui_lookup(:table=>"orchestration_stack")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"orchestration_stack")}?")
_("Warning: This #{ui_lookup(:table=>"storages")} and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this #{ui_lookup(:table=>"storages")}?")
_("Warning: This Analysis Profile and ALL of its components will be permanently removed from the VMDB.  Are you sure you want to delete this Analysis Profile?")
_("Warning: This Button will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Button?")
_("Warning: This Catalog Items and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Catalog Item?")
_("Warning: This Catalog will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Catalog?")
_("Warning: This Chargeback Rate will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Chargeback Rate?")
_("Warning: This Customization Template will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Customization Template?")
_("Warning: This Dashboard and ALL of its components will be permanently removed from the VMDB.  Are you sure you want to delete this Dashboard?")
_("Warning: This Dialog will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Dialog?")
_("Warning: This ISO Datastore and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this ISO Datastore?")
_("Warning: This Image and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Image?")
_("Warning: This Instance and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Instance?")
_("Warning: This PXE Server and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this PXE Server?")
_("Warning: This Repository and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Repository?")
_("Warning: This Resource Pool and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Resource Pool?")
_("Warning: This Saved Report and ALL of its components will be permanently removed from the VMDB.  Are you sure you want to delete this Saved Report?")
_("Warning: This Schedule and ALL of its components will be permanently removed from the VMDB.  Are you sure you want to delete this Schedule?")
_("Warning: This Service and ALL of their components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Service?")
_("Warning: This Storage Manager and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Storage Manager?")
_("Warning: This System Image Type will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this System Image Type?")
_("Warning: This Template and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this Template?")
_("Warning: This VM and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this VM?")
_("Warning: This Widget and ALL of its components will be permanently removed from the VMDB.  Are you sure you want to delete this Widget?")
_("Warning: This item and ALL of its components will be permanently removed from the Virtual Management Database.  Are you sure you want to remove this item?")
