class AddVmTableComments < ActiveRecord::Migration[5.0]
  def change
    change_table_comment :vms, "Virtual Machines and Templates"

    change_column_comment :vms, :autostart, "Indicates whether or not the VM is set to autostart."
    change_column_comment :vms, :availability_zone_id, "ID of the availability zone that the VM is part of."
    change_column_comment :vms, :busy, "HELP"
    change_column_comment :vms, :boot_time, "The last time the VM was started."
    change_column_comment :vms, :cloud, "Indicates whether or not the VM/Template is cloud or infra."
    change_column_comment :vms, :cloud_network_id, "ID of the cloud (virtual) network the VM/Template is associated with."
    change_column_comment :vms, :cloud_subnet_id, "Subnet ID associated with the VM."
    change_column_comment :vms, :cloud_tenant_id, "ID of the cloud tenant associated with the VM."
    change_column_comment :vms, :config_xml, "The VM or Template configuration in XML format. Deprecated."
    change_column_comment :vms, :connection_state, "HELP"
    change_column_comment :vms, :cpu_affinity, "HELP"
    change_column_comment :vms, :cpu_hot_add_enabled, "HELP"
    change_column_comment :vms, :cpu_hot_remove_enabled, "HELP"
    change_column_comment :vms, :cpu_limit, "HELP"
    change_column_comment :vms, :cpu_reserve, "HELP"
    change_column_comment :vms, :cpu_reserve_expand, "HELP"
    change_column_comment :vms, :cpu_shares, "HELP"
    change_column_comment :vms, :cpu_shares_level, "HELP"
    change_column_comment :vms, :created_on, "The date the VM was added to the app inventory."
    change_column_comment :vms, :deprecated, "HELP"
    change_column_comment :vms, :description, "A custom description that users can add within the app."
    change_column_comment :vms, :ems_created_on, "Date the associated EMS was created."
    change_column_comment :vms, :ems_id, "ID of the ExtManagementSystem associated with the VM."
    change_column_comment :vms, :evm_owner_id, "ID of VM owner from product database."
    change_column_comment :vms, :ems_ref_obj, "HELP"
    change_column_comment :vms, :ems_cluster_id, "ID of associated cluster."
    change_column_comment :vms, :fault_tolerance, "HELP"
    change_column_comment :vms, :flavor_id, "ID of associated flavor."
    change_column_comment :vms, :format, "The format of the VM's disk, such as VMDK."
    change_column_comment :vms, :guid, "A value used to uniquely identify the VM internally."
    change_column_comment :vms, :id, "The internal database ID."
    change_column_comment :vms, :host_id, "ID of the host that the VM/Template resides on."
    change_column_comment :vms, :last_perf_capture_on, "Timestamp for last performance metrics capture."
    change_column_comment :vms, :last_scan_on, "Timestamp for last SmartState Analysis."
    change_column_comment :vms, :last_scan_attempt_on, "Timestamp for last attempt to perform SmartState Analysis."
    change_column_comment :vms, :last_sync_on, "HELP"
    change_column_comment :vms, :linked_clone, "HELP"
    change_column_comment :vms, :location, "The location or region of the VM."
    change_column_comment :vms, :memory_hot_add_enabled, "HELP"
    change_column_comment :vms, :memory_hot_add_increment, "HELP"
    change_column_comment :vms, :memory_hot_add_limit, "HELP"
    change_column_comment :vms, :memory_limit, "HELP"
    change_column_comment :vms, :memory_reserve, "HELP"
    change_column_comment :vms, :memory_reserve_expand, "HELP"
    change_column_comment :vms, :memory_shares, "HELP"
    change_column_comment :vms, :memory_shares_level, "HELP"
    change_column_comment :vms, :miq_group_id, "MIQ Group associated with the VM."
    change_column_comment :vms, :name, "The name of the VM/Template."
    change_column_comment :vms, :orchestration_stack_id, "ID of the orchestration stack associated with the VM."
    change_column_comment :vms, :power_state, "The current power state, typically 'on' or 'off'."
    change_column_comment :vms, :previous_state, "The previous power state change."
    change_column_comment :vms, :publicly_available, "Indicates whether the VM is public or private."
    change_column_comment :vms, :raw_power_state, "HELP"
    change_column_comment :vms, :registered, "Indicates whether the VM registered to a Provider."
    change_column_comment :vms, :resource_group_id, "ID of the resource group that the VM/Template belongs to."
    change_column_comment :vms, :retired, "Indicates whether or not the VM is retired."
    change_column_comment :vms, :retirement_last_warn, "Date of last retirement warning."
    change_column_comment :vms, :retirement_requester, "Userid of the user who requested retirement."
    change_column_comment :vms, :retirement_state, "The current retirement state."
    change_column_comment :vms, :retirement_warn, "Warning message when VM was put into retirement."
    change_column_comment :vms, :retires_on, "Date the VM is to be retired."
    change_column_comment :vms, :smart, "HELP"
    change_column_comment :vms, :standby_action, "Action taken when VM is put into standby mode."
    change_column_comment :vms, :storage_id, "ID of the storage object associated with the VM."
    change_column_comment :vms, :storage_profile_id, "ID of the storage profile associated with the VM."
    change_column_comment :vms, :state_changed_on, "The date of the last power state change."
    change_column_comment :vms, :template, "Indicates if a template was used to provision the VM or not."
    change_column_comment :vms, :tenant_id, "ID of the tenant associated with the VM."
    change_column_comment :vms, :tools_status, "Status of VMWare tools."
    change_column_comment :vms, :type, "An internal class name that includes the provider type."
    change_column_comment :vms, :uid_ems, "HELP"
    change_column_comment :vms, :updated_on, "The last date the VM was modified within the app."
    change_column_comment :vms, :vendor, "The vendor for the VM, e.g. Azure, Amazon, etc."
    change_column_comment :vms, :version, "HELP"
    change_column_comment :vms, :vnc_port, "Port or port range used for VNC connections."
  end
end
