#!/bin/bash

function setup_ruby() {
version=$1

cat <<EOF
#!/bin/bash

function setup_ruby() {
  yum -y update
  yum -y install git-core zlib zlib-devel gcc-c++ patch readline readline-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison curl sqlite-devel postgresql-devel
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  export HOME="/root"
  echo 'export HOME="/root"' >> ~/.bash_profile
  echo 'export PATH="\$HOME/.rbenv/bin:\$PATH"' >> ~/.bash_profile
  echo "eval '\$(/root/.rbenv/bin/rbenv init -)'" >> ~/.bash_profile
  source ~/.bash_profile
  git clone git://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  echo 'export PATH="\$HOME/.rbenv/plugins/ruby-build/bin:\$PATH"' >> ~/.bash_profile
  source ~/.bash_profile
  echo \$PATH
  rbenv install -l
  rbenv install ${version}
  rbenv global ${version}
  gem install bundler
  rbenv rehash
  ruby -v
}
EOF
}

function install_gems() {
gemfile=$1

cat <<EOF
#
# Install Gems
#

function install_gems() {
  mkdir -p /opt/miq/log
  cd /opt/miq
EOF
while read -r line
do
  echo "  echo '$line' >> Gemfile"
done < $gemfile
echo "  bundle install"
echo "}"
}

function create_setting_yml() {
yml=$1
cat <<EOF
#
# Create settings yaml file 
#
function create_setting_yml() {
  cd /opt/miq
EOF
while read -r line
do
  echo "  echo '$line' >> default_ssa_config.yml"
done < $yml
echo "}"
}

function create_startup_script() {
cat <<EOF
#
# Script to start up agent
#
function create_startup_script() {
  ll=\$1
  bundle exec amazon_ssa_agent -l \${ll}
}
EOF
}

function add_rc_local_script() {
cat <<EOF
#
# Add following commands into rc.local, so they can be autorun after power on
#
function add_rc_local_script() {
  chmod +x /etc/rc.d/rc.local
  echo 'source /root/.bash_profile' >> /etc/rc.d/rc.local
  echo 'bundle exec amazon_ssa_agent &' >> /etc/rc.d/rc.local
}
EOF
}

function userdata() {
ver=$1
loglevel=$2
cat <<EOF
#
# Setup environment
#
echo "Start to setup Amazon agent"
(
  setup_ruby "${ver}"
  install_gems
  create_setting_yml
  add_rc_local_script
  create_startup_script "$loglevel"
)  >> /var/log/miq_ssa_deploy.log 2>&1
EOF
}

ruby_version=$1
log_level=$2

setup_ruby
install_gems 'tools/amazon_agent_settings/agent_gemfile'
create_setting_yml 'tools/amazon_agent_settings/default_ssa_config.yml'
add_rc_local_script
create_startup_script
userdata $ruby_version $log_level
