# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dialog_field.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manageiq.dialog.Input" do
    optional :namespace, :string, 1
    optional :class_name, :string, 2
    optional :instance_name, :string, 3
    optional :automate_message, :string, 4
    optional :user_id, :string, 5
    optional :miq_group_id, :string, 6
    optional :tenant_id, :string, 7
    optional :object_type, :string, 8
    optional :object_id, :string, 9
    map :attrs, :string, :string, 10
  end
  add_message "manageiq.dialog.DialogFieldCheckBoxResult" do
    optional :required, :bool, 1
    optional :read_only, :bool, 2
    optional :visible, :bool, 3
    optional :value, :string, 4
  end
  add_message "manageiq.dialog.DialogFieldTextBoxResult" do
    optional :data_type, :string, 1
    optional :protected, :bool, 2
    optional :required, :bool, 3
    optional :validator_rule, :string, 4
    optional :validator_type, :string, 5
    optional :read_only, :bool, 6
    optional :visible, :bool, 7
    optional :value, :string, 8
  end
  add_message "manageiq.dialog.DialogFieldTextAreaBoxResult" do
    optional :required, :bool, 1
    optional :read_only, :bool, 2
    optional :visible, :bool, 3
    optional :value, :string, 4
  end
  add_message "manageiq.dialog.DialogFieldSortedItemResult" do
    optional :sort_by, :string, 1
    optional :sort_order, :string, 2
    optional :data_type, :string, 3
    optional :default_value, :string, 4
    optional :required, :bool, 5
    map :values, :int64, :string, 6
  end
  add_message "manageiq.dialog.DialogFieldDateTimeControlResult" do
    optional :show_past_dates, :bool, 1
    optional :read_only, :bool, 2
    optional :visible, :bool, 3
    optional :value, :string, 4
  end
  add_message "manageiq.dialog.DialogFieldDateControlResult" do
    optional :show_past_dates, :bool, 1
    optional :read_only, :bool, 2
    optional :visible, :bool, 3
    optional :value, :string, 4
  end
end

module Manageiq
  module Dialog
    Input = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.Input").msgclass
    DialogFieldCheckBoxResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.DialogFieldCheckBoxResult").msgclass
    DialogFieldTextBoxResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.DialogFieldTextBoxResult").msgclass
    DialogFieldTextAreaBoxResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.DialogFieldTextAreaBoxResult").msgclass
    DialogFieldSortedItemResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.DialogFieldSortedItemResult").msgclass
    DialogFieldDateTimeControlResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.DialogFieldDateTimeControlResult").msgclass
    DialogFieldDateControlResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("manageiq.dialog.DialogFieldDateControlResult").msgclass
  end
end
