# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: dialog_field.proto for package 'manageiq.dialog'

require 'grpc'
require 'dialog_field_pb'

module Manageiq
  module Dialog
    module AutomateDialog
      # The Dialog service definition.
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'manageiq.dialog.AutomateDialog'

        # Sends back the result of a dialog field method
        rpc :GetDialogFieldDateControl, Input, DialogFieldDateControlResult
        rpc :GetDialogFieldDateTimeControl, Input, DialogFieldDateTimeControlResult
        rpc :GetDialogFieldSortedItem, Input, DialogFieldSortedItemResult
        rpc :GetDialogFieldTextAreaBox, Input, DialogFieldTextAreaBoxResult
        rpc :GetDialogFieldTextBox, Input, DialogFieldTextBoxResult
        rpc :GetDialogFieldCheckBox, Input, DialogFieldCheckBoxResult
      end

      Stub = Service.rpc_stub_class
    end
  end
end
