#!/usr/bin/env ruby

require "awesome_spawn"
cmd = File.expand_path("decrypt_env_vars", __dir__)
result = AwesomeSpawn.run!(cmd)

require "yaml"
env_vars = YAML.load(result.output)

Process.detach(Kernel.spawn(env_vars, ARGV.join(" ")))
