module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAutomationManager_ConfigurationScriptSource <
    MiqAeServiceManageIQ_Providers_AutomationManager_ConfigurationScriptSource
  end
end
