module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_NetworkCredential <
    MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_Credential
  end
end
