module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_AmazonCredential < MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_CloudCredential
  end
end
