module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_ConfigurationScript < MiqAeServiceManageIQ_Providers_EmbeddedAutomationManager_ConfigurationScript
    expose :run
  end
end
