module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_ExternalAutomationManager_ConfigurationScript < MiqAeServiceManageIQ_Providers_AutomationManager_ConfigurationScript
    expose :run
  end
end
