module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_NetworkCredential < MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_MachineCredential
  end
end
