module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_RackspaceCredential < MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_CloudCredential
  end
end
