module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_CloudCredential < MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_MachineCredential
  end
end
