module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_Playbook < MiqAeServiceManageIQ_Providers_ExternalAutomationManager_ConfigurationScriptPayload
  end
end
