module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_Satellite6Credential < MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_CloudCredential
  end
end
