module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_RackspaceCredential < MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_CloudCredential
  end
end
