module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_Project <
    MiqAeServiceManageIQ_Providers_EmbeddedAutomationManager_ConfigurationScriptSource
  end
end
