module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_OpenstackCredential < MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_CloudCredential
  end
end
