module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_GoogleCredential < MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_CloudCredential
  end
end
