module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_Project <
    MiqAeServiceManageIQ_Providers_ExternalAutomationManager_ConfigurationScriptSource
  end
end
