module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_AzureCredential < MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_CloudCredential
  end
end
