module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_GoogleCredential < MiqAeServiceManageIQ_Providers_AnsibleTower_AutomationManager_CloudCredential
  end
end
