module MiqAeMethodService
  class MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_OpenstackCredential < MiqAeServiceManageIQ_Providers_EmbeddedAnsible_AutomationManager_CloudCredential
  end
end
