#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
_('Account')
_('Account|Acctid')
_('Account|Accttype')
_('Account|Comment')
_('Account|Display name')
_('Account|Domain')
_('Account|Enabled')
_('Account|Expires')
_('Account|Homedir')
_('Account|Last logon')
_('Account|Local')
_('Account|Name')
_('Advanced setting')
_('AdvancedSetting|Created on')
_('AdvancedSetting|Default value')
_('AdvancedSetting|Description')
_('AdvancedSetting|Display name')
_('AdvancedSetting|Max')
_('AdvancedSetting|Min')
_('AdvancedSetting|Name')
_('AdvancedSetting|Read only')
_('AdvancedSetting|Resource type')
_('AdvancedSetting|Updated on')
_('AdvancedSetting|Value')
_('Assigned server role')
_('AssignedServerRole|Active')
_('AssignedServerRole|Priority')
_('Audit event')
_('AuditEvent|Created on')
_('AuditEvent|Event')
_('AuditEvent|Message')
_('AuditEvent|Severity')
_('AuditEvent|Source')
_('AuditEvent|Status')
_('AuditEvent|Target class')
_('AuditEvent|Userid')
_('Authentication')
_('Authentication|Auth key')
_('Authentication|Authtype')
_('Authentication|Created on')
_('Authentication|Credentials changed on')
_('Authentication|Fingerprint')
_('Authentication|Last invalid on')
_('Authentication|Last valid on')
_('Authentication|Name')
_('Authentication|Password')
_('Authentication|Resource type')
_('Authentication|Status')
_('Authentication|Status details')
_('Authentication|Updated on')
_('Authentication|Userid')
_('Availability zone')
_('AvailabilityZone|Ems ref')
_('AvailabilityZone|Name')
_('Binary blob')
_('BinaryBlob|Data type')
_('BinaryBlob|Md5')
_('BinaryBlob|Name')
_('BinaryBlob|Part size')
_('BinaryBlob|Resource type')
_('BinaryBlob|Size')
_('Binary blob part')
_('BinaryBlobPart|Data')
_('BinaryBlobPart|Md5')
_('BinaryBlobPart|Size')
_('Bottleneck event')
_('BottleneckEvent|Context data')
_('BottleneckEvent|Created on')
_('BottleneckEvent|Event type')
_('BottleneckEvent|Future')
_('BottleneckEvent|Message')
_('BottleneckEvent|Resource name')
_('BottleneckEvent|Resource type')
_('BottleneckEvent|Severity')
_('BottleneckEvent|Timestamp')
_('Chargeback rate')
_('ChargebackRate|Created on')
_('ChargebackRate|Default')
_('ChargebackRate|Description')
_('ChargebackRate|Guid')
_('ChargebackRate|Rate type')
_('ChargebackRate|Updated on')
_('Chargeback rate detail')
_('ChargebackRateDetail|Created on')
_('ChargebackRateDetail|Description')
_('ChargebackRateDetail|Enabled')
_('ChargebackRateDetail|Friendly rate')
_('ChargebackRateDetail|Group')
_('ChargebackRateDetail|Metric')
_('ChargebackRateDetail|Per time')
_('ChargebackRateDetail|Per unit')
_('ChargebackRateDetail|Rate')
_('ChargebackRateDetail|Source')
_('ChargebackRateDetail|Updated on')
_('Classification')
_('Classification|Default')
_('Classification|Description')
_('Classification|Example text')
_('Classification|Icon')
_('Classification|Perf by tag')
_('Classification|Read only')
_('Classification|Show')
_('Classification|Single value')
_('Classification|Syntax')
_('Cloud network')
_('CloudNetwork|Cidr')
_('CloudNetwork|Ems ref')
_('CloudNetwork|Enabled')
_('CloudNetwork|External facing')
_('CloudNetwork|Name')
_('CloudNetwork|Status')
_('Cloud object store container')
_('CloudObjectStoreContainer|Bytes')
_('CloudObjectStoreContainer|Ems ref')
_('CloudObjectStoreContainer|Key')
_('CloudObjectStoreContainer|Object count')
_('Cloud object store object')
_('CloudObjectStoreObject|Content length')
_('CloudObjectStoreObject|Content type')
_('CloudObjectStoreObject|Ems ref')
_('CloudObjectStoreObject|Etag')
_('CloudObjectStoreObject|Key')
_('CloudObjectStoreObject|Last modified')
_('Cloud resource quota')
_('CloudResourceQuota|Ems ref')
_('CloudResourceQuota|Name')
_('CloudResourceQuota|Service name')
_('CloudResourceQuota|Value')
_('Cloud subnet')
_('CloudSubnet|Cidr')
_('CloudSubnet|Dhcp enabled')
_('CloudSubnet|Ems ref')
_('CloudSubnet|Gateway')
_('CloudSubnet|Name')
_('CloudSubnet|Network protocol')
_('CloudSubnet|Status')
_('Cloud tenant')
_('CloudTenant|Description')
_('CloudTenant|Ems ref')
_('CloudTenant|Enabled')
_('CloudTenant|Name')
_('Cloud volume')
_('CloudVolume|Bootable')
_('CloudVolume|Creation time')
_('CloudVolume|Description')
_('CloudVolume|Ems ref')
_('CloudVolume|Name')
_('CloudVolume|Size')
_('CloudVolume|Status')
_('CloudVolume|Volume type')
_('Cloud volume snapshot')
_('CloudVolumeSnapshot|Creation time')
_('CloudVolumeSnapshot|Description')
_('CloudVolumeSnapshot|Ems ref')
_('CloudVolumeSnapshot|Name')
_('CloudVolumeSnapshot|Size')
_('CloudVolumeSnapshot|Status')
_('Compliance')
_('Compliance|Compliant')
_('Compliance|Event type')
_('Compliance|Resource type')
_('Compliance|Timestamp')
_('Compliance|Updated on')
_('Compliance detail')
_('ComplianceDetail|Condition desc')
_('ComplianceDetail|Condition result')
_('ComplianceDetail|Created on')
_('ComplianceDetail|Miq policy desc')
_('ComplianceDetail|Miq policy result')
_('ComplianceDetail|Updated on')
_('Condition')
_('Condition|Applies to exp')
_('Condition|Created on')
_('Condition|Description')
_('Condition|Expression')
_('Condition|File mtime')
_('Condition|Filename')
_('Condition|Guid')
_('Condition|Modifier')
_('Condition|Name')
_('Condition|Notes')
_('Condition|Towhat')
_('Condition|Updated on')
_('Condition set')
_('ConditionSet|Created on')
_('ConditionSet|Description')
_('ConditionSet|Guid')
_('ConditionSet|Mode')
_('ConditionSet|Name')
_('ConditionSet|Owner type')
_('ConditionSet|Read only')
_('ConditionSet|Set data')
_('ConditionSet|Set type')
_('ConditionSet|Updated on')
_('ConditionSet|Userid')
_('Configuration')
_('Configuration|Created on')
_('Configuration|Settings')
_('Configuration|Typ')
_('Configuration|Updated on')
_('Custom attribute')
_('CustomAttribute|Name')
_('CustomAttribute|Resource type')
_('CustomAttribute|Section')
_('CustomAttribute|Source')
_('CustomAttribute|Value')
_('Custom button')
_('CustomButton|Applies to class')
_('CustomButton|Applies to exp')
_('CustomButton|Created on')
_('CustomButton|Description')
_('CustomButton|Guid')
_('CustomButton|Name')
_('CustomButton|Options')
_('CustomButton|Updated on')
_('CustomButton|Userid')
_('CustomButton|Visibility')
_('CustomButton|Wait for complete')
_('Custom button set')
_('CustomButtonSet|Created on')
_('CustomButtonSet|Description')
_('CustomButtonSet|Guid')
_('CustomButtonSet|Mode')
_('CustomButtonSet|Name')
_('CustomButtonSet|Owner type')
_('CustomButtonSet|Read only')
_('CustomButtonSet|Set data')
_('CustomButtonSet|Set type')
_('CustomButtonSet|Updated on')
_('CustomButtonSet|Userid')
_('Customization spec')
_('CustomizationSpec|Description')
_('CustomizationSpec|Last update time')
_('CustomizationSpec|Name')
_('CustomizationSpec|Spec')
_('CustomizationSpec|Typ')
_('Customization template')
_('CustomizationTemplate|Description')
_('CustomizationTemplate|Name')
_('CustomizationTemplate|Script')
_('CustomizationTemplate|System')
_('Database backup')
_('DatabaseBackup|Name')
_('Dialog')
_('Dialog|Buttons')
_('Dialog|Description')
_('Dialog|Label')
_('Dialog field')
_('DialogField|Data type')
_('DialogField|Default value')
_('DialogField|Description')
_('DialogField|Display')
_('DialogField|Display method')
_('DialogField|Display method options')
_('DialogField|Dynamic')
_('DialogField|Label')
_('DialogField|Name')
_('DialogField|Notes')
_('DialogField|Notes display')
_('DialogField|Options')
_('DialogField|Position')
_('DialogField|Reconfigurable')
_('DialogField|Required')
_('DialogField|Required method')
_('DialogField|Required method options')
_('DialogField|Validator rule')
_('DialogField|Validator type')
_('DialogField|Values')
_('DialogField|Values method')
_('DialogField|Values method options')
_('Dialog group')
_('DialogGroup|Description')
_('DialogGroup|Display')
_('DialogGroup|Display method')
_('DialogGroup|Display method options')
_('DialogGroup|Label')
_('DialogGroup|Position')
_('Dialog tab')
_('DialogTab|Description')
_('DialogTab|Display')
_('DialogTab|Display method')
_('DialogTab|Display method options')
_('DialogTab|Label')
_('DialogTab|Position')
_('Disk')
_('Disk|Auto detect')
_('Disk|Backing type')
_('Disk|Controller type')
_('Disk|Created on')
_('Disk|Device name')
_('Disk|Device type')
_('Disk|Disk type')
_('Disk|Filename')
_('Disk|Free space')
_('Disk|Location')
_('Disk|Mode')
_('Disk|Present')
_('Disk|Size')
_('Disk|Size on disk')
_('Disk|Start connected')
_('Disk|Updated on')
_('Drift state')
_('DriftState|Data')
_('DriftState|Resource type')
_('DriftState|Timestamp')
_('Ems cluster')
_('EmsCluster|Created on')
_('EmsCluster|Drs automation level')
_('EmsCluster|Drs enabled')
_('EmsCluster|Drs migration threshold')
_('EmsCluster|Effective cpu')
_('EmsCluster|Effective memory')
_('EmsCluster|Ems ref')
_('EmsCluster|Ems ref obj')
_('EmsCluster|Ha admit control')
_('EmsCluster|Ha enabled')
_('EmsCluster|Ha max failures')
_('EmsCluster|Last perf capture on')
_('EmsCluster|Name')
_('EmsCluster|Uid ems')
_('EmsCluster|Updated on')
_('Ems event')
_('EmsEvent|Created on')
_('EmsEvent|Dest ems cluster name')
_('EmsEvent|Dest ems cluster uid')
_('EmsEvent|Dest host name')
_('EmsEvent|Dest vm location')
_('EmsEvent|Dest vm name')
_('EmsEvent|Ems cluster name')
_('EmsEvent|Ems cluster uid')
_('EmsEvent|Event type')
_('EmsEvent|Full data')
_('EmsEvent|Host name')
_('EmsEvent|Is task')
_('EmsEvent|Message')
_('EmsEvent|Source')
_('EmsEvent|Timestamp')
_('EmsEvent|Username')
_('EmsEvent|Vm location')
_('EmsEvent|Vm name')
_('Ems folder')
_('EmsFolder|Created on')
_('EmsFolder|Ems ref')
_('EmsFolder|Ems ref obj')
_('EmsFolder|Is datacenter')
_('EmsFolder|Name')
_('EmsFolder|Uid ems')
_('EmsFolder|Updated on')
_('Event log')
_('EventLog|Category')
_('EventLog|Computer name')
_('EventLog|Generated')
_('EventLog|Level')
_('EventLog|Message')
_('EventLog|Name')
_('EventLog|Source')
_('EventLog|Uid')
_('Ext management system')
_('ExtManagementSystem|Api version')
_('ExtManagementSystem|Created on')
_('ExtManagementSystem|Guid')
_('ExtManagementSystem|Host default vnc port end')
_('ExtManagementSystem|Host default vnc port start')
_('ExtManagementSystem|Hostname')
_('ExtManagementSystem|Ipaddress')
_('ExtManagementSystem|Name')
_('ExtManagementSystem|Port')
_('ExtManagementSystem|Provider region')
_('ExtManagementSystem|Uid ems')
_('ExtManagementSystem|Updated on')
_('File depot')
_('FileDepot|Name')
_('FileDepot|Resource type')
_('FileDepot|Support case')
_('FileDepot|Uri')
_('Filesystem')
_('Filesystem|Atime')
_('Filesystem|Base name')
_('Filesystem|Created on')
_('Filesystem|Ctime')
_('Filesystem|File version')
_('Filesystem|File version header')
_('Filesystem|Group')
_('Filesystem|Md5')
_('Filesystem|Mtime')
_('Filesystem|Name')
_('Filesystem|Owner')
_('Filesystem|Permissions')
_('Filesystem|Product version')
_('Filesystem|Product version header')
_('Filesystem|Resource type')
_('Filesystem|Rsc type')
_('Filesystem|Size')
_('Filesystem|Updated on')
_('Firewall rule')
_('FirewallRule|Created on')
_('FirewallRule|Direction')
_('FirewallRule|Display name')
_('FirewallRule|Ems ref')
_('FirewallRule|Enabled')
_('FirewallRule|End port')
_('FirewallRule|Group')
_('FirewallRule|Host protocol')
_('FirewallRule|Name')
_('FirewallRule|Network protocol')
_('FirewallRule|Port')
_('FirewallRule|Required')
_('FirewallRule|Resource type')
_('FirewallRule|Source ip range')
_('FirewallRule|Updated on')
_('Flavor')
_('Flavor|Block storage based only')
_('Flavor|Cpu cores')
_('Flavor|Cpus')
_('Flavor|Description')
_('Flavor|Ems ref')
_('Flavor|Enabled')
_('Flavor|Memory')
_('Flavor|Name')
_('Flavor|Supports 32 bit')
_('Flavor|Supports 64 bit')
_('Flavor|Supports hvm')
_('Flavor|Supports paravirtual')
_('Floating ip')
_('FloatingIp|Address')
_('FloatingIp|Cloud network only')
_('FloatingIp|Ems ref')
_('Guest application')
_('GuestApplication|Arch')
_('GuestApplication|Description')
_('GuestApplication|Language')
_('GuestApplication|Name')
_('GuestApplication|Package name')
_('GuestApplication|Path')
_('GuestApplication|Product icon')
_('GuestApplication|Product key')
_('GuestApplication|Release')
_('GuestApplication|Transform')
_('GuestApplication|Typename')
_('GuestApplication|Vendor')
_('GuestApplication|Version')
_('Guest device')
_('GuestDevice|Address')
_('GuestDevice|Auto detect')
_('GuestDevice|Chap auth enabled')
_('GuestDevice|Controller type')
_('GuestDevice|Device name')
_('GuestDevice|Device type')
_('GuestDevice|Filename')
_('GuestDevice|Free space')
_('GuestDevice|Iscsi alias')
_('GuestDevice|Iscsi name')
_('GuestDevice|Location')
_('GuestDevice|Mode')
_('GuestDevice|Model')
_('GuestDevice|Present')
_('GuestDevice|Size')
_('GuestDevice|Size on disk')
_('GuestDevice|Start connected')
_('GuestDevice|Uid ems')
_('Hardware')
_('Hardware|Annotation')
_('Hardware|Bios')
_('Hardware|Bios location')
_('Hardware|Bitness')
_('Hardware|Config version')
_('Hardware|Cores per socket')
_('Hardware|Cpu speed')
_('Hardware|Cpu type')
_('Hardware|Cpu usage')
_('Hardware|Disk capacity')
_('Hardware|Disk free space')
_('Hardware|Guest os')
_('Hardware|Guest os full name')
_('Hardware|Logical cpus')
_('Hardware|Manufacturer')
_('Hardware|Memory console')
_('Hardware|Memory cpu')
_('Hardware|Memory usage')
_('Hardware|Model')
_('Hardware|Number of nics')
_('Hardware|Numvcpus')
_('Hardware|Root device type')
_('Hardware|Size on disk')
_('Hardware|Time sync')
_('Hardware|Virtual hw version')
_('Hardware|Virtualization type')
_('Hardware|Vmotion enabled')
_('Host')
_('Host|Admin disabled')
_('Host|Asset tag')
_('Host|Connection state')
_('Host|Created on')
_('Host|Ems ref')
_('Host|Ems ref obj')
_('Host|Failover')
_('Host|Guid')
_('Host|Hostname')
_('Host|Hyperthreading')
_('Host|Ipaddress')
_('Host|Ipmi address')
_('Host|Last perf capture on')
_('Host|Mac address')
_('Host|Name')
_('Host|Next available vnc port')
_('Host|Power state')
_('Host|Service tag')
_('Host|Settings')
_('Host|Smart')
_('Host|Ssh permit root login')
_('Host|Uid ems')
_('Host|Updated on')
_('Host|User assigned os')
_('Host|Vmm buildnumber')
_('Host|Vmm product')
_('Host|Vmm vendor')
_('Host|Vmm version')
_('Iso datastore')
_('IsoDatastore|Last refresh on')
_('Iso image')
_('IsoImage|Name')
_('Job')
_('Job|Agent class')
_('Job|Agent message')
_('Job|Agent name')
_('Job|Agent state')
_('Job|Archive')
_('Job|Code')
_('Job|Context')
_('Job|Created on')
_('Job|Dispatch status')
_('Job|Guid')
_('Job|Message')
_('Job|Name')
_('Job|Options')
_('Job|Process')
_('Job|Started on')
_('Job|State')
_('Job|Status')
_('Job|Sync key')
_('Job|Target class')
_('Job|Updated on')
_('Job|Userid')
_('Job|Zone')
_('Lan')
_('Lan|Allow promiscuous')
_('Lan|Computed allow promiscuous')
_('Lan|Computed forged transmits')
_('Lan|Computed mac changes')
_('Lan|Created on')
_('Lan|Forged transmits')
_('Lan|Mac changes')
_('Lan|Name')
_('Lan|Tag')
_('Lan|Uid ems')
_('Lan|Updated on')
_('Ldap domain')
_('LdapDomain|Base dn')
_('LdapDomain|Bind timeout')
_('LdapDomain|Follow referrals')
_('LdapDomain|Get direct groups')
_('LdapDomain|Get roles from home forest')
_('LdapDomain|Get user groups')
_('LdapDomain|Group membership max depth')
_('LdapDomain|Last group sync')
_('LdapDomain|Last user sync')
_('LdapDomain|Name')
_('LdapDomain|Search timeout')
_('LdapDomain|User suffix')
_('LdapDomain|User type')
_('Ldap group')
_('LdapGroup|Display name')
_('LdapGroup|Dn')
_('LdapGroup|Mail')
_('LdapGroup|Whenchanged')
_('LdapGroup|Whencreated')
_('Ldap region')
_('LdapRegion|Description')
_('LdapRegion|Name')
_('Ldap server')
_('LdapServer|Hostname')
_('LdapServer|Mode')
_('LdapServer|Port')
_('Ldap user')
_('LdapUser|Address')
_('LdapUser|City')
_('LdapUser|Company')
_('LdapUser|Country')
_('LdapUser|Department')
_('LdapUser|Display name')
_('LdapUser|Dn')
_('LdapUser|Fax')
_('LdapUser|First name')
_('LdapUser|Last name')
_('LdapUser|Mail')
_('LdapUser|Office')
_('LdapUser|Phone')
_('LdapUser|Phone home')
_('LdapUser|Phone mobile')
_('LdapUser|Sam account name')
_('LdapUser|Sid')
_('LdapUser|State')
_('LdapUser|Title')
_('LdapUser|Upn')
_('LdapUser|Whenchanged')
_('LdapUser|Whencreated')
_('LdapUser|Zip')
_('Lifecycle event')
_('LifecycleEvent|Created by')
_('LifecycleEvent|Created on')
_('LifecycleEvent|Event')
_('LifecycleEvent|Guid')
_('LifecycleEvent|Location')
_('LifecycleEvent|Message')
_('LifecycleEvent|Status')
_('Log file')
_('LogFile|Created on')
_('LogFile|Description')
_('LogFile|Historical')
_('LogFile|Local file')
_('LogFile|Log uri')
_('LogFile|Logging ended on')
_('LogFile|Logging started on')
_('LogFile|Name')
_('LogFile|Resource type')
_('LogFile|State')
_('LogFile|Updated on')
_('Metric')
_('Metric|Assoc ids')
_('Metric|Capture interval')
_('Metric|Capture interval name')
_('Metric|Cpu ready delta summation')
_('Metric|Cpu system delta summation')
_('Metric|Cpu usage rate average')
_('Metric|Cpu usagemhz rate average')
_('Metric|Cpu used delta summation')
_('Metric|Cpu wait delta summation')
_('Metric|Created on')
_('Metric|Derived cpu available')
_('Metric|Derived cpu reserved')
_('Metric|Derived host count off')
_('Metric|Derived host count on')
_('Metric|Derived memory available')
_('Metric|Derived memory reserved')
_('Metric|Derived memory used')
_('Metric|Derived storage disk managed')
_('Metric|Derived storage disk registered')
_('Metric|Derived storage disk unmanaged')
_('Metric|Derived storage disk unregistered')
_('Metric|Derived storage free')
_('Metric|Derived storage mem managed')
_('Metric|Derived storage mem registered')
_('Metric|Derived storage mem unmanaged')
_('Metric|Derived storage mem unregistered')
_('Metric|Derived storage snapshot managed')
_('Metric|Derived storage snapshot registered')
_('Metric|Derived storage snapshot unmanaged')
_('Metric|Derived storage snapshot unregistered')
_('Metric|Derived storage total')
_('Metric|Derived storage used managed')
_('Metric|Derived storage used registered')
_('Metric|Derived storage used unmanaged')
_('Metric|Derived storage used unregistered')
_('Metric|Derived storage vm count managed')
_('Metric|Derived storage vm count registered')
_('Metric|Derived storage vm count unmanaged')
_('Metric|Derived storage vm count unregistered')
_('Metric|Derived vm allocated disk storage')
_('Metric|Derived vm count off')
_('Metric|Derived vm count on')
_('Metric|Derived vm numvcpus')
_('Metric|Derived vm used disk storage')
_('Metric|Disk devicelatency absolute average')
_('Metric|Disk kernellatency absolute average')
_('Metric|Disk queuelatency absolute average')
_('Metric|Disk usage rate average')
_('Metric|Intervals in rollup')
_('Metric|Mem swapin absolute average')
_('Metric|Mem swapout absolute average')
_('Metric|Mem swapped absolute average')
_('Metric|Mem swaptarget absolute average')
_('Metric|Mem usage absolute average')
_('Metric|Mem vmmemctl absolute average')
_('Metric|Mem vmmemctltarget absolute average')
_('Metric|Min max')
_('Metric|Net usage rate average')
_('Metric|Resource name')
_('Metric|Resource type')
_('Metric|Sys uptime absolute latest')
_('Metric|Tag names')
_('Metric|Timestamp')
_('Metric rollup')
_('MetricRollup|Assoc ids')
_('MetricRollup|Capture interval')
_('MetricRollup|Capture interval name')
_('MetricRollup|Cpu ready delta summation')
_('MetricRollup|Cpu system delta summation')
_('MetricRollup|Cpu usage rate average')
_('MetricRollup|Cpu usagemhz rate average')
_('MetricRollup|Cpu used delta summation')
_('MetricRollup|Cpu wait delta summation')
_('MetricRollup|Created on')
_('MetricRollup|Derived cpu available')
_('MetricRollup|Derived cpu reserved')
_('MetricRollup|Derived host count off')
_('MetricRollup|Derived host count on')
_('MetricRollup|Derived memory available')
_('MetricRollup|Derived memory reserved')
_('MetricRollup|Derived memory used')
_('MetricRollup|Derived storage disk managed')
_('MetricRollup|Derived storage disk registered')
_('MetricRollup|Derived storage disk unmanaged')
_('MetricRollup|Derived storage disk unregistered')
_('MetricRollup|Derived storage free')
_('MetricRollup|Derived storage mem managed')
_('MetricRollup|Derived storage mem registered')
_('MetricRollup|Derived storage mem unmanaged')
_('MetricRollup|Derived storage mem unregistered')
_('MetricRollup|Derived storage snapshot managed')
_('MetricRollup|Derived storage snapshot registered')
_('MetricRollup|Derived storage snapshot unmanaged')
_('MetricRollup|Derived storage snapshot unregistered')
_('MetricRollup|Derived storage total')
_('MetricRollup|Derived storage used managed')
_('MetricRollup|Derived storage used registered')
_('MetricRollup|Derived storage used unmanaged')
_('MetricRollup|Derived storage used unregistered')
_('MetricRollup|Derived storage vm count managed')
_('MetricRollup|Derived storage vm count registered')
_('MetricRollup|Derived storage vm count unmanaged')
_('MetricRollup|Derived storage vm count unregistered')
_('MetricRollup|Derived vm allocated disk storage')
_('MetricRollup|Derived vm count off')
_('MetricRollup|Derived vm count on')
_('MetricRollup|Derived vm numvcpus')
_('MetricRollup|Derived vm used disk storage')
_('MetricRollup|Disk devicelatency absolute average')
_('MetricRollup|Disk kernellatency absolute average')
_('MetricRollup|Disk queuelatency absolute average')
_('MetricRollup|Disk usage rate average')
_('MetricRollup|Intervals in rollup')
_('MetricRollup|Mem swapin absolute average')
_('MetricRollup|Mem swapout absolute average')
_('MetricRollup|Mem swapped absolute average')
_('MetricRollup|Mem swaptarget absolute average')
_('MetricRollup|Mem usage absolute average')
_('MetricRollup|Mem vmmemctl absolute average')
_('MetricRollup|Mem vmmemctltarget absolute average')
_('MetricRollup|Min max')
_('MetricRollup|Net usage rate average')
_('MetricRollup|Resource name')
_('MetricRollup|Resource type')
_('MetricRollup|Sys uptime absolute latest')
_('MetricRollup|Tag names')
_('MetricRollup|Timestamp')
_('Miq action')
_('MiqAction|Action type')
_('MiqAction|Created on')
_('MiqAction|Description')
_('MiqAction|Guid')
_('MiqAction|Name')
_('MiqAction|Options')
_('MiqAction|Updated on')
_('Miq action set')
_('MiqActionSet|Created on')
_('MiqActionSet|Description')
_('MiqActionSet|Guid')
_('MiqActionSet|Mode')
_('MiqActionSet|Name')
_('MiqActionSet|Owner type')
_('MiqActionSet|Read only')
_('MiqActionSet|Set data')
_('MiqActionSet|Set type')
_('MiqActionSet|Updated on')
_('MiqActionSet|Userid')
_('Miq ae class')
_('MiqAeClass|Created on')
_('MiqAeClass|Description')
_('MiqAeClass|Display name')
_('MiqAeClass|Inherits')
_('MiqAeClass|Name')
_('MiqAeClass|Owner')
_('MiqAeClass|Updated by')
_('MiqAeClass|Updated on')
_('MiqAeClass|Visibility')
_('Miq ae engine/miq ae workspace')
_('MiqAeEngine::MiqAeWorkspace|Created on')
_('MiqAeEngine::MiqAeWorkspace|Guid')
_('MiqAeEngine::MiqAeWorkspace|Setters')
_('MiqAeEngine::MiqAeWorkspace|Updated on')
_('MiqAeEngine::MiqAeWorkspace|Uri')
_('MiqAeEngine::MiqAeWorkspace|Workspace')
_('Miq ae field')
_('MiqAeField|Aetype')
_('MiqAeField|Collect')
_('MiqAeField|Condition')
_('MiqAeField|Created on')
_('MiqAeField|Datatype')
_('MiqAeField|Default value')
_('MiqAeField|Description')
_('MiqAeField|Display name')
_('MiqAeField|Max retries')
_('MiqAeField|Max time')
_('MiqAeField|Message')
_('MiqAeField|Name')
_('MiqAeField|On entry')
_('MiqAeField|On error')
_('MiqAeField|On exit')
_('MiqAeField|Owner')
_('MiqAeField|Priority')
_('MiqAeField|Scope')
_('MiqAeField|Substitute')
_('MiqAeField|Updated by')
_('MiqAeField|Updated on')
_('MiqAeField|Visibility')
_('Miq ae instance')
_('MiqAeInstance|Created on')
_('MiqAeInstance|Description')
_('MiqAeInstance|Display name')
_('MiqAeInstance|Inherits')
_('MiqAeInstance|Name')
_('MiqAeInstance|Updated by')
_('MiqAeInstance|Updated on')
_('Miq ae method')
_('MiqAeMethod|Created on')
_('MiqAeMethod|Data')
_('MiqAeMethod|Description')
_('MiqAeMethod|Display name')
_('MiqAeMethod|Language')
_('MiqAeMethod|Location')
_('MiqAeMethod|Name')
_('MiqAeMethod|Scope')
_('MiqAeMethod|Updated by')
_('MiqAeMethod|Updated on')
_('Miq ae namespace')
_('MiqAeNamespace|Created on')
_('MiqAeNamespace|Description')
_('MiqAeNamespace|Display name')
_('MiqAeNamespace|Enabled')
_('MiqAeNamespace|Name')
_('MiqAeNamespace|Priority')
_('MiqAeNamespace|System')
_('MiqAeNamespace|Updated by')
_('MiqAeNamespace|Updated on')
_('Miq ae value')
_('MiqAeValue|Collect')
_('MiqAeValue|Condition')
_('MiqAeValue|Created on')
_('MiqAeValue|Display name')
_('MiqAeValue|Max retries')
_('MiqAeValue|Max time')
_('MiqAeValue|On entry')
_('MiqAeValue|On error')
_('MiqAeValue|On exit')
_('MiqAeValue|Updated by')
_('MiqAeValue|Updated on')
_('MiqAeValue|Value')
_('Miq alert')
_('MiqAlert|Created on')
_('MiqAlert|Db')
_('MiqAlert|Description')
_('MiqAlert|Enabled')
_('MiqAlert|Expression')
_('MiqAlert|Guid')
_('MiqAlert|Options')
_('MiqAlert|Responds to events')
_('MiqAlert|Updated on')
_('Miq alert set')
_('MiqAlertSet|Created on')
_('MiqAlertSet|Description')
_('MiqAlertSet|Guid')
_('MiqAlertSet|Mode')
_('MiqAlertSet|Name')
_('MiqAlertSet|Owner type')
_('MiqAlertSet|Read only')
_('MiqAlertSet|Set data')
_('MiqAlertSet|Set type')
_('MiqAlertSet|Updated on')
_('MiqAlertSet|Userid')
_('Miq alert status')
_('MiqAlertStatus|Evaluated on')
_('MiqAlertStatus|Resource type')
_('MiqAlertStatus|Result')
_('Miq approval')
_('MiqApproval|Approver name')
_('MiqApproval|Approver type')
_('MiqApproval|Created on')
_('MiqApproval|Description')
_('MiqApproval|Reason')
_('MiqApproval|Stamped on')
_('MiqApproval|Stamper name')
_('MiqApproval|State')
_('MiqApproval|Updated on')
_('Miq cim association')
_('MiqCimAssociation|Assoc class')
_('MiqCimAssociation|Obj name')
_('MiqCimAssociation|Result class')
_('MiqCimAssociation|Result obj name')
_('MiqCimAssociation|Result role')
_('MiqCimAssociation|Role')
_('MiqCimAssociation|Status')
_('Miq cim derived metric')
_('MiqCimDerivedMetric|Avg read size')
_('MiqCimDerivedMetric|Avg write size')
_('MiqCimDerivedMetric|Interval')
_('MiqCimDerivedMetric|K bytes read per sec')
_('MiqCimDerivedMetric|K bytes transferred per sec')
_('MiqCimDerivedMetric|K bytes written per sec')
_('MiqCimDerivedMetric|Pct hit')
_('MiqCimDerivedMetric|Pct read')
_('MiqCimDerivedMetric|Pct write')
_('MiqCimDerivedMetric|Queue depth')
_('MiqCimDerivedMetric|Read hit ios per sec')
_('MiqCimDerivedMetric|Read ios per sec')
_('MiqCimDerivedMetric|Response time sec')
_('MiqCimDerivedMetric|Service time sec')
_('MiqCimDerivedMetric|Statistic time')
_('MiqCimDerivedMetric|Total ios per sec')
_('MiqCimDerivedMetric|Utilization')
_('MiqCimDerivedMetric|Wait time sec')
_('MiqCimDerivedMetric|Write hit ios per sec')
_('MiqCimDerivedMetric|Write ios per sec')
_('Miq cim instance')
_('MiqCimInstance|Class hier')
_('MiqCimInstance|Class name')
_('MiqCimInstance|Is top managed element')
_('MiqCimInstance|Last update status')
_('MiqCimInstance|Namespace')
_('MiqCimInstance|Obj')
_('MiqCimInstance|Obj name')
_('MiqCimInstance|Obj name str')
_('MiqCimInstance|Source')
_('MiqCimInstance|Type spec obj')
_('MiqCimInstance|Vmdb obj type')
_('Miq database')
_('MiqDatabase|Cfme version available')
_('MiqDatabase|Csrf secret token')
_('MiqDatabase|Last replication count')
_('MiqDatabase|Postgres update available')
_('MiqDatabase|Registration http proxy server')
_('MiqDatabase|Registration organization')
_('MiqDatabase|Registration server')
_('MiqDatabase|Registration type')
_('MiqDatabase|Session secret token')
_('MiqDatabase|Update repo name')
_('Miq dialog')
_('MiqDialog|Content')
_('MiqDialog|Default')
_('MiqDialog|Description')
_('MiqDialog|Dialog type')
_('MiqDialog|File mtime')
_('MiqDialog|Filename')
_('MiqDialog|Name')
_('Miq enterprise')
_('MiqEnterprise|Created on')
_('MiqEnterprise|Description')
_('MiqEnterprise|Name')
_('MiqEnterprise|Settings')
_('MiqEnterprise|Updated on')
_('Miq event')
_('MiqEvent|Created on')
_('MiqEvent|Default')
_('MiqEvent|Definition')
_('MiqEvent|Description')
_('MiqEvent|Enabled')
_('MiqEvent|Event type')
_('MiqEvent|Guid')
_('MiqEvent|Name')
_('MiqEvent|Updated on')
_('Miq event set')
_('MiqEventSet|Created on')
_('MiqEventSet|Description')
_('MiqEventSet|Guid')
_('MiqEventSet|Mode')
_('MiqEventSet|Name')
_('MiqEventSet|Owner type')
_('MiqEventSet|Read only')
_('MiqEventSet|Set data')
_('MiqEventSet|Set type')
_('MiqEventSet|Updated on')
_('MiqEventSet|Userid')
_('Miq group')
_('MiqGroup|Created on')
_('MiqGroup|Description')
_('MiqGroup|Filters')
_('MiqGroup|Group type')
_('MiqGroup|Guid')
_('MiqGroup|Resource type')
_('MiqGroup|Sequence')
_('MiqGroup|Settings')
_('MiqGroup|Updated on')
_('Miq policy')
_('MiqPolicy|Active')
_('MiqPolicy|Created by')
_('MiqPolicy|Created on')
_('MiqPolicy|Description')
_('MiqPolicy|Expression')
_('MiqPolicy|Guid')
_('MiqPolicy|Mode')
_('MiqPolicy|Name')
_('MiqPolicy|Notes')
_('MiqPolicy|Towhat')
_('MiqPolicy|Updated by')
_('MiqPolicy|Updated on')
_('Miq policy content')
_('MiqPolicyContent|Created on')
_('MiqPolicyContent|Failure sequence')
_('MiqPolicyContent|Failure synchronous')
_('MiqPolicyContent|Qualifier')
_('MiqPolicyContent|Success sequence')
_('MiqPolicyContent|Success synchronous')
_('MiqPolicyContent|Updated on')
_('Miq policy set')
_('MiqPolicySet|Created on')
_('MiqPolicySet|Description')
_('MiqPolicySet|Guid')
_('MiqPolicySet|Mode')
_('MiqPolicySet|Name')
_('MiqPolicySet|Owner type')
_('MiqPolicySet|Read only')
_('MiqPolicySet|Set data')
_('MiqPolicySet|Set type')
_('MiqPolicySet|Updated on')
_('MiqPolicySet|Userid')
_('Miq product feature')
_('MiqProductFeature|Description')
_('MiqProductFeature|Feature type')
_('MiqProductFeature|Hidden')
_('MiqProductFeature|Identifier')
_('MiqProductFeature|Name')
_('MiqProductFeature|Protected')
_('Miq proxy')
_('MiqProxy|Capabilities')
_('MiqProxy|Created on')
_('MiqProxy|Guid')
_('MiqProxy|Last heartbeat')
_('MiqProxy|Name')
_('MiqProxy|Power state')
_('MiqProxy|Remote config')
_('MiqProxy|Settings')
_('MiqProxy|Updated on')
_('MiqProxy|Upgrade message')
_('MiqProxy|Upgrade settings')
_('MiqProxy|Upgrade status')
_('MiqProxy|Version')
_('MiqProxy|Ws port')
_('Miq queue')
_('MiqQueue|Args')
_('MiqQueue|Class name')
_('MiqQueue|Created on')
_('MiqQueue|Deliver on')
_('MiqQueue|Expires on')
_('MiqQueue|For user')
_('MiqQueue|Handler type')
_('MiqQueue|Lock version')
_('MiqQueue|Method name')
_('MiqQueue|Miq callback')
_('MiqQueue|Msg data')
_('MiqQueue|Msg timeout')
_('MiqQueue|Priority')
_('MiqQueue|Queue name')
_('MiqQueue|Role')
_('MiqQueue|Server guid')
_('MiqQueue|State')
_('MiqQueue|Updated on')
_('MiqQueue|Zone')
_('Miq region')
_('MiqRegion|Description')
_('MiqRegion|Guid')
_('MiqRegion|Region')
_('Miq report')
_('MiqReport|Categories')
_('MiqReport|Col formats')
_('MiqReport|Col options')
_('MiqReport|Col order')
_('MiqReport|Cols')
_('MiqReport|Conditions')
_('MiqReport|Created on')
_('MiqReport|Db')
_('MiqReport|Db options')
_('MiqReport|Dims')
_('MiqReport|Display filter')
_('MiqReport|File mtime')
_('MiqReport|Filename')
_('MiqReport|Generate cols')
_('MiqReport|Generate rows')
_('MiqReport|Graph')
_('MiqReport|Group')
_('MiqReport|Headers')
_('MiqReport|Include')
_('MiqReport|Name')
_('MiqReport|Order')
_('MiqReport|Priority')
_('MiqReport|Rpt group')
_('MiqReport|Rpt options')
_('MiqReport|Rpt type')
_('MiqReport|Sortby')
_('MiqReport|Template type')
_('MiqReport|Timeline')
_('MiqReport|Title')
_('MiqReport|Tz')
_('MiqReport|Updated on')
_('MiqReport|Where clause')
_('Miq report result')
_('MiqReportResult|Created on')
_('MiqReportResult|Db')
_('MiqReportResult|Last accessed on')
_('MiqReportResult|Last run on')
_('MiqReportResult|Name')
_('MiqReportResult|Report')
_('MiqReportResult|Report rows per detail row')
_('MiqReportResult|Report source')
_('MiqReportResult|Scheduled on')
_('MiqReportResult|Userid')
_('Miq report result detail')
_('MiqReportResultDetail|Data')
_('MiqReportResultDetail|Data type')
_('Miq request')
_('MiqRequest|Approval state')
_('MiqRequest|Created on')
_('MiqRequest|Description')
_('MiqRequest|Destination type')
_('MiqRequest|Fulfilled on')
_('MiqRequest|Message')
_('MiqRequest|Options')
_('MiqRequest|Request state')
_('MiqRequest|Request type')
_('MiqRequest|Requester name')
_('MiqRequest|Source type')
_('MiqRequest|Status')
_('MiqRequest|Updated on')
_('MiqRequest|Userid')
_('Miq request task')
_('MiqRequestTask|Created on')
_('MiqRequestTask|Description')
_('MiqRequestTask|Destination type')
_('MiqRequestTask|Message')
_('MiqRequestTask|Options')
_('MiqRequestTask|Phase')
_('MiqRequestTask|Phase context')
_('MiqRequestTask|Request type')
_('MiqRequestTask|Source type')
_('MiqRequestTask|State')
_('MiqRequestTask|Status')
_('MiqRequestTask|Updated on')
_('MiqRequestTask|Userid')
_('Miq schedule')
_('MiqSchedule|Adhoc')
_('MiqSchedule|Created on')
_('MiqSchedule|Description')
_('MiqSchedule|Enabled')
_('MiqSchedule|Filter')
_('MiqSchedule|Last run on')
_('MiqSchedule|Name')
_('MiqSchedule|Prod default')
_('MiqSchedule|Run at')
_('MiqSchedule|Sched action')
_('MiqSchedule|Towhat')
_('MiqSchedule|Userid')
_('Miq scsi lun')
_('MiqScsiLun|Block')
_('MiqScsiLun|Block size')
_('MiqScsiLun|Canonical name')
_('MiqScsiLun|Capacity')
_('MiqScsiLun|Device name')
_('MiqScsiLun|Device type')
_('MiqScsiLun|Lun')
_('MiqScsiLun|Lun type')
_('MiqScsiLun|Uid ems')
_('Miq scsi target')
_('MiqScsiTarget|Address')
_('MiqScsiTarget|Iscsi alias')
_('MiqScsiTarget|Iscsi name')
_('MiqScsiTarget|Target')
_('MiqScsiTarget|Uid ems')
_('Miq search')
_('MiqSearch|Db')
_('MiqSearch|Description')
_('MiqSearch|Filter')
_('MiqSearch|Name')
_('MiqSearch|Options')
_('MiqSearch|Search key')
_('MiqSearch|Search type')
_('Miq server')
_('MiqServer|Build')
_('MiqServer|Capabilities')
_('MiqServer|Cpu time')
_('MiqServer|Drb uri')
_('MiqServer|Guid')
_('MiqServer|Has active userinterface')
_('MiqServer|Has active webservices')
_('MiqServer|Hostname')
_('MiqServer|Ipaddress')
_('MiqServer|Is master')
_('MiqServer|Last heartbeat')
_('MiqServer|Last update check')
_('MiqServer|Logo')
_('MiqServer|Mac address')
_('MiqServer|Memory size')
_('MiqServer|Memory usage')
_('MiqServer|Name')
_('MiqServer|Os priority')
_('MiqServer|Percent cpu')
_('MiqServer|Percent memory')
_('MiqServer|Pid')
_('MiqServer|Rh registered')
_('MiqServer|Rh subscribed')
_('MiqServer|Rhn mirror')
_('MiqServer|Sql spid')
_('MiqServer|Started on')
_('MiqServer|Status')
_('MiqServer|Stopped on')
_('MiqServer|Updates available')
_('MiqServer|Upgrade message')
_('MiqServer|Upgrade status')
_('MiqServer|Version')
_('Miq shortcut')
_('MiqShortcut|Description')
_('MiqShortcut|Name')
_('MiqShortcut|Rbac feature name')
_('MiqShortcut|Sequence')
_('MiqShortcut|Startup')
_('MiqShortcut|Url')
_('Miq storage metric')
_('MiqStorageMetric|Metric obj')
_('Miq task')
_('MiqTask|Context data')
_('MiqTask|Created on')
_('MiqTask|Identifier')
_('MiqTask|Message')
_('MiqTask|Name')
_('MiqTask|Pct complete')
_('MiqTask|Results')
_('MiqTask|State')
_('MiqTask|Status')
_('MiqTask|Updated on')
_('MiqTask|Userid')
_('Miq user role')
_('MiqUserRole|Name')
_('MiqUserRole|Read only')
_('MiqUserRole|Settings')
_('Miq widget')
_('MiqWidget|Content type')
_('MiqWidget|Description')
_('MiqWidget|Enabled')
_('MiqWidget|Guid')
_('MiqWidget|Last generated content on')
_('MiqWidget|Options')
_('MiqWidget|Read only')
_('MiqWidget|Resource type')
_('MiqWidget|Title')
_('MiqWidget|Visibility')
_('Miq widget content')
_('MiqWidgetContent|Contents')
_('MiqWidgetContent|Timezone')
_('Miq widget set')
_('MiqWidgetSet|Created on')
_('MiqWidgetSet|Description')
_('MiqWidgetSet|Guid')
_('MiqWidgetSet|Mode')
_('MiqWidgetSet|Name')
_('MiqWidgetSet|Owner type')
_('MiqWidgetSet|Read only')
_('MiqWidgetSet|Set data')
_('MiqWidgetSet|Set type')
_('MiqWidgetSet|Updated on')
_('MiqWidgetSet|Userid')
_('Miq widget shortcut')
_('MiqWidgetShortcut|Description')
_('MiqWidgetShortcut|Sequence')
_('Miq worker')
_('MiqWorker|Command line')
_('MiqWorker|Cpu time')
_('MiqWorker|Guid')
_('MiqWorker|Last heartbeat')
_('MiqWorker|Memory size')
_('MiqWorker|Memory usage')
_('MiqWorker|Os priority')
_('MiqWorker|Percent cpu')
_('MiqWorker|Percent memory')
_('MiqWorker|Pid')
_('MiqWorker|Queue name')
_('MiqWorker|Sql spid')
_('MiqWorker|Started on')
_('MiqWorker|Status')
_('MiqWorker|Stopped on')
_('MiqWorker|Uri')
_('Network')
_('Network|Default gateway')
_('Network|Description')
_('Network|Dhcp enabled')
_('Network|Dhcp server')
_('Network|Dns server')
_('Network|Domain')
_('Network|Guid')
_('Network|Hostname')
_('Network|Ipaddress')
_('Network|Ipv6address')
_('Network|Lease expires')
_('Network|Lease obtained')
_('Network|Subnet mask')
_('Ontap aggregate derived metric')
_('OntapAggregateDerivedMetric|Base counters')
_('OntapAggregateDerivedMetric|Cp read blocks')
_('OntapAggregateDerivedMetric|Cp reads')
_('OntapAggregateDerivedMetric|Interval')
_('OntapAggregateDerivedMetric|Statistic time')
_('OntapAggregateDerivedMetric|Total transfers')
_('OntapAggregateDerivedMetric|User read blocks')
_('OntapAggregateDerivedMetric|User reads')
_('OntapAggregateDerivedMetric|User write blocks')
_('OntapAggregateDerivedMetric|User writes')
_('Ontap aggregate metrics rollup')
_('OntapAggregateMetricsRollup|Base counters')
_('OntapAggregateMetricsRollup|Cp read blocks')
_('OntapAggregateMetricsRollup|Cp read blocks max')
_('OntapAggregateMetricsRollup|Cp read blocks min')
_('OntapAggregateMetricsRollup|Cp reads')
_('OntapAggregateMetricsRollup|Cp reads max')
_('OntapAggregateMetricsRollup|Cp reads min')
_('OntapAggregateMetricsRollup|Interval')
_('OntapAggregateMetricsRollup|Rollup type')
_('OntapAggregateMetricsRollup|Statistic time')
_('OntapAggregateMetricsRollup|Total transfers')
_('OntapAggregateMetricsRollup|Total transfers max')
_('OntapAggregateMetricsRollup|Total transfers min')
_('OntapAggregateMetricsRollup|User read blocks')
_('OntapAggregateMetricsRollup|User read blocks max')
_('OntapAggregateMetricsRollup|User read blocks min')
_('OntapAggregateMetricsRollup|User reads')
_('OntapAggregateMetricsRollup|User reads max')
_('OntapAggregateMetricsRollup|User reads min')
_('OntapAggregateMetricsRollup|User write blocks')
_('OntapAggregateMetricsRollup|User write blocks max')
_('OntapAggregateMetricsRollup|User write blocks min')
_('OntapAggregateMetricsRollup|User writes')
_('OntapAggregateMetricsRollup|User writes max')
_('OntapAggregateMetricsRollup|User writes min')
_('Ontap disk derived metric')
_('OntapDiskDerivedMetric|Base counters')
_('OntapDiskDerivedMetric|Cp read blocks')
_('OntapDiskDerivedMetric|Cp read chain')
_('OntapDiskDerivedMetric|Cp read latency')
_('OntapDiskDerivedMetric|Cp reads')
_('OntapDiskDerivedMetric|Disk busy')
_('OntapDiskDerivedMetric|Guarenteed read blocks')
_('OntapDiskDerivedMetric|Guarenteed read chain')
_('OntapDiskDerivedMetric|Guarenteed read latency')
_('OntapDiskDerivedMetric|Guarenteed reads')
_('OntapDiskDerivedMetric|Guarenteed write blocks')
_('OntapDiskDerivedMetric|Guarenteed write chain')
_('OntapDiskDerivedMetric|Guarenteed write latency')
_('OntapDiskDerivedMetric|Guarenteed writes')
_('OntapDiskDerivedMetric|Interval')
_('OntapDiskDerivedMetric|Io pending')
_('OntapDiskDerivedMetric|Io queued')
_('OntapDiskDerivedMetric|Skip blocks')
_('OntapDiskDerivedMetric|Statistic time')
_('OntapDiskDerivedMetric|Total transfers')
_('OntapDiskDerivedMetric|User read blocks')
_('OntapDiskDerivedMetric|User read chain')
_('OntapDiskDerivedMetric|User read latency')
_('OntapDiskDerivedMetric|User reads')
_('OntapDiskDerivedMetric|User skip write ios')
_('OntapDiskDerivedMetric|User write blocks')
_('OntapDiskDerivedMetric|User write chain')
_('OntapDiskDerivedMetric|User write latency')
_('OntapDiskDerivedMetric|User writes')
_('OntapDiskDerivedMetric|User writes in skip mask')
_('Ontap disk metrics rollup')
_('OntapDiskMetricsRollup|Base counters')
_('OntapDiskMetricsRollup|Cp read blocks')
_('OntapDiskMetricsRollup|Cp read blocks max')
_('OntapDiskMetricsRollup|Cp read blocks min')
_('OntapDiskMetricsRollup|Cp read chain')
_('OntapDiskMetricsRollup|Cp read chain max')
_('OntapDiskMetricsRollup|Cp read chain min')
_('OntapDiskMetricsRollup|Cp read latency')
_('OntapDiskMetricsRollup|Cp read latency max')
_('OntapDiskMetricsRollup|Cp read latency min')
_('OntapDiskMetricsRollup|Cp reads')
_('OntapDiskMetricsRollup|Cp reads max')
_('OntapDiskMetricsRollup|Cp reads min')
_('OntapDiskMetricsRollup|Disk busy')
_('OntapDiskMetricsRollup|Disk busy max')
_('OntapDiskMetricsRollup|Disk busy min')
_('OntapDiskMetricsRollup|Guarenteed read blocks')
_('OntapDiskMetricsRollup|Guarenteed read blocks max')
_('OntapDiskMetricsRollup|Guarenteed read blocks min')
_('OntapDiskMetricsRollup|Guarenteed read chain')
_('OntapDiskMetricsRollup|Guarenteed read chain max')
_('OntapDiskMetricsRollup|Guarenteed read chain min')
_('OntapDiskMetricsRollup|Guarenteed read latency')
_('OntapDiskMetricsRollup|Guarenteed read latency max')
_('OntapDiskMetricsRollup|Guarenteed read latency min')
_('OntapDiskMetricsRollup|Guarenteed reads')
_('OntapDiskMetricsRollup|Guarenteed reads max')
_('OntapDiskMetricsRollup|Guarenteed reads min')
_('OntapDiskMetricsRollup|Guarenteed write blocks')
_('OntapDiskMetricsRollup|Guarenteed write blocks max')
_('OntapDiskMetricsRollup|Guarenteed write blocks min')
_('OntapDiskMetricsRollup|Guarenteed write chain')
_('OntapDiskMetricsRollup|Guarenteed write chain max')
_('OntapDiskMetricsRollup|Guarenteed write chain min')
_('OntapDiskMetricsRollup|Guarenteed write latency')
_('OntapDiskMetricsRollup|Guarenteed write latency max')
_('OntapDiskMetricsRollup|Guarenteed write latency min')
_('OntapDiskMetricsRollup|Guarenteed writes')
_('OntapDiskMetricsRollup|Guarenteed writes max')
_('OntapDiskMetricsRollup|Guarenteed writes min')
_('OntapDiskMetricsRollup|Interval')
_('OntapDiskMetricsRollup|Io pending')
_('OntapDiskMetricsRollup|Io pending max')
_('OntapDiskMetricsRollup|Io pending min')
_('OntapDiskMetricsRollup|Io queued')
_('OntapDiskMetricsRollup|Io queued max')
_('OntapDiskMetricsRollup|Io queued min')
_('OntapDiskMetricsRollup|Rollup type')
_('OntapDiskMetricsRollup|Skip blocks')
_('OntapDiskMetricsRollup|Skip blocks max')
_('OntapDiskMetricsRollup|Skip blocks min')
_('OntapDiskMetricsRollup|Statistic time')
_('OntapDiskMetricsRollup|Total transfers')
_('OntapDiskMetricsRollup|Total transfers max')
_('OntapDiskMetricsRollup|Total transfers min')
_('OntapDiskMetricsRollup|User read blocks')
_('OntapDiskMetricsRollup|User read blocks max')
_('OntapDiskMetricsRollup|User read blocks min')
_('OntapDiskMetricsRollup|User read chain')
_('OntapDiskMetricsRollup|User read chain max')
_('OntapDiskMetricsRollup|User read chain min')
_('OntapDiskMetricsRollup|User read latency')
_('OntapDiskMetricsRollup|User read latency max')
_('OntapDiskMetricsRollup|User read latency min')
_('OntapDiskMetricsRollup|User reads')
_('OntapDiskMetricsRollup|User reads max')
_('OntapDiskMetricsRollup|User reads min')
_('OntapDiskMetricsRollup|User skip write ios')
_('OntapDiskMetricsRollup|User skip write ios max')
_('OntapDiskMetricsRollup|User skip write ios min')
_('OntapDiskMetricsRollup|User write blocks')
_('OntapDiskMetricsRollup|User write blocks max')
_('OntapDiskMetricsRollup|User write blocks min')
_('OntapDiskMetricsRollup|User write chain')
_('OntapDiskMetricsRollup|User write chain max')
_('OntapDiskMetricsRollup|User write chain min')
_('OntapDiskMetricsRollup|User write latency')
_('OntapDiskMetricsRollup|User write latency max')
_('OntapDiskMetricsRollup|User write latency min')
_('OntapDiskMetricsRollup|User writes')
_('OntapDiskMetricsRollup|User writes in skip mask')
_('OntapDiskMetricsRollup|User writes in skip mask max')
_('OntapDiskMetricsRollup|User writes in skip mask min')
_('OntapDiskMetricsRollup|User writes max')
_('OntapDiskMetricsRollup|User writes min')
_('Ontap lun derived metric')
_('OntapLunDerivedMetric|Avg latency')
_('OntapLunDerivedMetric|Base counters')
_('OntapLunDerivedMetric|Interval')
_('OntapLunDerivedMetric|Other ops')
_('OntapLunDerivedMetric|Queue full')
_('OntapLunDerivedMetric|Read data')
_('OntapLunDerivedMetric|Read ops')
_('OntapLunDerivedMetric|Statistic time')
_('OntapLunDerivedMetric|Total ops')
_('OntapLunDerivedMetric|Write data')
_('OntapLunDerivedMetric|Write ops')
_('Ontap lun metrics rollup')
_('OntapLunMetricsRollup|Avg latency')
_('OntapLunMetricsRollup|Avg latency max')
_('OntapLunMetricsRollup|Avg latency min')
_('OntapLunMetricsRollup|Base counters')
_('OntapLunMetricsRollup|Interval')
_('OntapLunMetricsRollup|Other ops')
_('OntapLunMetricsRollup|Other ops max')
_('OntapLunMetricsRollup|Other ops min')
_('OntapLunMetricsRollup|Queue full')
_('OntapLunMetricsRollup|Queue full max')
_('OntapLunMetricsRollup|Queue full min')
_('OntapLunMetricsRollup|Read data')
_('OntapLunMetricsRollup|Read data max')
_('OntapLunMetricsRollup|Read data min')
_('OntapLunMetricsRollup|Read ops')
_('OntapLunMetricsRollup|Read ops max')
_('OntapLunMetricsRollup|Read ops min')
_('OntapLunMetricsRollup|Rollup type')
_('OntapLunMetricsRollup|Statistic time')
_('OntapLunMetricsRollup|Total ops')
_('OntapLunMetricsRollup|Total ops max')
_('OntapLunMetricsRollup|Total ops min')
_('OntapLunMetricsRollup|Write data')
_('OntapLunMetricsRollup|Write data max')
_('OntapLunMetricsRollup|Write data min')
_('OntapLunMetricsRollup|Write ops')
_('OntapLunMetricsRollup|Write ops max')
_('OntapLunMetricsRollup|Write ops min')
_('Ontap system derived metric')
_('OntapSystemDerivedMetric|Avg processor busy')
_('OntapSystemDerivedMetric|Base counters')
_('OntapSystemDerivedMetric|Cifs ops')
_('OntapSystemDerivedMetric|Cpu busy')
_('OntapSystemDerivedMetric|Disk data read')
_('OntapSystemDerivedMetric|Disk data written')
_('OntapSystemDerivedMetric|Fcp ops')
_('OntapSystemDerivedMetric|Http ops')
_('OntapSystemDerivedMetric|Interval')
_('OntapSystemDerivedMetric|Iscsi ops')
_('OntapSystemDerivedMetric|Net data recv')
_('OntapSystemDerivedMetric|Net data sent')
_('OntapSystemDerivedMetric|Nfs ops')
_('OntapSystemDerivedMetric|Read ops')
_('OntapSystemDerivedMetric|Statistic time')
_('OntapSystemDerivedMetric|Sys avg latency')
_('OntapSystemDerivedMetric|Sys read latency')
_('OntapSystemDerivedMetric|Sys write latency')
_('OntapSystemDerivedMetric|Total ops')
_('OntapSystemDerivedMetric|Total processor busy')
_('OntapSystemDerivedMetric|Write ops')
_('Ontap system metrics rollup')
_('OntapSystemMetricsRollup|Avg processor busy')
_('OntapSystemMetricsRollup|Avg processor busy max')
_('OntapSystemMetricsRollup|Avg processor busy min')
_('OntapSystemMetricsRollup|Base counters')
_('OntapSystemMetricsRollup|Cifs ops')
_('OntapSystemMetricsRollup|Cifs ops max')
_('OntapSystemMetricsRollup|Cifs ops min')
_('OntapSystemMetricsRollup|Cpu busy')
_('OntapSystemMetricsRollup|Cpu busy max')
_('OntapSystemMetricsRollup|Cpu busy min')
_('OntapSystemMetricsRollup|Disk data read')
_('OntapSystemMetricsRollup|Disk data read max')
_('OntapSystemMetricsRollup|Disk data read min')
_('OntapSystemMetricsRollup|Disk data written')
_('OntapSystemMetricsRollup|Disk data written max')
_('OntapSystemMetricsRollup|Disk data written min')
_('OntapSystemMetricsRollup|Fcp ops')
_('OntapSystemMetricsRollup|Fcp ops max')
_('OntapSystemMetricsRollup|Fcp ops min')
_('OntapSystemMetricsRollup|Http ops')
_('OntapSystemMetricsRollup|Http ops max')
_('OntapSystemMetricsRollup|Http ops min')
_('OntapSystemMetricsRollup|Interval')
_('OntapSystemMetricsRollup|Iscsi ops')
_('OntapSystemMetricsRollup|Iscsi ops max')
_('OntapSystemMetricsRollup|Iscsi ops min')
_('OntapSystemMetricsRollup|Net data recv')
_('OntapSystemMetricsRollup|Net data recv max')
_('OntapSystemMetricsRollup|Net data recv min')
_('OntapSystemMetricsRollup|Net data sent')
_('OntapSystemMetricsRollup|Net data sent max')
_('OntapSystemMetricsRollup|Net data sent min')
_('OntapSystemMetricsRollup|Nfs ops')
_('OntapSystemMetricsRollup|Nfs ops max')
_('OntapSystemMetricsRollup|Nfs ops min')
_('OntapSystemMetricsRollup|Read ops')
_('OntapSystemMetricsRollup|Read ops max')
_('OntapSystemMetricsRollup|Read ops min')
_('OntapSystemMetricsRollup|Rollup type')
_('OntapSystemMetricsRollup|Statistic time')
_('OntapSystemMetricsRollup|Sys avg latency')
_('OntapSystemMetricsRollup|Sys avg latency max')
_('OntapSystemMetricsRollup|Sys avg latency min')
_('OntapSystemMetricsRollup|Sys read latency')
_('OntapSystemMetricsRollup|Sys read latency max')
_('OntapSystemMetricsRollup|Sys read latency min')
_('OntapSystemMetricsRollup|Sys write latency')
_('OntapSystemMetricsRollup|Sys write latency max')
_('OntapSystemMetricsRollup|Sys write latency min')
_('OntapSystemMetricsRollup|Total ops')
_('OntapSystemMetricsRollup|Total ops max')
_('OntapSystemMetricsRollup|Total ops min')
_('OntapSystemMetricsRollup|Total processor busy')
_('OntapSystemMetricsRollup|Total processor busy max')
_('OntapSystemMetricsRollup|Total processor busy min')
_('OntapSystemMetricsRollup|Write ops')
_('OntapSystemMetricsRollup|Write ops max')
_('OntapSystemMetricsRollup|Write ops min')
_('Ontap volume derived metric')
_('OntapVolumeDerivedMetric|Avg latency')
_('OntapVolumeDerivedMetric|Base counters')
_('OntapVolumeDerivedMetric|Cifs other latency')
_('OntapVolumeDerivedMetric|Cifs other ops')
_('OntapVolumeDerivedMetric|Cifs read data')
_('OntapVolumeDerivedMetric|Cifs read latency')
_('OntapVolumeDerivedMetric|Cifs read ops')
_('OntapVolumeDerivedMetric|Cifs write data')
_('OntapVolumeDerivedMetric|Cifs write latency')
_('OntapVolumeDerivedMetric|Cifs write ops')
_('OntapVolumeDerivedMetric|Interval')
_('OntapVolumeDerivedMetric|Nfs other latency')
_('OntapVolumeDerivedMetric|Nfs other ops')
_('OntapVolumeDerivedMetric|Nfs read data')
_('OntapVolumeDerivedMetric|Nfs read latency')
_('OntapVolumeDerivedMetric|Nfs read ops')
_('OntapVolumeDerivedMetric|Nfs write data')
_('OntapVolumeDerivedMetric|Nfs write latency')
_('OntapVolumeDerivedMetric|Nfs write ops')
_('OntapVolumeDerivedMetric|Other latency')
_('OntapVolumeDerivedMetric|Other ops')
_('OntapVolumeDerivedMetric|Queue depth')
_('OntapVolumeDerivedMetric|Read data')
_('OntapVolumeDerivedMetric|Read latency')
_('OntapVolumeDerivedMetric|Read ops')
_('OntapVolumeDerivedMetric|San other latency')
_('OntapVolumeDerivedMetric|San other ops')
_('OntapVolumeDerivedMetric|San read data')
_('OntapVolumeDerivedMetric|San read latency')
_('OntapVolumeDerivedMetric|San read ops')
_('OntapVolumeDerivedMetric|San write data')
_('OntapVolumeDerivedMetric|San write latency')
_('OntapVolumeDerivedMetric|San write ops')
_('OntapVolumeDerivedMetric|Statistic time')
_('OntapVolumeDerivedMetric|Total ops')
_('OntapVolumeDerivedMetric|Write data')
_('OntapVolumeDerivedMetric|Write latency')
_('OntapVolumeDerivedMetric|Write ops')
_('Ontap volume metrics rollup')
_('OntapVolumeMetricsRollup|Avg latency')
_('OntapVolumeMetricsRollup|Avg latency max')
_('OntapVolumeMetricsRollup|Avg latency min')
_('OntapVolumeMetricsRollup|Base counters')
_('OntapVolumeMetricsRollup|Cifs other latency')
_('OntapVolumeMetricsRollup|Cifs other latency max')
_('OntapVolumeMetricsRollup|Cifs other latency min')
_('OntapVolumeMetricsRollup|Cifs other ops')
_('OntapVolumeMetricsRollup|Cifs other ops max')
_('OntapVolumeMetricsRollup|Cifs other ops min')
_('OntapVolumeMetricsRollup|Cifs read data')
_('OntapVolumeMetricsRollup|Cifs read data max')
_('OntapVolumeMetricsRollup|Cifs read data min')
_('OntapVolumeMetricsRollup|Cifs read latency')
_('OntapVolumeMetricsRollup|Cifs read latency max')
_('OntapVolumeMetricsRollup|Cifs read latency min')
_('OntapVolumeMetricsRollup|Cifs read ops')
_('OntapVolumeMetricsRollup|Cifs read ops max')
_('OntapVolumeMetricsRollup|Cifs read ops min')
_('OntapVolumeMetricsRollup|Cifs write data')
_('OntapVolumeMetricsRollup|Cifs write data max')
_('OntapVolumeMetricsRollup|Cifs write data min')
_('OntapVolumeMetricsRollup|Cifs write latency')
_('OntapVolumeMetricsRollup|Cifs write latency max')
_('OntapVolumeMetricsRollup|Cifs write latency min')
_('OntapVolumeMetricsRollup|Cifs write ops')
_('OntapVolumeMetricsRollup|Cifs write ops max')
_('OntapVolumeMetricsRollup|Cifs write ops min')
_('OntapVolumeMetricsRollup|Interval')
_('OntapVolumeMetricsRollup|Nfs other latency')
_('OntapVolumeMetricsRollup|Nfs other latency max')
_('OntapVolumeMetricsRollup|Nfs other latency min')
_('OntapVolumeMetricsRollup|Nfs other ops')
_('OntapVolumeMetricsRollup|Nfs other ops max')
_('OntapVolumeMetricsRollup|Nfs other ops min')
_('OntapVolumeMetricsRollup|Nfs read data')
_('OntapVolumeMetricsRollup|Nfs read data max')
_('OntapVolumeMetricsRollup|Nfs read data min')
_('OntapVolumeMetricsRollup|Nfs read latency')
_('OntapVolumeMetricsRollup|Nfs read latency max')
_('OntapVolumeMetricsRollup|Nfs read latency min')
_('OntapVolumeMetricsRollup|Nfs read ops')
_('OntapVolumeMetricsRollup|Nfs read ops max')
_('OntapVolumeMetricsRollup|Nfs read ops min')
_('OntapVolumeMetricsRollup|Nfs write data')
_('OntapVolumeMetricsRollup|Nfs write data max')
_('OntapVolumeMetricsRollup|Nfs write data min')
_('OntapVolumeMetricsRollup|Nfs write latency')
_('OntapVolumeMetricsRollup|Nfs write latency max')
_('OntapVolumeMetricsRollup|Nfs write latency min')
_('OntapVolumeMetricsRollup|Nfs write ops')
_('OntapVolumeMetricsRollup|Nfs write ops max')
_('OntapVolumeMetricsRollup|Nfs write ops min')
_('OntapVolumeMetricsRollup|Other latency')
_('OntapVolumeMetricsRollup|Other latency max')
_('OntapVolumeMetricsRollup|Other latency min')
_('OntapVolumeMetricsRollup|Other ops')
_('OntapVolumeMetricsRollup|Other ops max')
_('OntapVolumeMetricsRollup|Other ops min')
_('OntapVolumeMetricsRollup|Read data')
_('OntapVolumeMetricsRollup|Read data max')
_('OntapVolumeMetricsRollup|Read data min')
_('OntapVolumeMetricsRollup|Read latency')
_('OntapVolumeMetricsRollup|Read latency max')
_('OntapVolumeMetricsRollup|Read latency min')
_('OntapVolumeMetricsRollup|Read ops')
_('OntapVolumeMetricsRollup|Read ops max')
_('OntapVolumeMetricsRollup|Read ops min')
_('OntapVolumeMetricsRollup|Rollup type')
_('OntapVolumeMetricsRollup|San other latency')
_('OntapVolumeMetricsRollup|San other latency max')
_('OntapVolumeMetricsRollup|San other latency min')
_('OntapVolumeMetricsRollup|San other ops')
_('OntapVolumeMetricsRollup|San other ops max')
_('OntapVolumeMetricsRollup|San other ops min')
_('OntapVolumeMetricsRollup|San read data')
_('OntapVolumeMetricsRollup|San read data max')
_('OntapVolumeMetricsRollup|San read data min')
_('OntapVolumeMetricsRollup|San read latency')
_('OntapVolumeMetricsRollup|San read latency max')
_('OntapVolumeMetricsRollup|San read latency min')
_('OntapVolumeMetricsRollup|San read ops')
_('OntapVolumeMetricsRollup|San read ops max')
_('OntapVolumeMetricsRollup|San read ops min')
_('OntapVolumeMetricsRollup|San write data')
_('OntapVolumeMetricsRollup|San write data max')
_('OntapVolumeMetricsRollup|San write data min')
_('OntapVolumeMetricsRollup|San write latency')
_('OntapVolumeMetricsRollup|San write latency max')
_('OntapVolumeMetricsRollup|San write latency min')
_('OntapVolumeMetricsRollup|San write ops')
_('OntapVolumeMetricsRollup|San write ops max')
_('OntapVolumeMetricsRollup|San write ops min')
_('OntapVolumeMetricsRollup|Statistic time')
_('OntapVolumeMetricsRollup|Total ops')
_('OntapVolumeMetricsRollup|Total ops max')
_('OntapVolumeMetricsRollup|Total ops min')
_('OntapVolumeMetricsRollup|Write data')
_('OntapVolumeMetricsRollup|Write data max')
_('OntapVolumeMetricsRollup|Write data min')
_('OntapVolumeMetricsRollup|Write latency')
_('OntapVolumeMetricsRollup|Write latency max')
_('OntapVolumeMetricsRollup|Write latency min')
_('OntapVolumeMetricsRollup|Write ops')
_('OntapVolumeMetricsRollup|Write ops max')
_('OntapVolumeMetricsRollup|Write ops min')
_('Operating system')
_('OperatingSystem|Bitness')
_('OperatingSystem|Build number')
_('OperatingSystem|Distribution')
_('OperatingSystem|Lockout duration')
_('OperatingSystem|Lockout threshold')
_('OperatingSystem|Max pw age')
_('OperatingSystem|Min pw age')
_('OperatingSystem|Min pw len')
_('OperatingSystem|Name')
_('OperatingSystem|Product key')
_('OperatingSystem|Product name')
_('OperatingSystem|Product type')
_('OperatingSystem|Productid')
_('OperatingSystem|Pw complex')
_('OperatingSystem|Pw encrypt')
_('OperatingSystem|Pw hist')
_('OperatingSystem|Reset lockout counter')
_('OperatingSystem|Service pack')
_('OperatingSystem|System root')
_('OperatingSystem|System type')
_('OperatingSystem|Version')
_('Orchestration stack')
_('OrchestrationStack|Ancestry')
_('OrchestrationStack|Description')
_('OrchestrationStack|Ems ref')
_('OrchestrationStack|Name')
_('OrchestrationStack|Status')
_('Orchestration stack output')
_('OrchestrationStackOutput|Description')
_('OrchestrationStackOutput|Ems ref')
_('OrchestrationStackOutput|Key')
_('OrchestrationStackOutput|Value')
_('Orchestration stack parameter')
_('OrchestrationStackParameter|Ems ref')
_('OrchestrationStackParameter|Name')
_('OrchestrationStackParameter|Value')
_('Orchestration stack resource')
_('OrchestrationStackResource|Description')
_('OrchestrationStackResource|Ems ref')
_('OrchestrationStackResource|Last updated')
_('OrchestrationStackResource|Logical resource')
_('OrchestrationStackResource|Name')
_('OrchestrationStackResource|Physical resource')
_('OrchestrationStackResource|Resource category')
_('OrchestrationStackResource|Resource status')
_('OrchestrationStackResource|Resource status reason')
_('Orchestration template')
_('OrchestrationTemplate|Content')
_('OrchestrationTemplate|Description')
_('OrchestrationTemplate|Ems ref')
_('OrchestrationTemplate|Name')
_('Os process')
_('OsProcess|Cpu time')
_('OsProcess|Created on')
_('OsProcess|Memory size')
_('OsProcess|Memory usage')
_('OsProcess|Name')
_('OsProcess|Percent cpu')
_('OsProcess|Percent memory')
_('OsProcess|Pid')
_('OsProcess|Priority')
_('OsProcess|Updated on')
_('Partition')
_('Partition|Controller')
_('Partition|Created on')
_('Partition|Free space')
_('Partition|Location')
_('Partition|Name')
_('Partition|Partition type')
_('Partition|Size')
_('Partition|Start address')
_('Partition|Uid')
_('Partition|Updated on')
_('Partition|Used space')
_('Partition|Virtual disk file')
_('Partition|Volume group')
_('Patch')
_('Patch|Created on')
_('Patch|Description')
_('Patch|Installed')
_('Patch|Installed on')
_('Patch|Is valid')
_('Patch|Name')
_('Patch|Service pack')
_('Patch|Updated on')
_('Patch|Vendor')
_('Picture')
_('Picture|Resource type')
_('Policy event')
_('PolicyEvent|Event type')
_('PolicyEvent|Miq event description')
_('PolicyEvent|Miq policy description')
_('PolicyEvent|Result')
_('PolicyEvent|Target class')
_('PolicyEvent|Target name')
_('PolicyEvent|Timestamp')
_('PolicyEvent|Username')
_('Policy event content')
_('PolicyEventContent|Resource description')
_('PolicyEventContent|Resource type')
_('Product update')
_('ProductUpdate|Arch')
_('ProductUpdate|Build')
_('ProductUpdate|Component')
_('ProductUpdate|Created on')
_('ProductUpdate|Description')
_('ProductUpdate|Md5')
_('ProductUpdate|Name')
_('ProductUpdate|Platform')
_('ProductUpdate|Update type')
_('ProductUpdate|Updated on')
_('ProductUpdate|Version')
_('ProductUpdate|Vmdb schema version')
_('Proxy task')
_('ProxyTask|Command')
_('ProxyTask|Created on')
_('ProxyTask|Priority')
_('ProxyTask|State')
_('ProxyTask|Updated on')
_('Pxe image')
_('PxeImage|Default for windows')
_('PxeImage|Description')
_('PxeImage|Initrd')
_('PxeImage|Kernel')
_('PxeImage|Kernel options')
_('PxeImage|Name')
_('PxeImage|Path')
_('Pxe image type')
_('PxeImageType|Name')
_('PxeImageType|Provision type')
_('Pxe menu')
_('PxeMenu|Contents')
_('PxeMenu|File name')
_('Pxe server')
_('PxeServer|Access url')
_('PxeServer|Customization directory')
_('PxeServer|Last refresh on')
_('PxeServer|Name')
_('PxeServer|Pxe directory')
_('PxeServer|Uri')
_('PxeServer|Uri prefix')
_('PxeServer|Visibility')
_('PxeServer|Windows images directory')
_('Registry item')
_('RegistryItem|Created on')
_('RegistryItem|Data')
_('RegistryItem|Format')
_('RegistryItem|Name')
_('RegistryItem|Updated on')
_('RegistryItem|Value name')
_('Relationship')
_('Relationship|Ancestry')
_('Relationship|Relationship')
_('Relationship|Resource type')
_('Repository')
_('Repository|Created on')
_('Repository|Name')
_('Repository|Relative path')
_('Repository|Updated on')
_('Reserve')
_('Reserve|Reserved')
_('Reserve|Resource type')
_('Resource action')
_('ResourceAction|Action')
_('ResourceAction|Ae attributes')
_('ResourceAction|Ae class')
_('ResourceAction|Ae instance')
_('ResourceAction|Ae message')
_('ResourceAction|Ae namespace')
_('ResourceAction|Resource type')
_('Resource pool')
_('ResourcePool|Cpu limit')
_('ResourcePool|Cpu reserve')
_('ResourcePool|Cpu reserve expand')
_('ResourcePool|Cpu shares')
_('ResourcePool|Cpu shares level')
_('ResourcePool|Created on')
_('ResourcePool|Ems ref')
_('ResourcePool|Ems ref obj')
_('ResourcePool|Is default')
_('ResourcePool|Memory limit')
_('ResourcePool|Memory reserve')
_('ResourcePool|Memory reserve expand')
_('ResourcePool|Memory shares')
_('ResourcePool|Memory shares level')
_('ResourcePool|Name')
_('ResourcePool|Uid ems')
_('ResourcePool|Updated on')
_('ResourcePool|Vapp')
_('Rr pending change')
_('RrPendingChange|Change key')
_('RrPendingChange|Change new key')
_('RrPendingChange|Change table')
_('RrPendingChange|Change time')
_('RrPendingChange|Change type')
_('Rr sync state')
_('RrSyncState|State')
_('RrSyncState|Table name')
_('Rss feed')
_('RssFeed|Created on')
_('RssFeed|Description')
_('RssFeed|Link')
_('RssFeed|Name')
_('RssFeed|Title')
_('RssFeed|Updated on')
_('RssFeed|Yml file mtime')
_('Scan history')
_('ScanHistory|Created on')
_('ScanHistory|Finished on')
_('ScanHistory|Message')
_('ScanHistory|Started on')
_('ScanHistory|Status')
_('ScanHistory|Status code')
_('ScanHistory|Updated on')
_('Scan item')
_('ScanItem|Created on')
_('ScanItem|Definition')
_('ScanItem|Description')
_('ScanItem|File mtime')
_('ScanItem|Filename')
_('ScanItem|Guid')
_('ScanItem|Item type')
_('ScanItem|Mode')
_('ScanItem|Name')
_('ScanItem|Prod default')
_('ScanItem|Updated on')
_('Scan item set')
_('ScanItemSet|Created on')
_('ScanItemSet|Description')
_('ScanItemSet|Guid')
_('ScanItemSet|Mode')
_('ScanItemSet|Name')
_('ScanItemSet|Owner type')
_('ScanItemSet|Read only')
_('ScanItemSet|Set data')
_('ScanItemSet|Set type')
_('ScanItemSet|Updated on')
_('ScanItemSet|Userid')
_('Security group')
_('SecurityGroup|Description')
_('SecurityGroup|Ems ref')
_('SecurityGroup|Name')
_('Server role')
_('ServerRole|Created on')
_('ServerRole|Description')
_('ServerRole|External failover')
_('ServerRole|License required')
_('ServerRole|Max concurrent')
_('ServerRole|Name')
_('ServerRole|Role scope')
_('ServerRole|Updated on')
_('Service')
_('Service|Description')
_('Service|Display')
_('Service|Guid')
_('Service|Name')
_('Service|Options')
_('Service|Retired')
_('Service|Retirement last warn')
_('Service|Retirement state')
_('Service|Retirement warn')
_('Service|Retires on')
_('Service resource')
_('ServiceResource|Group idx')
_('ServiceResource|Name')
_('ServiceResource|Provision index')
_('ServiceResource|Resource type')
_('ServiceResource|Scaling max')
_('ServiceResource|Scaling min')
_('ServiceResource|Source type')
_('ServiceResource|Start action')
_('ServiceResource|Start delay')
_('ServiceResource|Stop action')
_('ServiceResource|Stop delay')
_('Service template')
_('ServiceTemplate|Description')
_('ServiceTemplate|Display')
_('ServiceTemplate|Guid')
_('ServiceTemplate|Long description')
_('ServiceTemplate|Name')
_('ServiceTemplate|Options')
_('ServiceTemplate|Prov type')
_('ServiceTemplate|Provision cost')
_('ServiceTemplate|Service type')
_('Service template catalog')
_('ServiceTemplateCatalog|Description')
_('ServiceTemplateCatalog|Name')
_('Snapshot')
_('Snapshot|Create time')
_('Snapshot|Created on')
_('Snapshot|Current')
_('Snapshot|Description')
_('Snapshot|Disks')
_('Snapshot|Ems ref')
_('Snapshot|Ems ref obj')
_('Snapshot|Filename')
_('Snapshot|Name')
_('Snapshot|Parent uid')
_('Snapshot|Total size')
_('Snapshot|Uid')
_('Snapshot|Uid ems')
_('Snapshot|Updated on')
_('Storage')
_('Storage|Created on')
_('Storage|Directory hierarchy supported')
_('Storage|Ems ref')
_('Storage|Ems ref obj')
_('Storage|Free space')
_('Storage|Last perf capture on')
_('Storage|Last scan on')
_('Storage|Location')
_('Storage|Master')
_('Storage|Multiplehostaccess')
_('Storage|Name')
_('Storage|Raw disk mappings supported')
_('Storage|Storage domain type')
_('Storage|Store type')
_('Storage|Thin provisioning supported')
_('Storage|Total space')
_('Storage|Uncommitted')
_('Storage|Updated on')
_('Storage file')
_('StorageFile|Base name')
_('StorageFile|Ext name')
_('StorageFile|Mtime')
_('StorageFile|Name')
_('StorageFile|Rsc type')
_('StorageFile|Size')
_('Storage manager')
_('StorageManager|Agent type')
_('StorageManager|Hostname')
_('StorageManager|Ipaddress')
_('StorageManager|Last update status')
_('StorageManager|Name')
_('StorageManager|Port')
_('StorageManager|Type spec data')
_('StorageManager|Vendor')
_('StorageManager|Version')
_('Storage metrics metadata')
_('StorageMetricsMetadata|Counter info')
_('Switch')
_('Switch|Allow promiscuous')
_('Switch|Created on')
_('Switch|Forged transmits')
_('Switch|Mac changes')
_('Switch|Name')
_('Switch|Ports')
_('Switch|Uid ems')
_('Switch|Updated on')
_('System service')
_('SystemService|Depend on group')
_('SystemService|Depend on service')
_('SystemService|Description')
_('SystemService|Disable run levels')
_('SystemService|Display name')
_('SystemService|Enable run levels')
_('SystemService|Image path')
_('SystemService|Name')
_('SystemService|Object name')
_('SystemService|Running')
_('SystemService|Start')
_('SystemService|Svc type')
_('SystemService|Typename')
_('Tag')
_('Tag|Name')
_('Tagging')
_('Tagging|Taggable type')
_('Time profile')
_('TimeProfile|Created on')
_('TimeProfile|Description')
_('TimeProfile|Profile')
_('TimeProfile|Profile key')
_('TimeProfile|Profile type')
_('TimeProfile|Rollup daily metrics')
_('TimeProfile|Updated on')
_('Ui task')
_('UiTask|Area')
_('UiTask|Created on')
_('UiTask|Name')
_('UiTask|Task')
_('UiTask|Typ')
_('UiTask|Updated on')
_('Ui task set')
_('UiTaskSet|Created on')
_('UiTaskSet|Description')
_('UiTaskSet|Guid')
_('UiTaskSet|Mode')
_('UiTaskSet|Name')
_('UiTaskSet|Owner type')
_('UiTaskSet|Read only')
_('UiTaskSet|Set data')
_('UiTaskSet|Set type')
_('UiTaskSet|Updated on')
_('UiTaskSet|Userid')
_('User')
_('User|Created on')
_('User|Email')
_('User|Filters')
_('User|First name')
_('User|Icon')
_('User|Last name')
_('User|Lastlogoff')
_('User|Lastlogon')
_('User|Name')
_('User|Password digest')
_('User|Region')
_('User|Settings')
_('User|Updated on')
_('User|Userid')
_('Vim performance operating range')
_('VimPerformanceOperatingRange|Days')
_('VimPerformanceOperatingRange|Resource type')
_('VimPerformanceOperatingRange|Values')
_('Vim performance state')
_('VimPerformanceState|Capture interval')
_('VimPerformanceState|Resource type')
_('VimPerformanceState|State data')
_('VimPerformanceState|Timestamp')
_('Vim performance tag value')
_('VimPerformanceTagValue|Assoc ids')
_('VimPerformanceTagValue|Association type')
_('VimPerformanceTagValue|Category')
_('VimPerformanceTagValue|Column name')
_('VimPerformanceTagValue|Metric type')
_('VimPerformanceTagValue|Tag name')
_('VimPerformanceTagValue|Value')
_('Vm or template')
_('VmOrTemplate|Autostart')
_('VmOrTemplate|Blackbox exists')
_('VmOrTemplate|Blackbox validated')
_('VmOrTemplate|Boot time')
_('VmOrTemplate|Busy')
_('VmOrTemplate|Cloud')
_('VmOrTemplate|Config xml')
_('VmOrTemplate|Connection state')
_('VmOrTemplate|Cpu affinity')
_('VmOrTemplate|Cpu limit')
_('VmOrTemplate|Cpu reserve')
_('VmOrTemplate|Cpu reserve expand')
_('VmOrTemplate|Cpu shares')
_('VmOrTemplate|Cpu shares level')
_('VmOrTemplate|Created on')
_('VmOrTemplate|Description')
_('VmOrTemplate|Ems created on')
_('VmOrTemplate|Ems ref')
_('VmOrTemplate|Ems ref obj')
_('VmOrTemplate|Fault tolerance')
_('VmOrTemplate|Format')
_('VmOrTemplate|Guid')
_('VmOrTemplate|Last perf capture on')
_('VmOrTemplate|Last scan attempt on')
_('VmOrTemplate|Last scan on')
_('VmOrTemplate|Last sync on')
_('VmOrTemplate|Linked clone')
_('VmOrTemplate|Location')
_('VmOrTemplate|Memory limit')
_('VmOrTemplate|Memory reserve')
_('VmOrTemplate|Memory reserve expand')
_('VmOrTemplate|Memory shares')
_('VmOrTemplate|Memory shares level')
_('VmOrTemplate|Name')
_('VmOrTemplate|Power state')
_('VmOrTemplate|Previous state')
_('VmOrTemplate|Publicly available')
_('VmOrTemplate|Raw power state')
_('VmOrTemplate|Registered')
_('VmOrTemplate|Retired')
_('VmOrTemplate|Retirement last warn')
_('VmOrTemplate|Retirement state')
_('VmOrTemplate|Retirement warn')
_('VmOrTemplate|Retires on')
_('VmOrTemplate|Smart')
_('VmOrTemplate|Standby action')
_('VmOrTemplate|State changed on')
_('VmOrTemplate|Template')
_('VmOrTemplate|Tools status')
_('VmOrTemplate|Uid ems')
_('VmOrTemplate|Updated on')
_('VmOrTemplate|Vendor')
_('VmOrTemplate|Version')
_('VmOrTemplate|Vnc port')
_('Vmdb database')
_('VmdbDatabase|Data directory')
_('VmdbDatabase|Data disk')
_('VmdbDatabase|Ipaddress')
_('VmdbDatabase|Last start time')
_('VmdbDatabase|Name')
_('VmdbDatabase|Vendor')
_('VmdbDatabase|Version')
_('Vmdb database metric')
_('VmdbDatabaseMetric|Active connections')
_('VmdbDatabaseMetric|Capture interval name')
_('VmdbDatabaseMetric|Disk free bytes')
_('VmdbDatabaseMetric|Disk free inodes')
_('VmdbDatabaseMetric|Disk total bytes')
_('VmdbDatabaseMetric|Disk total inodes')
_('VmdbDatabaseMetric|Disk used bytes')
_('VmdbDatabaseMetric|Disk used inodes')
_('VmdbDatabaseMetric|Running processes')
_('VmdbDatabaseMetric|Timestamp')
_('Vmdb index')
_('VmdbIndex|Name')
_('VmdbIndex|Prior raw metrics')
_('Vmdb metric')
_('VmdbMetric|Capture interval name')
_('VmdbMetric|Index rows fetched')
_('VmdbMetric|Index scans')
_('VmdbMetric|Last analyze date')
_('VmdbMetric|Last autoanalyze date')
_('VmdbMetric|Last autovacuum date')
_('VmdbMetric|Last vacuum date')
_('VmdbMetric|Otta')
_('VmdbMetric|Pages')
_('VmdbMetric|Percent bloat')
_('VmdbMetric|Resource type')
_('VmdbMetric|Rows')
_('VmdbMetric|Rows dead')
_('VmdbMetric|Rows deleted')
_('VmdbMetric|Rows hot updated')
_('VmdbMetric|Rows inserted')
_('VmdbMetric|Rows live')
_('VmdbMetric|Rows updated')
_('VmdbMetric|Sequential rows read')
_('VmdbMetric|Size')
_('VmdbMetric|Table scans')
_('VmdbMetric|Timestamp')
_('VmdbMetric|Wasted bytes')
_('Vmdb table')
_('VmdbTable|Name')
_('VmdbTable|Prior raw metrics')
_('Volume')
_('Volume|Created on')
_('Volume|Filesystem')
_('Volume|Free space')
_('Volume|Name')
_('Volume|Size')
_('Volume|Typ')
_('Volume|Uid')
_('Volume|Updated on')
_('Volume|Used space')
_('Volume|Volume group')
_('Windows image')
_('WindowsImage|Description')
_('WindowsImage|Index')
_('WindowsImage|Name')
_('WindowsImage|Path')
_('Zone')
_('Zone|Created on')
_('Zone|Description')
_('Zone|Name')
_('Zone|Settings')
_('Zone|Updated on')
#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
